### PR TITLE
bump libovsdb

### PR DESCRIPTION
**Pull request by dave-tucker**
/cc @trozet

### CODE REVIEW

**Comment by dave-tucker** [comment]
I think it's likely something in the revamped server impl that is at fault
(part of pr 222). I'll look tomorrow with fresh eyes and see if  I can
figure it out.

**Comment by dave-tucker** [comment]
Pulled in ovn-org/libovsdb#238, which fixes some of the issues with the libovsdb server (used in test).
Rebased and :crossed_fingers: CI will be green

**Comment by dave-tucker** [comment]
pulled in ovn-org/libovsdb#239 which fixes another cache issue. tests pass locally for me

**Review by trozet — APPROVED** [review]

**Pull request merged**
