### PR TITLE
kind dualstack support

### PR DESCRIPTION
**Pull request by Billy99**
This PR has 2 commits. First is to enable dual-stack running in a KIND deployment. The second are some hacks to move the deployment with OVN-Kubernetes forward and not intended to be merged..

### CODE REVIEW

**Comment by Billy99** [comment]
@trozet @danwinship PTAL

**Comment by dcbw** [comment]
@Billy99 can you rebase?

**Comment by dcbw** [comment]
@Billy99 sorry, needs another rebase :(

**Comment by Billy99** [comment]
Looks like I screwed up the commit history. I'll look into it.

**Comment by Billy99** [comment]
> Looks like I screwed up the commit history. I'll look into it.

It was to hard to unwind and not worth the time. Abandoning this PR and started over with #1248

**Pull request closed without merging**
