### PR TITLE
Update client-go

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
**- What this PR does and why is it needed**

Update client gen and related packages from  v0.17.4 -> v0.18.5. This brings the client-go code 
up to date and will allow the use of the code generation scripts easier when adding CRDs 

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by aojea** [comment]
wow, this is great ... but do we need to vendor all the dependencies?

**Comment by JacobTanenbaum** [comment]
@aojea I didn't think I added anything, anything that came in came in from` go mod vendor` when I bumped the version.

**Comment by aojea** [comment]
sorry, I was more thinking in loud than a question directed to the PR :sweat_smile: 
This seems a typical struggle in golang projects,  If we want to keep the dependencies in the repo or just leverage the go.mod

**Comment by dcbw** [comment]
DCO failure looks like a github flake, all commits have DCO.

**Comment by aojea** [comment]
@JacobTanenbaum can you retry using a shorter title for the second commit? 
maybe that's "confusing" the dco bot :shrug:

**Comment by aojea** [comment]
ping @dcbw :)

**Pull request merged**
