### PR TITLE
Added egressIP count for services as prometheus metric.

### PR DESCRIPTION
**Pull request by gvbalaji**
This metric will have value 0 if no egressIP is configured otherwise a positive integer

Signed-off-by: Balaji Varadaraju <bvaradar@redhat.com>

### CODE REVIEW

**Comment by squeed** [comment]
I think kube-state-metrics already has this - https://github.com/kubernetes/kube-state-metrics/blob/5d56275d2b95ffcf6d15d8a6fa2b1bb02a1066ae/internal/store/service.go

kube-state-metrics is a program that exports data exclusively from kubernetes API objects.

**Comment by gvbalaji** [comment]
IN that case shall I close this PR?

**Comment by martinkennelly** [comment]
I think this should be closed. The cardinality is unbounded.

**Comment by martinkennelly** [comment]
Also, EgressIP count metric is already exported and like Dan said ExternalIP is not egressIP.

**Pull request closed without merging**
