### PR TITLE
Backport E2E fixes

### PR DESCRIPTION
**Pull request by kyrtapz**
Fixes: https://github.com/ovn-org/ovn-kubernetes/issues/4733
Fixes: https://github.com/ovn-org/ovn-kubernetes/issues/4719

cherry picked from commit d6f145e01a683b3a9d71c41289a7efc8ba8699d0
clean backport of https://github.com/ovn-org/ovn-kubernetes/pull/4385
cherry picked from commit https://github.com/ovn-org/ovn-kubernetes/commit/511e9c699ada9a8fe9f846823b2a8917cff51aa2

### CODE REVIEW

**Review by dceara — APPROVED** [review]
Looks good to me, thanks!

**Comment by tssurya** [comment]
I will hold merge till we figure out the new flakes that are appearing: the only known flakes I am aware of in release-1.0 are:  https://github.com/ovn-org/ovn-kubernetes/pull/4714#issuecomment-2345813460

**Comment by dceara** [comment]
> I will hold merge till we figure out the new flakes that are appearing: the only known flakes I am aware of in release-1.0 are: [#4714 (comment)](https://github.com/ovn-org/ovn-kubernetes/pull/4714#issuecomment-2345813460)

shard-conformance fails with (we see this often in ovn-org/ovn CI too):
```
Error: The action 'Run Tests' has timed out after 120 minutes.
```

The control-plane failures are:
```
 Summarizing 1 Failure:
  [FAIL] Services of type NodePort [It] should work on secondary node interfaces for ETP=local and ETP=cluster when backend pods are also served by EgressIP
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/e2e.go:351

 Summarizing 2 Failures:
  [FAIL] e2e egress firewall policy validation [AfterEach] Should validate the egress firewall DNS does not deadlock when adding many dnsNames
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/egress_firewall.go:113
  [FAIL] e2e egress firewall policy validation [AfterEach] Should validate the egress firewall allows inbound connections
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/egress_firewall.go:113
```

The last one seems to be because of:
```
2024-09-19T18:04:26.7701454Z   [38;5;9m[FAILED] failed to remove ip address 172.18.1.13 from node ovn-control-plane, err: "failed to run \"docker exec ovn-control-plane ip addr delete 172.18.1.13/32 dev breth0\": exit status 2 (Error: ipv4: Address not found.\n)"[0m
```

Which is what the original fix was trying to fix but for egress_firewall..  It seems to me we're just missing this commit on release-1.0:
https://github.com/ovn-org/ovn-kubernetes/commit/217ec65c6c67775f34116b60730297f024f1eab2

Should we cherry pick that one too?

**Comment by kyrtapz** [comment]
re-running `ovn-ci / e2e (external-gateway, noHA, shared, ipv4, noSnatGW, 2br, ic-single-node-zones)`

**Comment by kyrtapz** [comment]
re-running `ovn-ci / Upgrade OVN from Release-1.0 to PR branch based image (local)` - it timed out:
```
Error: The operation was canceled.
```

**Pull request merged**
