### PR TITLE
Recreate the ovnkube-node certificate if the node name changed

### PR DESCRIPTION
**Pull request by kyrtapz**
If the node name changes recreate the certificate using kubelets kubeconfig by removing the stale cert.
Otherwise the certificate request would be created by using the current cert(with the old node name) which the cert approver denies. 

Verified in kind with the following steps:
1. Rename a node:
```
docker exec ovn-worker sh -c 'echo " --hostname-override=ovn-worker-pro" >> /etc/default/kubelet'
docker exec ovn-worker systemctl restart kubelet
```
3. Accept the new node to the family:
```
kubectl get csr | awk '/Pending/ {print $1}' | xargs kubectl certificate approve
# wait a bit for the node to appear
kubectl label node ovn-worker-pro k8s.ovn.org/zone-name=ovn-worker-pro --overwrite 
```
5. Verify that the ovnkube-node cert got recreated:
```
kubectl get csr --sort-by=.metadata.creationTimestamp -o=jsonpath='{.items[-1].metadata.name}' | xargs kubectl describe csr
Name:                csr-l994w
Labels:              <none>
Annotations:         <none>
CreationTimestamp:   Fri, 16 Feb 2024 17:39:16 +0100
Requesting User:     system:node:ovn-worker-pro
Signer:              kubernetes.io/kube-apiserver-client
Requested Duration:  10m
Status:              Approved,Issued
Subject:
         Common Name:    system:ovn-node:ovn-worker-pro
         Serial Number:  
         Organization:   system:ovn-nodes
Events:  <none>

#pod logs:
E0216 16:39:16.323779    2762 kube.go:298] Unexpected common name found in the certificate, expected: "system:ovn-node:ovn-worker-pro", got: "system:ovn-node:ovn-worker", removing /var/run/ovn-kubernetes/certs/ovnkube-client-current.pem                                                                                                                                                                                          
I0216 16:39:16.323850    2762 certificate_manager.go:356] kubernetes.io/kube-apiserver-client: Certificate rotation is enabled                                                                                                                                                                                                                                                                                                        
I0216 16:39:16.323867    2762 kube.go:336] Waiting for certificate                                                                                                                                                                                                                                                                                                                                                                    
I0216 16:39:16.323900    2762 certificate_manager.go:356] kubernetes.io/kube-apiserver-client: Rotating certificates                                                                                                                                                                                                                                                                                                                  
I0216 16:39:16.324411    2762 cert_rotation.go:137] Starting client certificate rotation controller                                                                                                                                                                                                                                                                                                                                   
I0216 16:39:16.336609    2762 reflector.go:289] Starting reflector *v1.CertificateSigningRequest (0s) from k8s.io/client-go/tools/watch/informerwatcher.go:146                                                                                                                                                                                                                                                                        
I0216 16:39:16.336627    2762 reflector.go:325] Listing and watching *v1.CertificateSigningRequest from k8s.io/client-go/tools/watch/informerwatcher.go:146                                                                                                                                                                                                                                                                           
I0216 16:39:16.342682    2762 csr.go:261] certificate signing request csr-l994w is approved, waiting to be issued                                                                                                                                                                                                                                                                                                                     
I0216 16:39:16.350049    2762 csr.go:257] certificate signing request csr-l994w is issued  

#approver logs:
I0216 16:39:16.334609       1 recorder.go:104] "events: CSR \"csr-l994w\" has been approved" type="Normal" object={"kind":"CertificateSigningRequest","name":"csr-l994w"} reason="CSRApproved"
I0216 16:39:16.342579       1 approver.go:230] Finished syncing CSR csr-l994w for ovn-worker-pro node in 8.16257ms

```

### CODE REVIEW

**Comment by tssurya** [comment]
hmm wait, a "node rename" is a supported action in kubernetes? (https://kubernetes.io/docs/concepts/architecture/nodes/#node-name-uniqueness)

**Comment by kyrtapz** [comment]
> hmm wait, a "node rename" is a supported action in kubernetes? or are we supporting unsupported scenarios (https://kubernetes.io/docs/concepts/architecture/nodes/#node-name-uniqueness)
> 
> I see `--hostname-override` being used, is that intended to be used for node object renames? I guess it is supported: https://www.youtube.com/watch?v=TqoA9HwFLVU ?

node rename is supported kubernetes, kubelet will regenerate it's own certificates and the "new" node will appear in the API without removing the "old" one. Without this PR ovnkube-node will still create a CSR for the new node name but it will use it's current certificate to do that which will cause the cert approver to [reject the request](https://github.com/ovn-org/ovn-kubernetes/pull/4161/files#diff-daf9de695e0ff81f9173caf83cb88efa138e92a9b35439bd7044aa012ff931c0R291-R293).

**Review by trozet — APPROVED** [review]

**Comment by tssurya** [comment]
> > hmm wait, a "node rename" is a supported action in kubernetes? or are we supporting unsupported scenarios (https://kubernetes.io/docs/concepts/architecture/nodes/#node-name-uniqueness)
> > I see `--hostname-override` being used, is that intended to be used for node object renames? I guess it is supported: https://www.youtube.com/watch?v=TqoA9HwFLVU ?
> 
> node rename is supported in kubernetes, kubelet will regenerate it's own certificates and the "new" node will appear in the API without removing the "old" one. Without this PR ovnkube-node will still create a CSR for the new node name but it will use it's current certificate to do that which will cause the cert approver to [reject the request](https://github.com/ovn-org/ovn-kubernetes/pull/4161/files#diff-daf9de695e0ff81f9173caf83cb88efa138e92a9b35439bd7044aa012ff931c0R291-R293).

do you have docs or pointers around this.. "new" noed will appear in the API without removing "old" one means its a new node, not a rename right?

**Comment by danwinship** [comment]
> I see `--hostname-override` being used, is that intended to be used for node object renames?

No, that's supposed to be used from initial node creation time, in scenarios where the node's hostname doesn't correspond to what you want the node name to be.

> node rename is supported in kubernetes, kubelet will regenerate it's own certificates and the "new" node will appear in the API without removing the "old" one.

That sounds more like a bug than a feature. If this was supposed to work then the old object would get deleted. What's happening here is just that kubelet starts up, sees that there is no Node with its name, assumes that it is a newly-created node, and creates a new Node object accordingly.

**Pull request merged**
