### PR TITLE
gw: add default connection tracking rules even when NodePort is disabled

### PR DESCRIPTION
**Pull request by girishmg**
One can selectively enable NodePort on nodes in K8s cluster. This is
so that OVN control plane can scale well in large cluster. For example:
If you have 1000 node cluster, then you may not want to enable Load
Balancers on all of the 1000 nodes.

We only enable NodePort on few 10s of nodes that form the control plane
services nodes. The rest of the 990 nodes we don’t want it to be a
forwarding or routing entity for these services.

Irrespective of whether NodePort is enabled or not, we still need the
default OpenFlow rules on the host OVS bridge to connection track the
traffic comming in from the OVN logical topology (North-South).

Fixes: 3606ee31259b (Modifies local gateway mode functionality)

@trozet can you PTAL?

### CODE REVIEW

**Comment by trozet** [comment]
heh what timing @girishmg :) I just merged @dave-tucker where I had that comment:
https://github.com/ovn-org/ovn-kubernetes/pull/1586#discussion_r510465730

**Comment by girishmg** [comment]
@trozet :) yeah discovered this while testing something an hour ago.

But now that @dave-tucker's PR got merged, I will need to rebase this.

**Comment by dave-tucker** [comment]
I fixed it for the local gateway case @girishmg. You should only need to move the `if config.NodePortEnable` here https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/node/gateway_shared_intf.go#L492

**Comment by girishmg** [comment]
@dave-tucker @trozet can you PTAL?

**Review by trozet — APPROVED** [review]
/lgtm

**Pull request merged**
