### PR TITLE
Remove endpoint support & add endpointSlices support for ovnkube-node

### PR DESCRIPTION
**Pull request by Pardhakeswar**
Signed-off-by: Pardhakeswar Pacha <ppacha@nvidia.com>

### CODE REVIEW

**Comment by dcbw** [comment]
@Pardhakeswar looks like some of the errors in the CI are

`[It] should be able to change the type from ExternalName to NodePort [Conformance]`

and the PR touches some code in the NodePort watcher; is that error related to the code changes?

**Comment by astoycos** [comment]
```
2022-03-01T18:01:58.5452780Z [91m[1mSummarizing 8 Failures:[0m
2022-03-01T18:01:58.5452945Z 
2022-03-01T18:01:58.5454017Z [91m[1m[Fail] [0m[90m[sig-network] NetworkPolicyLegacy [LinuxOnly] [0m[0mNetworkPolicy between server and client [0m[91m[1m[It] should enforce updated policy [Feature:NetworkPolicy] [0m
2022-03-01T18:01:58.5454997Z [37m/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/netpol/network_legacy.go:1909[0m
2022-03-01T18:01:58.5455260Z 
2022-03-01T18:01:58.5455955Z [91m[1m[Fail] [0m[90m[sig-network] NetworkPolicyLegacy [LinuxOnly] [0m[0mNetworkPolicy between server and client [0m[91m[1m[BeforeEach] should enforce multiple ingress policies with ingress allow-all policy taking precedence [Feature:NetworkPolicy] [0m
2022-03-01T18:01:58.5456940Z [37m/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/netpol/network_legacy.go:1909[0m
2022-03-01T18:01:58.5457181Z 
2022-03-01T18:01:58.5457802Z [91m[1m[Fail] [0m[90m[sig-network] NetworkPolicyLegacy [LinuxOnly] [0m[0mNetworkPolicy between server and client [0m[91m[1m[It] should enforce multiple, stacked policies with overlapping podSelectors [Feature:NetworkPolicy] [0m
2022-03-01T18:01:58.5458577Z [37m/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/netpol/network_legacy.go:1909[0m
2022-03-01T18:01:58.5458830Z 
2022-03-01T18:01:58.5459248Z [91m[1m[Fail] [0m[90m[sig-network] Services [0m[91m[1m[It] should be able to change the type from ExternalName to NodePort [Conformance] [0m
2022-03-01T18:01:58.5459856Z [37m/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1375[0m
2022-03-01T18:01:58.5460095Z 
2022-03-01T18:01:58.5460507Z [91m[1m[Fail] [0m[90m[sig-network] Services [0m[91m[1m[It] should be able to change the type from ExternalName to NodePort [Conformance] [0m
2022-03-01T18:01:58.5461122Z [37m/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1375[0m
2022-03-01T18:01:58.5461358Z 
2022-03-01T18:01:58.5461748Z [91m[1m[Fail] [0m[90m[sig-network] Services [0m[91m[1m[It] should be able to change the type from ExternalName to NodePort [Conformance] [0m
2022-03-01T18:01:58.5462362Z [37m/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1375[0m
2022-03-01T18:01:58.5462603Z 
2022-03-01T18:01:58.5463005Z [91m[1m[Fail] [0m[90m[sig-network] Services [0m[91m[1m[It] should be able to change the type from ExternalName to NodePort [Conformance] [0m
2022-03-01T18:01:58.5463602Z [37m/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1375[0m
2022-03-01T18:01:58.5463837Z 
2022-03-01T18:01:58.5464235Z [91m[1m[Fail] [0m[90m[sig-network] Services [0m[91m[1m[It] should be able to change the type from ExternalName to NodePort [Conformance] [0m
2022-03-01T18:01:58.5464839Z [37m/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1375[0m
2022-03-01T18:01:58.5465073Z 
2022-03-01T18:01:58.5465270Z [1m[91mRan 285 of 7042 Specs in 2177.427 seconds[0m
2022-03-01T18:01:58.5465802Z [1m[91mFAIL![0m -- [32m[1m284 Passed[0m | [91m[1m1 Failed[0m | [33m[1m3 Flaked[0m | [33m[1m0 Pending[0m | [36m[1m6757 Skipped[0m
2022-03-01T18:01:58.5546906Z 
```

**Comment by astoycos** [comment]
I don't really have time to reproduce these failures locally, and no problems are apparent to me from read the code, @Pardhakeswar Were you able to repro locally?

**Comment by Pardhakeswar** [comment]
@astoycos I wasn't able to reproduce these failures in our local Kind setup.

**Comment by astoycos** [comment]
Hrm well I don't think this is a flake.... Since all the conformance tests are failing on the same test, how did you reproduce? Were you able to run `2022-03-01T18:01:58.5463005Z �[91m�[1m[Fail] �[0m�[90m[sig-network] Services �[0m�[91m�[1m[It] should be able to change the type from ExternalName to NodePort [Conformance] �[0m
` 

Manually with the e2e test binary?

**Comment by Pardhakeswar** [comment]
@astoycos haven't tried manually the changing the service form externalName to nodeport one, will test it locally. Thanks

**Comment by astoycos** [comment]
@girishmg mentioned he may be able to help reproduce this?

**Pull request closed without merging**
