### PR TITLE
dist: bump OVN to ovn-20.09.0-1.fc31

### PR DESCRIPTION
**Pull request by dceara**

### CODE REVIEW

**Comment by girishmg** [comment]
@dceara we are seeing huge memory leak(?) with ovn-controller at scale with OVN 20.09 release. Winson from my team is going to send out an email to ovs-dev

**Comment by dceara** [comment]
> @dceara we are seeing huge memory consumption (possible memory leak(?)) with ovn-controller at scale with OVN 20.09 release. Winson from my team is going to send out an email to ovs-dev

Ack. I'll park this PR for now and wait until the memory consumption is clarified.

**Comment by numansiddique** [comment]
@girishmg When you send the email, is it possible to share the OVN NB DB ?

Can you please try running the below command and then see the memory consumption ?

ovs-vsctl set open . external_ids:ovn-enable-lflow-cache=false

I'm suspecting if the lflow caching is causing the memory consumption issue.

Thanks

**Comment by winsopc** [comment]
@numansiddique 
Thanks for the information. 
You are correct, after set the option as you suggested.
one node ovn-controller memory usage reduced from 1.17G to 376MB.

**Pull request merged**
