### PR TITLE
CI: Remove redundant booleans and use names for all of the features.

### LINKED ISSUE #2379: Fix CI job naming
In our CI the job names show as:

```
ovn-ci / e2e (shard-conformance, false, false, false, true, HA, false, snatGW, local, false, 1br, ip...
```

We should get rid of the redundant booleans and use names for all of the features.

### PR DESCRIPTION
**Pull request by andreaskaris**
Fixes #2379 

Signed-off-by: Andreas Karis <ak.karis@gmail.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by andreaskaris** [comment]
Checklist:

Before - 9 tests

e2e (shard-conformance, false, false, false, true, HA, false, snatGW, local, false, 1br, ipv6, IP..

==> shard-confirmance, HA, snatGW, local, 1br, IPv6

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: shard-conformance-HA-local-IPv6-snatGW-1br
    OVN_HA: true
    KIND_IPV4_SUPPORT: false
    KIND_IPV6_SUPPORT: true
    OVN_HYBRID_OVERLAY_ENABLE: false
    OVN_GATEWAY_MODE: local
    OVN_MULTICAST_ENABLE: false
    OVN_EMPTY_LB_EVENTS: false
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_SECOND_BRIDGE: false                                                                               https://github.com/ovn-org/ovn-kubernetes/runs/3233953194

e2e (shard-conformance, false, false, false, true, HA, false, snatGW, local, false, 1br, dualstac...

==> shard-conformance, HA, snatGW, local, 1br, dualstack

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: shard-conformance-HA-local-Dualstack-snatGW-1br
    OVN_HA: true
    KIND_IPV4_SUPPORT: true
    KIND_IPV6_SUPPORT: true
    OVN_HYBRID_OVERLAY_ENABLE: false
    OVN_GATEWAY_MODE: local
    OVN_MULTICAST_ENABLE: false
    OVN_EMPTY_LB_EVENTS: false
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_SECOND_BRIDGE: false


e2e (shard-conformance, false, false, false, true, HA, false, snatGW, shared, false, 1br, ipv4, I...
succeeded 40 minutes ago in 33m 18s

==> shard-conformance, HA, snatGW, shared, 1br, ipv4

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: shard-conformance-HA-shared-IPv4-snatGW-1br
    OVN_HA: true
    KIND_IPV4_SUPPORT: true
    KIND_IPV6_SUPPORT: false
    OVN_HYBRID_OVERLAY_ENABLE: false
    OVN_GATEWAY_MODE: shared
    OVN_MULTICAST_ENABLE: false
    OVN_EMPTY_LB_EVENTS: false
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_SECOND_BRIDGE: false

XXXXXXXXXXXXX

e2e (shard-conformance, false, false, false, true, HA, false, snatGW, shared, false, 1br, ipv6, I...

==> shard-conformance, HA, snatGW, shared, 1br, ipv6

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: shard-conformance-HA-shared-IPv6-snatGW-1br
    OVN_HA: true
    KIND_IPV4_SUPPORT: false
    KIND_IPV6_SUPPORT: true
    OVN_HYBRID_OVERLAY_ENABLE: false
    OVN_GATEWAY_MODE: shared
    OVN_MULTICAST_ENABLE: false
    OVN_EMPTY_LB_EVENTS: false
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_SECOND_BRIDGE: false

e2e (shard-conformance, false, false, false, false, noHA, false, snatGW, local, false, 1br, ipv4,...

==> shard-conformance, noHA, snatGW, local, 1br, ipv4

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: shard-conformance-noHA-local-IPv4-snatGW-1br
    OVN_HA: false
    KIND_IPV4_SUPPORT: true
    KIND_IPV6_SUPPORT: false
    OVN_HYBRID_OVERLAY_ENABLE: false
    OVN_GATEWAY_MODE: local
    OVN_MULTICAST_ENABLE: false
    OVN_EMPTY_LB_EVENTS: false
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_SECOND_BRIDGE: false

e2e (control-plane, true, true, true, true, HA, false, snatGW, local, false, 1br, ipv6, IPv6, fal...

==> control-plane, HA, snatGW, local, 1br, ipv6

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: control-plane-HA-local-IPv6-snatGW-1br
    OVN_HA: true
    KIND_IPV4_SUPPORT: false
    KIND_IPV6_SUPPORT: true
    OVN_HYBRID_OVERLAY_ENABLE: true
    OVN_GATEWAY_MODE: local
    OVN_MULTICAST_ENABLE: true
    OVN_EMPTY_LB_EVENTS: true
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_SECOND_BRIDGE: false

e2e (control-plane, true, true, true, true, HA, false, snatGW, shared, false, 1br, ipv4, IPv4, tr...

==> control-plane, HA, snatGW, shared, 1br, ipv4

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: control-plane-HA-shared-IPv4-snatGW-1br
    OVN_HA: true
    KIND_IPV4_SUPPORT: true
    KIND_IPV6_SUPPORT: false
    OVN_HYBRID_OVERLAY_ENABLE: true
    OVN_GATEWAY_MODE: shared
    OVN_MULTICAST_ENABLE: true
    OVN_EMPTY_LB_EVENTS: true
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_SECOND_BRIDGE: false

e2e (control-plane, true, true, true, true, HA, false, snatGW, shared, false, 1br, ipv6, IPv6, fa...

==> control-plane, HA, snatGW, shared, 1br, ipv6

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: control-plane-HA-shared-IPv6-snatGW-1br
    OVN_HA: true
    KIND_IPV4_SUPPORT: false
    KIND_IPV6_SUPPORT: true
    OVN_HYBRID_OVERLAY_ENABLE: true
    OVN_GATEWAY_MODE: shared
    OVN_MULTICAST_ENABLE: true
    OVN_EMPTY_LB_EVENTS: true
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_SECOND_BRIDGE: false

e2e (control-plane, true, true, true, false, noHA, false, snatGW, local, false, 1br, ipv4, IPv4, ...

==> control-plane, noHA, snatGW, local, 1br, ipv4

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: control-plane-noHA-local-IPv4-snatGW-1br
    OVN_HA: false
    KIND_IPV4_SUPPORT: true
    KIND_IPV6_SUPPORT: false
    OVN_HYBRID_OVERLAY_ENABLE: true
    OVN_GATEWAY_MODE: local
    OVN_MULTICAST_ENABLE: true
    OVN_EMPTY_LB_EVENTS: true
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_SECOND_BRIDGE: false

**Comment by andreaskaris** [comment]
The new list runs 2 tests less. That's because the initial list contained 2 invalid exclusions:
```
         # IPv6 multicast is supported but tests fail due to old iperf version
         # in agnhost images. Disable them for now.
         - {"ipfamily": {"ip": dualstack}, "target": {"shard": {"multicast-enable": "true"}}}
         - {"ipfamily": {"ip": ipv6}, "target": {"shard": {"multicast-enable": "true"}}}
```

These exclusions assumed that target-> shard-> multicast-enable was nested, but multicast-enable was right at the same level as shard:
```
- shard: control-plane
  hybrid-overlay: true
  multicast-enable: true
  emptylb-enable: true
```

The new rules fix this:
```
         - {"ipfamily": "dualstack", "target": "control-plane"}
         - {"ipfamily": "ipv6", "target": "control-plane"}
```

And thus exclude the scenarios:
e2e (control-plane, true, true, true, true, HA, false, snatGW, local, false, 1br, ipv6, IPv6, fal...
e2e (control-plane, true, true, true, true, HA, false, snatGW, shared, false, 1br, ipv6, IPv6, fa...

I am not sure which of the 2 options is correct: excluding the 2 jobs as stated by the comment's (and configuration's) intention or removing both line (or at least the ipv6 one) and running the 2 tests.

**Comment by andreaskaris** [comment]
New tests - as mentioned above, 2 are removed but can easily be added back in if this is actually desired.

e2e (shard-conformance, HA, snatGW, local, 1br, ipv6)

   GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: shard-conformance-HA-local-ipv6-snatGW-1br
    OVN_HYBRID_OVERLAY_ENABLE: false
    OVN_MULTICAST_ENABLE: false
    OVN_EMPTY_LB_EVENTS: false
    OVN_HA: true
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_GATEWAY_MODE: local
    OVN_SECOND_BRIDGE: false
    KIND_IPV4_SUPPORT: false
    KIND_IPV6_SUPPORT: true

e2e (shard-conformance, HA, snatGW, local, 1br, dualstack)

   GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: shard-conformance-HA-local-dualstack-snatGW-1br
    OVN_HYBRID_OVERLAY_ENABLE: false
    OVN_MULTICAST_ENABLE: false
    OVN_EMPTY_LB_EVENTS: false
    OVN_HA: true
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_GATEWAY_MODE: local
    OVN_SECOND_BRIDGE: false
    KIND_IPV4_SUPPORT: true
    KIND_IPV6_SUPPORT: true

e2e (shard-conformance, HA, snatGW, shared, 1br, ipv4)

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: shard-conformance-HA-shared-ipv4-snatGW-1br
    OVN_HYBRID_OVERLAY_ENABLE: false
    OVN_MULTICAST_ENABLE: false
    OVN_EMPTY_LB_EVENTS: false
    OVN_HA: true
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_GATEWAY_MODE: shared
    OVN_SECOND_BRIDGE: false
    KIND_IPV4_SUPPORT: true
    KIND_IPV6_SUPPORT: false

e2e (shard-conformance, HA, snatGW, shared, 1br, ipv6)

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: shard-conformance-HA-shared-ipv6-snatGW-1br
    OVN_HYBRID_OVERLAY_ENABLE: false
    OVN_MULTICAST_ENABLE: false
    OVN_EMPTY_LB_EVENTS: false
    OVN_HA: true
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_GATEWAY_MODE: shared
    OVN_SECOND_BRIDGE: false
    KIND_IPV4_SUPPORT: false
    KIND_IPV6_SUPPORT: true

e2e (shard-conformance, noHA, snatGW, local, 1br, ipv4)

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: shard-conformance-noHA-local-ipv4-snatGW-1br
    OVN_HYBRID_OVERLAY_ENABLE: false
    OVN_MULTICAST_ENABLE: false
    OVN_EMPTY_LB_EVENTS: false
    OVN_HA: false
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_GATEWAY_MODE: local
    OVN_SECOND_BRIDGE: false
    KIND_IPV4_SUPPORT: true
    KIND_IPV6_SUPPORT: false

e2e (control-plane, HA, snatGW, shared, 1br, ipv4)

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: control-plane-HA-shared-ipv4-snatGW-1br
    OVN_HYBRID_OVERLAY_ENABLE: true
    OVN_MULTICAST_ENABLE: true
    OVN_EMPTY_LB_EVENTS: true
    OVN_HA: true
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_GATEWAY_MODE: shared
    OVN_SECOND_BRIDGE: false
    KIND_IPV4_SUPPORT: true
    KIND_IPV6_SUPPORT: false

e2e (control-plane, noHA, snatGW, local, 1br, ipv4)

    GO_VERSION: 1.16.3
    K8S_VERSION: v1.20.2
    KIND_CLUSTER_NAME: ovn
    KIND_INSTALL_INGRESS: true
    KIND_ALLOW_SYSTEM_WRITES: true
    PARALLEL: true
    JOB_NAME: control-plane-noHA-local-ipv4-snatGW-1br
    OVN_HYBRID_OVERLAY_ENABLE: true
    OVN_MULTICAST_ENABLE: true
    OVN_EMPTY_LB_EVENTS: true
    OVN_HA: false
    OVN_DISABLE_SNAT_MULTIPLE_GWS: false
    OVN_GATEWAY_MODE: local
    OVN_SECOND_BRIDGE: false
    KIND_IPV4_SUPPORT: true
    KIND_IPV6_SUPPORT: false

**Comment by squeed** [comment]
wow, great fix.
/lgtm
@dcbw want to merge this/

**Pull request merged**
