### PR TITLE
Update to latest version of go-ovn to get support for port groups and ACLs on port groups

### PR DESCRIPTION
**Pull request by anfredette**
**-What this PR does and why is it needed:**

This is the first step in an effort to use go-ovn APIs for port groups and ACLs.  In order to do this, go-ovn needed to be extended to support port groups and ACLs on port groups.  This PR pulls in the latest go-ovn code with needed support.

**- Special notes for reviewers**

This PR contains an update to the latest version of go-ovn to pick up support for port groups and ACLs on port groups
- updated to github.com/ebay/go-ovn v0.1.1-0.20210203103701-8bb6a085d599
- Added the new APIs to mock_stubs.go so go test will work.

None of the new APIs are used yet.

The following steps were used to update go-ovn:
- go get github.com/ebay/go-ovn@8bb6a085d5998a6071f81f85eac258dbeafbcf65
- Deleted the following replace directive:
  - github.com/ebay/go-ovn v0.1.0 => github.com/ebay/go-ovn v0.1.1-0.20200810162212-30abed5fb968
- go mod tidy
- go mod vendor

**- How to verify it**

- All of the new (and old) go-ovn APIs have unit tests in the go-ovn project.
- Run "go test" in the ovn-kubernetes/go-controller/pkg/ovn directory
- Run e2e Policy tests.

**- Description for the changelog**

Update to the latest version of go-ovn

### CODE REVIEW

**Comment by anfredette** [comment]
I squashed the two commits because the first one won't build without the second one.

**Comment by JacobTanenbaum** [comment]
the linter is unsuccessful 

/util/net_unit_test.go:127:56: cannot use mockOvnNBClient (variable of type *\"github.com/ovn-org/ovn-kubernetes/go-controller/pkg/testing/mocks/github.com/ebay/go-ovn\".Client) as goovn.Client value in argument to GetPortAddresses: missing method ACLAddEntity]"

**Comment by anfredette** [comment]
I backed out changes pulled in by go get -u github.com/ebay/go-ovn.  It pulled in a new version of github.com/cenkalti/rpc2 that was incompatible with libovsdb.  This should be ready for review now.

**Comment by anfredette** [comment]
Rebased on upstream/master latest per Tim's request on ovn-kubernetes call today.

**Comment by anfredette** [comment]
Rebased to fix merge conflict.

**Pull request merged**
