### PR TITLE
Upgrade sriovnet

### PR DESCRIPTION
**Pull request by bn222**
GetPfIndexByVfPciAddress is now part of sriovnet, so upgrade it. Also rename the url since the project moved to https://github.com/k8snetworkplumbingwg/sriovnet

### CODE REVIEW

**Comment by bn222** [comment]
@DmytroLinkin

**Review by DmytroLinkin — APPROVED** [review]
LGTM

**Comment by bn222** [comment]
@DmytroLinkin I needed to fix the mock for sriovnet. PTAL

**Review by DmytroLinkin — APPROVED** [review]
LGTM

**Pull request merged**
