### PR TITLE
Bump OVN to latest from advisory

### PR DESCRIPTION
**Pull request by trozet**
Move to ovn-20.12.0-24

Signed-off-by: Tim Rozet <trozet@redhat.com>

### CODE REVIEW

**Comment by trozet** [comment]
```
 Package          Arch        Version                Repository            Size
================================================================================
Upgrading:
 ovn              x86_64      20.12.0-24.fc33        updates-testing      1.0 M
 ovn-central      x86_64      20.12.0-24.fc33        updates-testing      430 k
 ovn-host         x86_64      20.12.0-24.fc33        updates-testing      680 k
```

**Comment by trozet** [comment]
@aojea FYI

**Comment by trozet** [comment]
@dceara

**Comment by aojea** [comment]
it seems the same tests that failed with the previous upgrade keep failing , related to services

**Comment by trozet** [comment]
my bad was missing -y on dnf install so install was aborting and using old version

**Pull request merged**
