### PR TITLE
util: Fix incorrect mock import

### PR DESCRIPTION
**Pull request by dave-tucker**
**- What this PR does and why is it needed**

Fixes incorrect import of mock packages that has broken the build

**- Special notes for reviewers**

None

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by dave-tucker** [comment]
@trozet @dcbw master build is broken due to a conflict between #1675 #1737
I'm going to guess that the one the moved the mocks merged first, and github didn't see the merge conflict that would have been created.

**Comment by dave-tucker** [comment]
Well this is painful. This PR changes nothing of note and yet....

First run: Fails a unit test because the watch factory gets events out of order. I think I've seen this flake before.

Second run: Gets a segfault in the egressIP tests 😱 
```
I1020 10:24:13.728701   19036 reflector.go:181] Stopping reflector *v1.EgressIP (0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x150814d]

goroutine 4387 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).addEgressNode(0xc00000c1e0, 0xc0008adb00, 0x1952527, 0x1d)
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/egressip.go:654 +0xed
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).WatchEgressNodes.func2(0x1916f80, 0xc0008acc00, 0x1916f80, 0xc0008adb00)
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/ovn.go:792 +0x1ee
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/controller.go:225
k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnUpdate(0xc0003781c0, 0x1b84640, 0xc00045c600, 0x1916f80, 0xc0008acc00, 0x1916f80, 0xc0008adb00)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/controller.go:259 +0x122
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*Handler).OnUpdate(...)
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/factory/factory.go:61
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).newFederatedQueuedHandler.func2.1.1(0xc000552300)
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/factory/factory.go:238 +0x78
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).forEachQueuedHandler(0xc00081c400, 0xc000511ef8)
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/factory/factory.go:107 +0x1d6
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).newFederatedQueuedHandler.func2.1(0xc000552630)
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/factory/factory.go:237 +0x52
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).processEvents(0xc00081c400, 0xc000737ec0, 0xc000738960)
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/factory/factory.go:174 +0x78
created by github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.newQueuedInformer
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/factory/factory.go:365 +0x11e
FAIL	github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn	14.080s
FAIL
```

**Comment by aojea** [comment]
/lgtm
great catch
we should have a postsubmit or something, I think that right now it merges directly without rerunning the tests

**Review by trozet — APPROVED** [review]

**Pull request merged**
