### PR TITLE
Removing check on hostname and proper update of IP address

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
This is a PR targetted at:

* being able to target cluster nodes using their DNS name. 
* improving the check on valid IP addresses for endpoint updates. 

@dcbw @squeed @girishmg

### CODE REVIEW

**Comment by squeed** [comment]
Some backstory: while updating our cluster to use raft, we discovered some oddness in how ovnkube node handles domain names.

**Comment by girishmg** [comment]
@dcbw @alexanderConstantinescu IMHO, this PR should just fix the parsing of hostname part and then take the rest of the changes to PR #888

**Comment by alexanderConstantinescu** [comment]
Hi @girishmg 

I modified both PRs and added the "IP address update" to this PR while removing it from #888. The reasoning being: keeping "nice-to-have's" (#888) separated from "required features" (this PR). Hope that's fine, otherwise I can re-incorporate the "IP address update" back to #888, but I don't think that adds anything.

**Comment by girishmg** [comment]
@alexanderConstantinescu can you please rebase?

**Comment by alexanderConstantinescu** [comment]
> @alexanderConstantinescu can you please rebase?

Done, PTAL.

**Pull request merged**
