### PR TITLE
Add e2e tests for egressIP health check

### PR DESCRIPTION
**Pull request by jcaamano**
Legacy health check test is skipped for now as it takes ~10mins to do two sequenced rollouts of both ovnkube-node and ovnkube-master which is high price to pay for a non-default unlikely used option.

@flavio-fernandes @kyrtapz WDYT?

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
nice! TY @jcaamano I will try / look at it soon.

**Comment by flavio-fernandes** [comment]
Ran tests locally and verified that it touches egressip grpc operations as expected.
TY @jcaamano 
/lgtm

**Comment by jcaamano** [comment]
oops had to unfocus the tests

**Review by flavio-fernandes — APPROVED** [review]
/lgtm

**Pull request merged**
