### PR TITLE
bump version of go used for building images is CI testing

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
specifically calls to the syncMaps LoadAndDelete() causes failure

seen in this PR: https://github.com/ovn-org/ovn-kubernetes/pull/1916
```
 # github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn
Error: pkg/ovn/policy.go:848:26: np.localPods.LoadAndDelete undefined (type sync.Map has no field or method LoadAndDelete)
Error: make[1]: *** [Makefile:34: all] Error 2
make[1]: Leaving directory '/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller'
Error: make: *** [Makefile:87: ../../go-controller/_output/go/bin/ovnkube] Error 2
make: Leaving directory '/home/runner/work/ovn-kubernetes/ovn-kubernetes/dist/images'
Error: Process completed with exit code 2.
```

Signed-off-by: Jacob Tanenbaum <jtanenba@redhat.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by squeed** [comment]
:+1:

**Comment by JacobTanenbaum** [comment]
@trozet @dcbw PTAL it is a very small PR

**Review by trozet — APPROVED** [review]
/lgtm

**Pull request merged**
