### PR TITLE
Make GR SNAT using host CT zone in shared GW mode

### PR DESCRIPTION
**Pull request by trozet**
Shared GW mode uses the same IP between the host and the GR. Traffic
leaving the cluster to the same destination IP and Port, with the same
source Port may conflict unless OVN uses the same CT zone as the host to
avoid potential conflicts. For more information see:
https://bugzilla.redhat.com/show_bug.cgi?id=1892311

Signed-off-by: Tim Rozet <trozet@redhat.com>

### CODE REVIEW

**Comment by trozet** [comment]
@putnopvut @numansiddique

**Comment by dcbw** [comment]
@trozet will this fail on OVNs that dont' have the feature, or does the option just get ignored? eg are we about to require an unreleased OVN to use shared gateway mode...

**Comment by trozet** [comment]
> @trozet will this fail on OVNs that dont' have the feature, or does the option just get ignored? eg are we about to require an unreleased OVN to use shared gateway mode...

it will just get ignored. We dont have the F32 build yet, @numansiddique is working on it. But we can safely get this in in the meantime and verify it once downstream builds are going.

**Comment by numansiddique** [comment]
Fedora 32 and 33 updates: - 

https://bodhi.fedoraproject.org/updates/FEDORA-2020-0b2305bf8c
https://bodhi.fedoraproject.org/updates/FEDORA-2020-27afba40b6

**Pull request merged**
