### PR TITLE
Add enable-multi-networkpolicy CLI flag

### PR DESCRIPTION
**Pull request by jcaamano**
So that it can be enabled independently of multi-network support.

### CODE REVIEW

**Comment by jcaamano** [comment]
/cc @cathy-zhou @trozet @maiqueb 

We had to add this because our downstream operator exposes the specific flag as well :/

**Review by maiqueb — CHANGES_REQUESTED** [review]
I think the code is solid, but I wonder if  we should add a unit test for this, similar to [this one](https://github.com/ovn-org/ovn-kubernetes/commit/fcb87247fa78be6372d5ff063ab1cd3abb4adc8a).

**Comment by maiqueb** [comment]
is the following unit test error a flake ? 
```
[Fail] Informer Event Handler Tests [It] adds existing pod and processes an update event 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/informer/informer_test.go:278
```

**Comment by maiqueb** [comment]
I assume this means I'll need to enable this flag on the e2e framework [PR](https://github.com/ovn-org/ovn-kubernetes/pull/3531) @jcaamano .

**Comment by cathy-zhou** [comment]
we should not need to watchNamespaces() for secondary networks if multi-network-policy is disabled. Also, for secondary network, initRetryFramework() does not need to initialize retryNamespaces and retryNetworkPolicies. But I guess if we do so, it is harmless.

**Comment by cathy-zhou** [comment]
one more nits, https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/ovn/base_network_controller_secondary.go#L249 also needs to check if multi-network-policy is enabled. Otherwise, it lgtm.

**Comment by cathy-zhou** [comment]
@jcaamano while reviewing https://github.com/ovn-org/ovn-kubernetes/pull/3575, I just realized you'd need to change daemonset.sh, ovnkube.sh and ovnkube-master.yaml.j2 to provide the way to enabling this new flag.

**Comment by jcaamano** [comment]
> @jcaamano while reviewing #3575, I just realized you'd need to change daemonset.sh, ovnkube.sh and ovnkube-master.yaml.j2 to provide the way to enabling this new flag.

Done. I guess it is good enough to enable it whenever multinet is enabled for now.

**Review by trozet — APPROVED** [review]

**Pull request merged**
