### PR TITLE
Remove hardcoded kernel version

### PR DESCRIPTION
**Pull request by vishnoianil**
Signed-off-by: Anil Vishnoi <vishnoianil@gmail.com>

### CODE REVIEW

**Comment by vishnoianil** [comment]
@dcbw @girishmg Minor fix. PTAL, thanks.

**Comment by danwinship** [comment]
This doesn't really seem any better... it's going to get out of date almost immediately. The script needs to figure out the right version itself by calling `rpm` or `uname` or something.

**Comment by vishnoianil** [comment]
> This doesn't really seem any better... it's going to get out of date almost immediately. The script needs to figure out the right version itself by calling `rpm` or `uname` or something.

@danwinship This PR is just to remove the hardcoded version. 

Yes, that's the right way, and i tried it as well. Fedora base images comes with kernel version 3.10.X and when you upgrade it while building the docker image, uname -r always gives you the 3.10.x version rather then upgraded kernel version. So I need to spend some time to see how to fix that.

**Comment by dcbw** [comment]
@vishnoianil shouldn't we just be installing whatever the latest kernel-devel package is, regardless of what kernel is actually running on the host? Unless you force-install a specific kernel-devel package you'll always have just one: the latest.

And if you want to be really safe you then:

`KERNEL_VERSION=`ls /usr/src/kernels/ | xargs | cut -f1 -d' '``

and you're done.

**Comment by vishnoianil** [comment]
> @vishnoianil shouldn't we just be installing whatever the latest kernel-devel package is, regardless of what kernel is actually running on the host?
Yes, that's what i have tried. But how do you find out the latest kernel-devel package from dnf/rpm?

> Unless you force-install a specific kernel-devel package you'll always have just one: the latest.

I think kernel-devel packages are not installed by default, so the below command will fail.
> 
> And if you want to be really safe you then:
> 
> `KERNEL_VERSION=`ls /usr/src/kernels/ | xargs | cut -f1 -d' '``
> 
> and you're done.

Given that docker relies on the host machine's kernel, as far as your host machine where you are building the docker image has latest kernel (> 4.8.x), things will work file with `kernel-devel-uname-r == uname -r`, as it will pickup and install the devel packages for that kernel version. So all good. 

Host machine that is running the old kernel version (like centos is currently run 3.10, and i believe RHEL/Fedora as well), above command will try to install the 3.10 version kernel-devel package, which is expected. But if you want to installed the latest version of kernel-devel packages, you have 2 options 
(1) Upgrade your host machine's kernel version to the latest version (probably not a favourable options), and the above command will work fine and install the latest kernel-devel package.
(2) Explictly install the latest kernel-devel package using dnf, like it's currently implemented (we can probably do some more scripting work to find out the latest version and set KERNEL_VERSION to that, but i didn't come across any sane way to do that.).

Overall, i am thinking if we can just set the KERNEL_VERSION=`uname -r` as @danwinship suggested, that will work fine for latest kernels, and for scenario (2) user can change it to the hardcoded version locally in it's environment to build the images?
@dcbw @danwinship If that makese sense, let me know, will change and push the patch.

**Comment by vishnoianil** [comment]
@dcbw @danwinship I pushed new changes, let me know if that looks like a better approach?

**Pull request merged**
