### PR TITLE
Succesor for PR 2331 [fix reserve joinSwitch LRP IPs]

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
**- What this PR does and why is it needed**

I have no clue what is happening with Github and its actions on PR: https://github.com/ovn-org/ovn-kubernetes/pull/2331 , it's cancelling the build during every run. Hence try to get a CI signal on it here. 

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by Reamer** [comment]
Thank you for pushing for these changes.

**Comment by alexanderConstantinescu** [comment]
This PR is a successor to #2331 , since that PR is bonkers...

This PR passes CI and has the exact same commits as #2331 (which has an lgtm)

**Comment by alexanderConstantinescu** [comment]
Merging this, following agreement: https://github.com/ovn-org/ovn-kubernetes/pull/2331#issuecomment-903825507

**Pull request merged**
