### PR TITLE
logging: allow changing log-level at runtime via the pprof /debug endpoint

### PR DESCRIPTION
**Pull request by dcbw**
Bundled with the pprof endpoint since enabling pprof (a) enables /debug and (b) indicates that you're OK with things that can reach ovnkube changing runtime settings (pprof and logging).

To change logging do something like:

`curl -X PUT --data="5" http://localhost:<metrics port>/debug/flags/v`

### CODE REVIEW

**Comment by girishmg** [comment]
@dcbw i think we discussed this in the past (maybe 2 years ago).
1. this will only work if we have enabled Golang profiling
2. there is no Authentication so anyone can change the logging level and we can't audit this change..

Can we use k8s node annotation to influence the log level?

k8s.ovn.org/ovnkube-master-loglevel=<int>
k8s.ovn.org/ovnkube-node-loglevel=<int>

**Comment by dcbw** [comment]
Action item for me: figure out if OpenShift enables this option for Kubelet by default (this PR is basically lifted from how Kubelet does things)

We should also ensure that a logging option gets into the node Custom Resource we're discussing to replace all the annotations we use.

**Comment by dcbw** [comment]
@girishmg investigated more...

OpenShift *does* enable kubelet debugging endpoints by default but it binds the HTTP server to 127.0.0.1. So regular pods can't talk to the endpoint (because they can't get to host's 127.0.0.1) and any hostNetwork pods are already privileged.

**Comment by girishmg** [comment]
@dcbw sounds good.  We do the same.

**Comment by dcbw** [comment]
@girishmg does that mean we could merge this PR?

**Comment by girishmg** [comment]
@dcbw yes this is good to go

**Pull request merged**
