### PR TITLE
Set MTU for br-ext hybrid overlay bridge

### PR DESCRIPTION
**Pull request by trozet**
Signed-off-by: Tim Rozet <trozet@redhat.com>

### CODE REVIEW

**Comment by dcbw** [comment]
@trozet needs a corresponding testcase update

**Comment by rcarrillocruz** [comment]
Other than maybe testcase , lgtm

**Comment by trozet** [comment]
not sure if this is a new flake. Doesn't happen on my laptop:

• Failure [2.004 seconds]
Hybrid SDN Master Operations
/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/hybrid-overlay/pkg/controller/master_test.go:69
  cleans up a Linux node when the OVN hostsubnet annotation is removed [It]
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/hybrid-overlay/pkg/controller/master_test.go:226

  Timed out after 2.000s.
  Expected
      <map[string]string | len:1>: {
          "k8s.ovn.org/hybrid-overlay-distributed-router-gateway-mac": "00:00:00:52:19:d2",
      }
  not to have key
      <string>: k8s.ovn.org/hybrid-overlay-distributed-router-gateway-mac

**Pull request merged**
