### PR TITLE
Node delete should not fail when it can never succeed when `node-subnet` annot isnt assigned

### PR DESCRIPTION
**Pull request by martinkennelly**
Node delete is failing and retrying until retry limit when it can never succeed when particular annotations arent added in time before the node is deleted.

~/hold~

~Need to add unit test.~

All thanks to @trozet  for his KinD scaler PR to reproduce #4331 !

### CODE REVIEW

**Comment by martinkennelly** [comment]
`Update to OVN master` job failed near the beginning of the test run because of `8Z ##[error]The operation was canceled.` - This is usually provider issue.

Other issue is a admin net pol test failed - unrelated to this PR:
` helper.go:123: StatefulSet replicas in namespace network-policy-conformance-gryffindor not rolled out yet. 0/2 replicas are available.`

**Comment by martinkennelly** [comment]
cc @ricky-rav

**Comment by martinkennelly** [comment]
/hold 

until i understand why job `Upgrade OVN from Master to PR ..` is exceeding its time limit.

**Review by jcaamano — APPROVED** [review]

**Comment by ricky-rav** [comment]
/lgtm

Thanks, Martin!

**Comment by jcaamano** [comment]
I considered if the information could have been retrieved from OVN DB instead (in case it was unexpectedly removed from the node), and although I am sure there is a way, is not apparently straight forward (for the host subnets).

**Pull request merged**
