### PR TITLE
excludeSubnets in layer2 topology type NAD is optional

### PR DESCRIPTION
**Pull request by cathy-zhou**
Signed-off-by: Yun Zhou <yunz@nvidia.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by maiqueb — APPROVED** [review]
Thanks.

**Review by maiqueb — CHANGES_REQUESTED** [review]
While I think the code is what we want/need, I think we should add some unit tests for this.

**Comment by cathy-zhou** [comment]
> While I think the code is what we want/need, I think we should add some unit tests for this.
for parseSubnetsString()? ok.

**Comment by maiqueb** [comment]
> > While I think the code is what we want/need, I think we should add some unit tests for this.
> 
> for parseSubnetsString()? but this is not an exported function, shall we make it exported and move to net.go?

Not sure the best course of action, given the lack of overall unit tests. 

@trozet can you suggest a course of action ?

**Comment by cathy-zhou** [comment]
@maiqueb I've added unit tests, please take a look.

**Review by maiqueb — APPROVED** [review]
Thank you :)

**Review by trozet — APPROVED** [review]

**Pull request merged**
