### PR TITLE
Small fixes for external GW

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
**- What this PR does and why is it needed**

Fixes some small issues seen with the external GW code while investigating; https://github.com/ovn-org/ovn-kubernetes/issues/1794

/assign @trozet 

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
Pasting this here for future reference:

```
go test -test.v -race  github.com/ovn-org/ovn-kubernetes/go-controller/pkg/informer -ginkgo.v -ginkgo.reportFile /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/_artifacts/junit-pkg_informer.xml
=== RUN   TestEventHandler
Running Suite: Event Handler Suite
==================================
Random Seed: 1605027972
Will run 9 of 9 specs

Informer Event Handler Tests 
  processes an add event
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/informer/informer_test.go:74
I1110 17:06:12.793547   11902 informer.go:178] Starting test informer queue
I1110 17:06:12.793670   11902 informer.go:180] Waiting for test informer caches to sync
I1110 17:06:12.894755   11902 informer.go:186] Starting 1 test queue workers
I1110 17:06:12.894909   11902 informer.go:197] Started test queue workers
I1110 17:06:13.294947   11902 informer.go:294] Successfully synced 'test/foo'
I1110 17:06:13.395108   11902 informer.go:201] Shutting down test queue workers
I1110 17:06:13.395209   11902 informer.go:204] Shut down test queue workers
•
------------------------------
Informer Event Handler Tests 
  do not processes an add event if the pod is set for deletion
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/informer/informer_test.go:136
I1110 17:06:13.395936   11902 informer.go:178] Starting test informer queue
I1110 17:06:13.395974   11902 informer.go:180] Waiting for test informer caches to sync
I1110 17:06:13.497229   11902 informer.go:186] Starting 1 test queue workers
I1110 17:06:13.497544   11902 informer.go:197] Started test queue workers
I1110 17:06:13.996782   11902 informer.go:201] Shutting down test queue workers
I1110 17:06:13.997725   11902 informer.go:204] Shut down test queue workers
•
------------------------------
Informer Event Handler Tests 
  adds existing pod and processes an update event
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/informer/informer_test.go:201
I1110 17:06:13.999702   11902 informer.go:178] Starting test informer queue
I1110 17:06:13.999761   11902 informer.go:180] Waiting for test informer caches to sync
I1110 17:06:14.000107   11902 informer.go:186] Starting 1 test queue workers
I1110 17:06:14.000324   11902 informer.go:197] Started test queue workers
I1110 17:06:14.000473   11902 informer.go:294] Successfully synced 'test/foo'
I1110 17:06:15.104441   11902 informer.go:201] Shutting down test queue workers
I1110 17:06:15.104702   11902 informer.go:204] Shut down test queue workers

• Failure [1.107 seconds]
Informer Event Handler Tests
/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/informer/informer_test.go:55
  adds existing pod and processes an update event [It]
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/informer/informer_test.go:201

  Timed out after 1.000s.
  adds
  Expected
      <int32>: 1
  to equal
      <int32>: 2

  /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/informer/informer_test.go:276
------------------------------
```

@dave-tucker : I think you've been working on this frequently, have you seen this before?

**Comment by dave-tucker** [comment]
I've not seen that before @alexanderConstantinescu, but I'll look in to it tomorrow

**Comment by alexanderConstantinescu** [comment]
This second failure is much more disconcerting:

```
OVN Egress Gateway Operations on setting pod gateway annotations 
  reconciles a host networked pod acting as a exgw for another namespace for existing pod
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/egressgw_test.go:323
I1110 17:39:55.209316   12720 reflector.go:175] Starting reflector *v1beta1.CustomResourceDefinition (0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.209361   12720 reflector.go:211] Listing and watching *v1beta1.CustomResourceDefinition from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.309753   12720 shared_informer.go:253] caches populated
I1110 17:39:55.310604   12720 reflector.go:175] Starting reflector *v1.Pod (0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.310748   12720 reflector.go:211] Listing and watching *v1.Pod from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.310964   12720 reflector.go:175] Starting reflector *v1.NetworkPolicy (0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.311022   12720 reflector.go:211] Listing and watching *v1.NetworkPolicy from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.312353   12720 reflector.go:175] Starting reflector *v1.Namespace (0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.312813   12720 reflector.go:211] Listing and watching *v1.Namespace from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.313386   12720 reflector.go:175] Starting reflector *v1.Service (0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.313576   12720 reflector.go:211] Listing and watching *v1.Service from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.313965   12720 reflector.go:175] Starting reflector *v1.Node (0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.314106   12720 reflector.go:211] Listing and watching *v1.Node from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.312376   12720 reflector.go:175] Starting reflector *v1.Endpoints (0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.314586   12720 reflector.go:211] Listing and watching *v1.Endpoints from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.412096   12720 shared_informer.go:253] caches populated
I1110 17:39:55.412183   12720 shared_informer.go:253] caches populated
I1110 17:39:55.412211   12720 shared_informer.go:253] caches populated
I1110 17:39:55.412239   12720 shared_informer.go:253] caches populated
I1110 17:39:55.412260   12720 shared_informer.go:253] caches populated
I1110 17:39:55.412286   12720 shared_informer.go:253] caches populated
I1110 17:39:55.412756   12720 reflector.go:175] Starting reflector *v1.EgressIP (0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.412932   12720 reflector.go:211] Listing and watching *v1.EgressIP from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.512818   12720 shared_informer.go:253] caches populated
I1110 17:39:55.514283   12720 reflector.go:175] Starting reflector *v1.EgressFirewall (0s) from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.514363   12720 reflector.go:211] Listing and watching *v1.EgressFirewall from pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125
I1110 17:39:55.614039   12720 shared_informer.go:253] caches populated
I1110 17:39:55.614270   12720 ovn.go:841] Bootstrapping existing namespaces and cleaning stale namespaces took 96.1µs
I1110 17:39:55.615363   12720 kube.go:63] Setting annotations map[k8s.ovn.org/pod-networks:{"default":{"ip_addresses":["10.128.1.3/24"],"mac_address":"0a:58:0a:80:01:03","gateway_ips":["10.128.1.1"],"ip_address":"10.128.1.3/24","gateway_ip":"10.128.1.1"}}] on pod namespace1/myPod
I1110 17:39:55.616988   12720 pods.go:272] [namespace1/myPod] addLogicalPort took 1.796099ms
I1110 17:39:55.617162   12720 ovn.go:554] Bootstrapping existing pods and cleaning stale pods took 2.784298ms
I1110 17:39:55.617388   12720 egressgw.go:28] External gateway pod: gwPod, detected for namespace(s) namespace1
F1110 17:39:55.617592   12720 exec.go:168] Unexpected command: /fake-bin/ovn-nbctl --timeout=15 -- --may-exist --policy=src-ip --ecmp-symmetric-reply lr-route-add GR_node1 10.128.1.3/32 9.0.0.1

Executed commands do not match expected commands!
[00]   /fake-bin/ovn-nbctl --timeout=15 --data=bare --no-heading --columns=name find logical_switch_port external_ids:pod=true
FAIL	github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn	7.842s
FAIL
```

I've had a look at the test and the only way that can fail is if `syncPods` is executed twice...

The message 

```
 Bootstrapping existing pods and cleaning stale pods took 2.784298ms
```

means that `syncPods` already got executed once, and that find command is only executed in `syncPods` in the entire code base. I have no clue how this could have happened, but it smells bad

**Comment by JacobTanenbaum** [comment]
looks like you need to rebase for the new image build and I have https://github.com/ovn-org/ovn-kubernetes/pull/1858 in flight to remove the hybrid overlay external GW code @alexanderConstantinescu

**Pull request merged**
