### PR TITLE
[DNM] Disable parallelism for dual-conversion jobs

### PR DESCRIPTION
**Pull request by jcaamano**
Signed-off-by: Jaime Caamaño Ruiz <jcaamano@redhat.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by trozet** [comment]
So I suspected this might be an issue as well. The reason is because in the logs I saw delays scheduling the host networked pod endpoints for several minutes because the TCP/UDP ports were already in use (all the tests use the same ports). However, I don't think the actual test case failure is related to parallel jobs. Or at least I haven't seen any evidence pointing to that. I was going to hack a PR to build my own k8s e2e with infinite for loops on failure, then add the github action so we can login to the cluster while it is happening.

What made you think the parallelism is an issue @jcaamano ?

**Comment by jcaamano** [comment]
> So I suspected this might be an issue as well. The reason is because in the logs I saw delays scheduling the host networked pod endpoints for several minutes because the TCP/UDP ports were already in use (all the tests use the same ports).

I actually saw a test failing because of it so I'm just trying to get that out of the way and see if it actually has any other effect. Another idea I had was to stream the logs in order to see what's going on concurrently. 

> However, I don't think the actual test case failure is related to parallel jobs. Or at least I haven't seen any evidence pointing to that.

Agreed, so far, just hoping for the small chance of homing in to a more specific problem on a specific test though.

>  ... then add the github action so we can login to the cluster while it is happening.

What sorcery is that?

**Comment by jcaamano** [comment]
> What sorcery is that?

I see that we can setup a reverse tunnel with ngrok.

**Pull request closed without merging**
