### PR TITLE
OVN Kubernetes v1.0.0 Release

### PR DESCRIPTION
**Pull request by tssurya**
**- What this PR does and why is it needed**

Updates the version to 1.0.0. This PR will mark the tip of head for our major release.
So basically once we merge this I will cut the v1.0.0 release. This will also be followed by a
branch cut where we will do a `release-1.0` branch cut
Tentative date for release is May 17th 2024

cc @trozet / cc @girishmg / cc @jcaamano 

**- Special notes for reviewers**
We still have some more items to finish: https://github.com/ovn-org/ovn-kubernetes/milestone/1
Will have to review and remove some items that won't make the cut.

**- How to verify it**
```
ovnkube --version
Version: 1.0.0
Git commit: 24b9982706e37bafc66085045295d072f3fc7723
Git branch: release-v1.0.0
Go version: go1.21.4
Build date: 2024-05-02
OS/Arch: linux amd64
```

**- Description for the changelog**
`Cut v1.0.0 release`

### CODE REVIEW

**Comment by tssurya** [comment]
REMINDER FOR SELF: ENSURE THIS PR IS REBASED ON LATEST MASTER AT THE TIME AND THAT WE DON'T MERGE MULTIPLE THINGS NEARBY THIS

**Comment by tssurya** [comment]
unrelated flake:

```
Summarizing 1 Failure:
  [FAIL] External Gateway With Admin Policy Based External Route CRs e2e multiple external gateway validation Should validate ICMP connectivity to multiple external gateways for an ECMP scenario [It] IPV4
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/external_gateways.go:1636

Ran 44 of 278 Specs in 3018.570 seconds
FAIL! -- 43 Passed | 1 Failed | 2 Pending | 232 Skipped
```
https://github.com/ovn-org/ovn-kubernetes/actions/runs/9416828557/job/25941858275?pr=4333

**Review by flavio-fernandes — APPROVED** [review]
/lgtm

**Comment by tssurya** [comment]
unrelated failures happening in v6 lane:
https://github.com/ovn-org/ovn-kubernetes/actions/runs/9518141867/job/26239613328?pr=4333
https://github.com/ovn-org/ovn-kubernetes/actions/runs/9518141867/job/26239615805?pr=4333

**Comment by tssurya** [comment]
latest set was simply a rebase after flavio lgtm-ed it no new changes.

**Pull request merged**
