### PR TITLE
    Upgrade ovs version in Dockerfile.ubuntu to 2.11

### PR DESCRIPTION
**Pull request by TrevorTaoARM**
Due to the problems met in issue:
https://github.com/ovn-org/ovn-kubernetes/issues/855
We should use ovs 2.11 instead of 2.10 to fix the problem of using ovn-nbctl in daemon mode(default).

So the ovs version used in the Dockerfile should be promoted
to 2.11 to build a suitable image for daemonset install.
The related changes in Dockerfile.ubuntu are also verified on
aarch64(arm64) platform in addition to amd64(x86_64).

### CODE REVIEW

**Comment by girishmg** [comment]
@TrevorTaoARM I don't think we need changes to Dockerfile.ubuntu. If you build an image off of that dockerfile, then you should already be at OVS 2.11.X.

**Comment by shettyg** [comment]
If Ubuntu 19.04 provides 2.11.x, it may make sense to move to upstream OVS.

**Comment by girishmg** [comment]
@shettyg with what we have in the current Dockerfile for Ubuntu we have a flexibility to install latest and greatest OVS/OVN software and check the OVN K8s code against it. I think it will be very helpful to have this for developers on at least one distribution.

**Comment by shettyg** [comment]
@girishmg Fair. I updated 3.19.28.122 with 2.12.0

**Comment by dcbw** [comment]
@girishmg this PR includes the Dockerfile changes for Centos as well, and I'm OK with those, so feel free to merge if you are happy with the updates.

**Comment by girishmg** [comment]
@dcbw Agree.

@TrevorTaoARM Can you please submit a PR with just changes to the Centos Dockerfile? Thanks.

**Comment by girishmg** [comment]
@TrevorTaoARM I merged your other PR that had changes to CentOS alone. I think we can close this PR since we decided to keep Dockerfile.ubuntu as is since it already installs 2.11.x OVS/OVN.

**Comment by TrevorTaoARM** [comment]
@girishmg OK, I know what you said. 

One issue here is the original Dockerfile.ubuntu can only support ovs 2.11+ installation for x86_64 but not aarch64(arm64) since it uses a 3rd party ovs lib(http://3.19.28.122/openvswitch/stable)  which only support x86_64 but not aarch64(arm64). 

If we use ubuntu:19.04, the ovs 2.11 of both x86_64 and aarch64 can be supported at the same time without any differences.

**Comment by girishmg** [comment]
@shettyg do you have cross compilers setup to build OVS/OVN packages for ARM as well? Thanks.

**Comment by shettyg** [comment]
No. May be a if else condition there?

**Comment by TrevorTaoARM** [comment]
I thought about one possible alternative solution for this issue: Can I add a file, which may be named as Dockerfile.ubuntu.arm64, and add some build helpers in the Makefile to help ovn-k8s work on arm.
On the other side, maybe a simple guide for the building and status of ovn-k8s on arm is also helpful.

**Comment by dcbw** [comment]
> I thought about one possible alternative solution for this issue: Can I add a file, which may be named as Dockerfile.ubuntu.arm64, and add some build helpers in the Makefile to help ovn-k8s work on arm.
> On the other side, maybe a simple guide for the building and status of ovn-k8s on arm is also helpful.

@TrevorTaoARM sure? let's see what that would look like. Thanks!

**Comment by trozet** [comment]
@TrevorTaoARM can we close this? I see Ubuntu image is pulling from:

http://3.19.28.122/openvswitch/stable

which has 2.12 OVN in it?

**Comment by girishmg** [comment]
@trozet yes, we can.

**Comment by TrevorTaoARM** [comment]
OK.The link http://3.19.28.122/openvswitch/stable supports x86_64 well.
For arm64, we would look at alternative solutions in the future.

**Pull request closed without merging**
