### PR TITLE
Port need not be specified for a protocol in a network policy

### PR DESCRIPTION
**Pull request by venuiyer**
K8s network policy allows to specify the protocol, but if the port
is not specified, it is taken to mean all the ports for that
protocol

"If specified, the port on the given protocol.  This can either be a
numerical or named port on a pod.  If this field is not provided, this
matches all port names and numbers. If present, only traffic on the
specified protocol AND port will be matched.
+optional"

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by venuiyer** [comment]
sorry @trozet saw this now; yeah, somehow missed the signed-off; looks like this PR is merged, any way I can fix this now?
don't want force push, if possible.

**Comment by trozet** [comment]
@venuiyer I don't think so. Don't worry about it, just in the future please add it.

**Comment by venuiyer** [comment]
sure, will do, thanks @trozet!

**Pull request merged**
