### PR TITLE
pkg/cluster: set br-nexthop mtu

### PR DESCRIPTION
**Pull request by juanluisvaladas**
Creates br-nexthop with the same MTU as br-int.

### CODE REVIEW

**Comment by russellb** [comment]
> Creates br-nexthop with the same MTU as br-int.

I would find it helpful to expand a bit on the commit message.  What symptoms were observed that led to seeing the need for this change?  What does it fix?

**Comment by pecameron** [comment]
@russellb The default 1500 doesn't work with gcp (which has an mtu of 1460). Also when we pass in the MTU (cno PR333) on aws the interface gets set to 9001 and the gateway to 1500. This causes problems for pods reaching host net services (openshift api server).

**Comment by russellb** [comment]
> @russellb The default 1500 doesn't work with gcp (which has an mtu of 1460). Also when we pass in the MTU (cno PR333) on aws the interface gets set to 9001 and the gateway to 1500. This causes problems for pods reaching host net services (openshift api server).

That's very useful info that would be helpful to have in the commit message history.  :-)

**Comment by dcbw** [comment]
@juanluisvaladas testcases are failing, you need to update the expected command in the testcases to include the new mtu_request bits.

**Comment by dcbw** [comment]
@juanluisvaladas nevermind, added those bits and pushed so I can merge soon soon soon.

**Pull request merged**
