### PR TITLE
wait longer for ovnkube-node rollout to complete for NetFlow e2e test

### PR DESCRIPTION
**Pull request by girishmg**
the NetFlow e2e tests changes the environment variable for the
ovnkube-node daemonset and this results in rolling update of the
ovnkube-node Pods which is very involved process and the current 40
seconds will not help. the rollout involves first terminating all of
the ovnkube-node Pods and re-creating them.

@rcarrillocruz the E2E tests for NetFlow were timing out frequently, and this PR should
hopefully fix it.

### CODE REVIEW

**Review by trozet — COMMENTED** [review]
I'm on my phone so can't really tell, but wanted to ask if the test will ensure that the nodes are all fully rolled out before completing. Meaning that we don't just check one node netflow worked and then move onto the next test while other workers could still be coming up.

**Comment by girishmg** [comment]
@trozet the test doesn't wait for all the ovnkube-node pods to come up. I think it should. I will fix that too. Thanks.

**Comment by rcarrillocruz** [comment]
good catch, thx

**Pull request closed without merging**
