### PR TITLE
apbroute: consolidate some startup code

### PR DESCRIPTION
**Pull request by dcbw**
Do the same work, but in loops rather than duplicating code.

### CODE REVIEW

**Comment by trozet** [comment]
@jordigilh FYI

**Comment by trozet** [comment]
@dcbw this is the same change as https://github.com/ovn-org/ovn-kubernetes/pull/3629/files ?

**Comment by dcbw** [comment]
@trozet my bad; not supposed to be. How about now?

**Review by trozet — APPROVED** [review]
@jordigilh PTAL

**Pull request merged**
