### PR TITLE
[wip] Node ip netlink fixup

### PR DESCRIPTION
**Pull request by dcbw**
Test out some changes to netlink to allow us to cleanly terminate the address subscription.

@tssurya

### CODE REVIEW

**Comment by tssurya** [comment]
hmm seems like updating lint to new version also doesn't fix it yet...

**Comment by tssurya** [comment]
It's a bit funny as to why the job picks up linter version 1.33.s still? seems like it doesn't read from our hack file?: https://github.com/ovn-org/ovn-kubernetes/runs/5778087394?check_suite_focus=true#step:3:27

**Comment by tssurya** [comment]
ah the job is using another another version:
```
jobs:
  # separate job for parallelism
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Verify
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.33.2
        working-directory: go-controller
        args: --modules-download-mode=vendor --timeout=15m0s --verbose
```
opened https://github.com/ovn-org/ovn-kubernetes/pull/2889

**Comment by trozet** [comment]
stale PR, please reopen and rebase if you intend to get this in

**Pull request closed without merging**
