### PR TITLE
Add egress-ip doc

### PR DESCRIPTION
**Pull request by flavio-fernandes**
Document egress IP functionality.

Emphasis on this commit was done in documenting the gRPC enhancement that is now implemented as part of the Egress IP reachability logic.

Reported-at: https://issues.redhat.com/browse/SDN-3470
Signed-off-by: Flavio Fernandes <flaviof@redhat.com>

### CODE REVIEW

**Comment by jcaamano** [comment]
LGTM

@kyrtapz PTAL

**Comment by kyrtapz** [comment]
/lgtm
Thanks Flavio!

**Review by jcaamano — APPROVED** [review]

**Pull request merged**
