### PR TITLE
testing: add plural/array versions of MustParseIP and MustParseIPNet

### PR DESCRIPTION
**Pull request by danwinship**
We have `ovntest.MustParseIP` and `ovntest.MustParseIPNet` for simplifying tests, but as more code becomes dual-stack, we need to explicitly construct arrays in more places and it seemed like this would be simpler...

### CODE REVIEW

**Comment by Billy99** [comment]
/lgtm
Much cleaner. Thank you.

**Comment by dave-tucker** [comment]
@danwinship seems that it needs a `gofmt -w -s` on unspecified files :upside_down_face: , otherwise I think this is good to go.

**Comment by dcbw** [comment]
shard-other failure is due to leader election.

**Pull request merged**
