### PR TITLE
go mod: Manually solve dependabot conflicts

### PR DESCRIPTION
**Pull request by oshoval**
**- What this PR does and why is it needed**
This commit is applying those PRs and fix the conflicts between them

https://github.com/ovn-org/ovn-kubernetes/pull/3816 
https://github.com/ovn-org/ovn-kubernetes/pull/3817

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by oshoval** [comment]
Lets see if all pass, having problem atm to check manually

**Comment by maiqueb** [comment]
I think we'll keep seeing a lot of dependabot PRs about bumping these 2 libs.

Wouldn't it be better to just drop these dependencies and pass the name of the bridge via env variables as it is being done in other tests ? 

I've suggested this before in https://github.com/ovn-org/ovn-kubernetes/pull/3801#discussion_r1279093249 . Other tests are doing this FWIW.

**Comment by oshoval** [comment]
> I think we'll keep seeing a lot of dependabot PRs about bumping these 2 libs.
> 
> Wouldn't it be better to just drop these dependencies and pass the name of the bridge via env variables as it is being done in other tests ?
> 
> I've suggested this before in [#3801 (comment)](https://github.com/ovn-org/ovn-kubernetes/pull/3801#discussion_r1279093249) . Other tests are doing this FWIW.

imo lets give it a chance please ?
we can always remove if something require busy work
btw there might be a solution that we find that will eliminate the busy work

**Comment by oshoval** [comment]
All passed

**Comment by jcaamano** [comment]
Ok, let's see how busy this makes us be. The protobuf one was already there.

**Review by jcaamano — APPROVED** [review]

**Pull request merged**
