### PR TITLE
Change the source repo of containernetwork-cni

### PR DESCRIPTION
**Pull request by TrevorTaoARM**
It seems the containernetwork-cni rpm package had been
removed from the official fedoraproject repo which leads to
an error when building the image.
Now we turn to a 3rd party repo to get that package and
make the building process work.

Signed-off-by: trevor tao <trevor.tao@arm.com>

### CODE REVIEW

**Comment by shettyg** [comment]
@pecameron PTAL

@girishmg For Ubuntu, we don't use this. Do you know the difference?

**Comment by girishmg** [comment]
@shettyg I don't know why we need containernetworking-cni inside of our docker images. It should be installed on each of the K8s node explicitly.

In the case of Ubuntu we have:

```
# dpkg --search /opt/cni/bin/ipvlan 
kubernetes-cni: /opt/cni/bin/ipvlan
# apt-cache rdepends kubernetes-cni |sort -u
  kubeadm
  kubelet
Reverse Depends:
# 
```
So, all the CNI stuff gets installed as part of kubeadm/kubelet installation.

**Comment by dcbw** [comment]
I'm not sure why they are needed either; for OpenShift they will get installed by Multus. Perhaps we used it long ago for the 'loopback' plugin or something?

**Comment by pecameron** [comment]
@dcbw @girishmg @shettyg At one point it was a rpm dependency. If we no longer need it, just drop it.

**Comment by girishmg** [comment]
@TrevorTaoARM can you please resubmit a fix with the following line removed?
```
 RUN rpm -i http://dl.fedoraproject.org/pub/epel/7/${rpmArch}/Packages/c/containernetworking-cni-0.5.1-1.el7.${rpmArch}.rpm
```
In fact there are so many packages that can be removed that Dockerfile, but that is for some other day.

**Comment by TrevorTaoARM** [comment]
> @TrevorTaoARM can you please resubmit a fix with the following line removed?
> 
> ```
>  RUN rpm -i http://dl.fedoraproject.org/pub/epel/7/${rpmArch}/Packages/c/containernetworking-cni-0.5.1-1.el7.${rpmArch}.rpm
> ```
> 
> In fact there are so many packages that can be removed that Dockerfile, but that is for some other day.

Yes, I would remove that line if it's not needed here.

**Pull request closed without merging**
