### PR TITLE
Kind script: add support for podman

### PR DESCRIPTION
**Pull request by jotak**
- Support in Makefile (e.g. OCI_BIN=podman make fedora)
- Support in kind.sh with flag "-ep podman"

Signed-off-by: Joel Takvorian <jtakvori@redhat.com>

**- What this PR does and why is it needed**

This PR adds podman support for kind. Currently, only docker is supported, and building / deploying with podman fails.

**- Special notes for reviewers**

None

**- How to verify it**

- Non-regression with docker must be verified (I only have podman on my machine, didn't test with docker). Basically, need to check that the instructions here are still working: https://github.com/ovn-org/ovn-kubernetes/blob/master/docs/kind.md

- I wrote a gist to give instructions with podman, as they slightly differ: https://gist.github.com/jotak/068cee03ef1ba9fea467d96daf811cbd . Not sure if they have to be integrated in the documentation, as it involves some workarounds , and starting kind as root. Or perhaps we can just link to this gist from the documentation.

**- Description for the changelog**

Added support for podman in script for Kind.

### CODE REVIEW

**Comment by jotak** [comment]
cc @astoycos

**Comment by trozet** [comment]
@squeed FYI

**Review by trozet — CHANGES_REQUESTED** [review]
Thanks Joel. I tried out your PR and it worked for me running with the instructions from your gist. Can you please include those in this PR under https://github.com/openshift/ovn-kubernetes/blob/master/docs/kind.md ?

Also, when can we expect to be able to deploy without sudo?

**Comment by jotak** [comment]
> Thanks Joel. I tried out your PR and it worked for me running with the instructions from your gist. Can you please include those in this PR under https://github.com/openshift/ovn-kubernetes/blob/master/docs/kind.md ?

Sure, doc added

> 
> Also, when can we expect to be able to deploy without sudo?

Unfortunately I can't give an answer, the solution with sudo is sufficient for me at the moment, I keep that at the back of my mind but can't give an ETA

**Review by trozet — APPROVED** [review]
/lgtm and wfm

**Comment by jotak** [comment]
Hey @trozet , thanks for merging it; just a quick follow-up: I did a quick try to upgrade the `kindest/node` image to a more recent one and see if it helps to run with podman without sudo: and it does. So, using `v1.20.7` instead of `v1.20.0` seems to fix some issues.

Then, there is another issue on the ovn-node-* pods, they fail to start due to a bunch of permission issues, here's the message:

```
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   ================== ovnkube.sh --- version: 3 ================
 ==================== command: ovs-server
 =================== hostname: ovn-control-plane
 =================== daemonset version 3
 =================== Image built from ovn-kubernetes ref: refs/heads/master  commit: fde614f72dd031ca61914aaf90c3f44c53a58da3
nice: cannot set niceness: Permission denied
Starting ovsdb-server.
Configuring Open vSwitch system IDs.
Enabling remote OVSDB managers.
modprobe: ERROR: could not insert 'openvswitch': Operation not permitted
Inserting openvswitch module ... failed!
rmmod: ERROR: could not remove 'bridge': Operation not permitted
rmmod: ERROR: could not remove module bridge: Operation not permitted
removing bridge module ... failed!

      Exit Code:    1
```

Let me know if you'd like me to try some fix.

**Pull request merged**
