### PR TITLE
Fix egressip test not waiting for update processing before delete

### PR DESCRIPTION
**Pull request by jcaamano**
This egressip test is updating and then deleting an egressip. The expectations in between do not correctly verify if the update had been processed. Sometimes the update would not be processed at all because we get the delete event before that.

Then when we process the delete, we only look at the deleted egress ip status items but not at any other status items the pod would have been previously assigned. In this specific case those other status items are not cleared and the standby egressip does not take over.

This fixes the UT to correctly verify that the update has been process. But there might be another bug to fix in the egressip logic.

### CODE REVIEW

**Comment by jcaamano** [comment]
@tssurya PTAL

**Comment by jcaamano** [comment]
These are logs showing how two events are ignored and then the controller only removes node 2 status, and node 1 status remains:

```
2023-06-28T23:46:44.1611693Z I0628 23:46:44.096758   22215 obj_retry.go:512] Update event received for resource *v1.EgressIP, old object is equal to new: false
2023-06-28T23:46:44.1612153Z I0628 23:46:44.096887   22215 obj_retry.go:552] Ignoring update event for *v1.EgressIP egressip as it was not found in informer cache and is not in a terminal state
2023-06-28T23:46:44.1612782Z I0628 23:46:44.097001   22215 obj_retry.go:512] Update event received for resource *v1.EgressIP, old object is equal to new: false
2023-06-28T23:46:44.1613240Z I0628 23:46:44.097101   22215 obj_retry.go:552] Ignoring update event for *v1.EgressIP egressip as it was not found in informer cache and is not in a terminal state
2023-06-28T23:46:44.1613658Z I0628 23:46:44.097172   22215 obj_retry.go:660] Delete event received for *v1.EgressIP egressip
2023-06-28T23:46:44.1614043Z I0628 23:46:44.097258   22215 egressip.go:633] Deleting pod egress IP status: {node2 192.168.126.30} for EgressIP: egressip
```

**Comment by tssurya** [comment]
unrelated flake: https://github.com/ovn-org/ovn-kubernetes/actions/runs/5411238262/jobs/9835455378?pr=3726
```
2023-06-29T12:37:38.4369324Z 
2023-06-29T12:37:38.4374572Z [91m[1mSummarizing 1 Failure:[0m
2023-06-29T12:37:38.4374973Z 
2023-06-29T12:37:38.4377481Z [91m[1m[Panic!] [0m[90mOVN External Gateway namespace [0m[0mWhen deleting a namespace [0m[91m[1m[It] validates that the namespace info cache is only recreated after deletion when all the pods in the namespace are deleted after a new event to create the namespace  [0m
2023-06-29T12:37:38.4379703Z [37m/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/vendor/github.com/onsi/gomega/internal/async_assertion.go:321[0m
2023-06-29T12:37:38.4380153Z 
2023-06-29T12:37:38.4380616Z [1m[91mRan 51 of 51 Specs in 25.282 seconds[0m
2023-06-29T12:37:38.4381842Z [1m[91mFAIL![0m -- [32m[1m50 Passed[0m | [91m[1m1 Failed[0m | [33m[1m0 Pending[0m | [36m[1m0 Skipped[0m
2023-06-29T12:37:38.4382444Z --- FAIL: TestApbroute (25.35s)
2023-06-29T12:37:38.4382773Z FAIL
2023-06-29T12:37:38.4509960Z coverage: 42.7% of statements
```

**Review by tssurya — APPROVED** [review]
/lgtm
this change lgtm
i hope we can determine the real bugs soon-ish let's see

**Pull request closed without merging**
