### PR TITLE
Disable race detector until we have race free code

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
Signed-off-by: Alexander Constantinescu <aconstan@redhat.com>

We are currently running CI with the race detector set to "on". However our code is not fully thread-safe, we have code such as https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/util/iptables.go#L35 and https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/util/iptables.go#L78 which are thread-unsafe.

PR: https://github.com/ovn-org/ovn-kubernetes/pull/1484 is quite heavily impacted by this particular case as it adds a lot more tests on the node side. 

To not block people and their PRs during week, I propose to disable the race detector for now. 

I will take care of fixing all race conditions found, ASAP, in the mean time. 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by dcbw** [comment]
I'm OK with this if others agree.

**Comment by trozet** [comment]
I'm OK with it as well. We probably need to get agreement from @aojea though since he added the race detector stuff.

**Comment by alexanderConstantinescu** [comment]
```
Executed commands do not match expected commands!
[00] ! /fake-bin/ovn-nbctl --timeout=15 --data=bare --no-heading --columns=_uuid find ACL match="ip4.src == {$a4417941599443114881} && outport == @pg-name" external-ids:namespace=testing external-ids:policy=policy external-ids:Ingress_num=0 external-ids:policy_type=Ingress
[01] ! /fake-bin/ovn-nbctl --timeout=15 set acl 94407fe0-2c15-4a63-baea-ab4af0ea5bb8 match="ip4.src == {$a4417941599443114881, $a7467980285203883600} && outport == @pg-name"
FAIL	github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn	0.243s
FAIL
##[error]Makefile:30: recipe for target 'check' failed
```

I have seen that happen locally too, will need to be addressed in a separate issue as well.

/retest

**Comment by danwinship** [comment]
(I think the ovn-kube bot only recognizes "/retest" when it's alone in the comment)

**Comment by danwinship** [comment]
> `Executed commands do not match expected commands!`

There's already an issue filed about this (#1543). It seems to have suddenly gotten worse though

**Comment by trozet** [comment]
> ```
> Executed commands do not match expected commands!
> [00] ! /fake-bin/ovn-nbctl --timeout=15 --data=bare --no-heading --columns=_uuid find ACL match="ip4.src == {$a4417941599443114881} && outport == @pg-name" external-ids:namespace=testing external-ids:policy=policy external-ids:Ingress_num=0 external-ids:policy_type=Ingress
> [01] ! /fake-bin/ovn-nbctl --timeout=15 set acl 94407fe0-2c15-4a63-baea-ab4af0ea5bb8 match="ip4.src == {$a4417941599443114881, $a7467980285203883600} && outport == @pg-name"
> FAIL	github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn	0.243s
> FAIL
> ##[error]Makefile:30: recipe for target 'check' failed
> ```
> 
> I have seen that happen locally too, will need to be addressed in a separate issue as well.
> 
> /retest

https://github.com/ovn-org/ovn-kubernetes/issues/1543

**Comment by alexanderConstantinescu** [comment]
PR: https://github.com/ovn-org/ovn-kubernetes/pull/1551/commits took over, closing this accordingly

**Pull request closed without merging**
