### PR TITLE
udn: Wire up multicast for primary networks.

### PR DESCRIPTION
**Pull request by qinqon**
#### What this PR does and why is it needed
TODO:
- [ ] The e2e IGMP test depends on installing tcpdump, but we don't have egress yet to do so
- [ ] Unit test, reuse stuff under `pkg/ovn/mutlicast_test.go`

#### Which issue(s) this PR fixes

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by qinqon** [comment]
After activating multicast for primary UDN 
```
E0722 10:36:26.601360    1131 base_network_controller.go:442] object not found
E0722 10:36:26.601385    1131 secondary_layer3_network_controller.go:112] Node add failed for ovn-worker2, will try again later: nodeAdd: error adding node "ovn-worker2" for network cwvgn_gryffindor: failed adding port to portgroup for multicast: object not found
I0722 10:36:26.601404    1131 obj_retry.go:370] Retry add failed for *v1.Node ovn-worker2, will try again later: nodeAdd: error adding node "ovn-worker2" for network cwvgn_gryffindor: failed adding port to portgroup for multicast: object not found

```

**Comment by qinqon** [comment]
e2e passes at CI but not locally.

**Comment by qinqon** [comment]
Default deny is breaking multicast, this are the ACLs so far 
```
_uuid               : 8dbd89c3-9ac2-4532-bda9-9b1df3d85b28
action              : drop
direction           : to-lport
external_ids        : {direction=Ingress, "k8s.ovn.org/id"="rzgnb_gryffindor-network-controller:MulticastCluster:DefaultDeny:Ingress", "k8s.ovn.org/owner-controller"=rzgnb_gryffindor-network-controller, "k8s.ovn.org/owner-type"=MulticastCluster, type=DefaultDeny}
label               : 0
log                 : false
match               : "(ip4.mcast || mldv1 || mldv2 || (ip6.dst[120..127] == 0xff && ip6.dst[116] == 1))"
meter               : acl-logging
name                : []
options             : {}
priority            : 1011
severity            : []
tier                : 2

_uuid               : 10c39707-c72e-4da4-9664-8c6fabc88c1f
action              : drop
direction           : from-lport
external_ids        : {direction=Egress, "k8s.ovn.org/id"="rzgnb_gryffindor-network-controller:MulticastCluster:DefaultDeny:Egress", "k8s.ovn.org/owner-controller"=rzgnb_gryffindor-network-controller, "k8s.ovn.org/owner-type"=MulticastCluster, type=DefaultDeny}
label               : 0
log                 : false
match               : "(ip4.mcast || mldv1 || mldv2 || (ip6.dst[120..127] == 0xff && ip6.dst[116] == 1))"
meter               : acl-logging
name                : []
options             : {apply-after-lb="true"}
priority            : 1011
severity            : []
tier                : 2

_uuid               : 81c88bd7-e726-45cf-837f-37ca91c18de4
action              : drop
direction           : to-lport
external_ids        : {direction=Ingress, "k8s.ovn.org/id"="default-network-controller:MulticastCluster:DefaultDeny:Ingress", "k8s.ovn.org/owner-controller"=default-network-controller, "k8s.ovn.org/owner-type"=MulticastCluster, type=DefaultDeny}
label               : 0
log                 : false
match               : "(ip4.mcast || mldv1 || mldv2 || (ip6.dst[120..127] == 0xff && ip6.dst[116] == 1))"
meter               : acl-logging
name                : []
options             : {}
priority            : 1011
severity            : []
tier                : 2

_uuid               : f5626f2a-ebc1-43f1-b8a3-adb3e6e0aa53
action              : allow
direction           : from-lport
external_ids        : {direction=Egress, "k8s.ovn.org/id"="rzgnb_gryffindor-network-controller:MulticastCluster:AllowInterNode:Egress", "k8s.ovn.org/owner-controller"=rzgnb_gryffindor-network-controller, "k8s.ovn.org/owner-type"=MulticastCluster, type=AllowInterNode}
label               : 0
log                 : false
match               : "inport == @a10122709809664695909 && (ip4.mcast || mldv1 || mldv2 || (ip6.dst[120..127] == 0xff && ip6.dst[116] == 1))"
meter               : acl-logging
name                : []
options             : {apply-after-lb="true"}
priority            : 1012
severity            : []
tier                : 2

_uuid               : 733c2a1a-25c9-4f72-a56f-77d8c87b6aba
action              : allow
direction           : from-lport
external_ids        : {direction=Egress, "k8s.ovn.org/id"="rzgnb_gryffindor-network-controller:MulticastNS:network-segmentation-668:Egress", "k8s.ovn.org/name"=network-segmentation-668, "k8s.ovn.org/owner-controller"=rzgnb_gryffindor-network-controller, "k8s.ovn.org/owner-type"=MulticastNS}
label               : 0
log                 : false
match               : "inport == @a14005067550931942570 && (ip4.mcast || (mldv1 || mldv2 || (ip6.dst[120..127] == 0xff && ip6.dst[116] == 1)))"
meter               : acl-logging
name                : []
options             : {apply-after-lb="true"}
priority            : 1012
severity            : []
tier                : 2

_uuid               : 4ca31f5a-11dd-4125-864a-9ce6fc107f93
action              : allow
direction           : to-lport
external_ids        : {direction=Ingress, "k8s.ovn.org/id"="rzgnb_gryffindor-network-controller:MulticastNS:network-segmentation-668:Ingress", "k8s.ovn.org/name"=network-segmentation-668, "k8s.ovn.org/owner-controller"=rzgnb_gryffindor-network-controller, "k8s.ovn.org/owner-type"=MulticastNS}
label               : 0
log                 : false
match               : "outport == @a14005067550931942570 && ((igmp || (ip4.src == $a16357502162385096434 && ip4.mcast)) || (mldv1 || mldv2 || (ip6.src == $a16357499963361840012 && (ip6.dst[120..127] == 0xff && ip6.dst[116] == 1))))"
meter               : acl-logging
name                : []
options             : {}
priority            : 1012
```
```

**Comment by qinqon** [comment]
Ok, the per namepsace port group is missing the LSPs 
```
_uuid               : 3c8d8603-345c-4bec-ac25-93b0a0d12ed8
acls                : [de0f1ea1-0576-4903-a123-6b862eafb703, f7fb75a3-0234-476f-ab79-9c6832b99fbf]
external_ids        : {"k8s.ovn.org/id"="rzgnb_gryffindor-network-controller:Namespace:network-segmentation-668", "k8s.ovn.org/name"=network-segmentation-668, "k8s.ovn.org/owner-controller"=rzgnb_gryffindor-network-controller, "k8s.ovn.org/owner-type"=Namespace}
name                : a14005067550931942570
ports               : []

```

**Comment by qinqon** [comment]
Legit unit test failure
```
• Failure [1.524 seconds]
OVN MultiNetworkPolicy Operations
/home/ellorent/Documents/cnv/upstream/ovn-kubernetes/go-controller/pkg/ovn/multipolicy_test.go:219
  during execution
  /home/ellorent/Documents/cnv/upstream/ovn-kubernetes/go-controller/pkg/ovn/multipolicy_test.go:427
    correctly adds and deletes pod IPs from secondary network namespace address set
    /home/ellorent/Documents/cnv/upstream/ovn-kubernetes/go-controller/pkg/ovn/multipolicy_test.go:560
      on remote zone for layer3 topology [It]
      /home/ellorent/Documents/cnv/upstream/ovn-kubernetes/go-controller/pkg/ovn/multipolicy_test.go:652

      Timed out after 1.001s.
      The function passed to Eventually failed at /home/ellorent/Documents/cnv/upstream/ovn-kubernetes/go-controller/pkg/ovn/address_set/fake_address_set.go:202 with:
      Expected
          <map[string]string | len:0>: {}
      to have key
          <string>: 10.1.1.1

      /home/ellorent/Documents/cnv/upstream/ovn-kubernetes/go-controller/pkg/ovn/address_set/fake_address_set.go:248
------------------------------

```

**Comment by qinqon** [comment]
IGMP query test not working for primary UDNs.

**Comment by dceara** [comment]
Closing in favor of #4797

**Pull request closed without merging**
