### PR TITLE
Add scripts for daemonset installation

### PR DESCRIPTION
**Pull request by TrevorTaoARM**
Add scripts for daemonset install, check and wait for
the installation status by the needed running
pods and services.

Signed-off-by: Trevor Tao <trevor.tao@arm.com>

### CODE REVIEW

**Comment by dcbw** [comment]
Looks OK to me; @girishmg what do you think?

**Comment by girishmg** [comment]
@dcbw I have not tested it, but looks OK to me as well.

**Comment by danwinship** [comment]
@dcbw and @girishmg both said this looked good, but then it never got merged...

@TrevorTaoARM is this still relevant? Is it still correct or does it need updates?

The file should probably be called `install-ovn-k8s.sh` for consistency with other shell scripts. (ie, add `.sh`)

**Comment by TrevorTaoARM** [comment]
> @dcbw and @girishmg both said this looked good, but then it never got merged...
> 
> @TrevorTaoARM is this still relevant? Is it still correct or does it need updates?
> 
> The file should probably be called `install-ovn-k8s.sh` for consistency with other shell scripts. (ie, add `.sh`)

@danwinship Updated accordingly. Thanks.

**Pull request merged**
