### PR TITLE
Add metric to record gateway modes

### PR DESCRIPTION
**Pull request by tssurya**
A metric is the first step towards telemetry and we need
to know the count of lgw users. This will be a first step
towards that.

Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>

### CODE REVIEW

**Comment by tssurya** [comment]
Screenshot from 2022-02-25 22-48-05
ok I think that looks good. @martinkennelly if you agree I can get Simon's to check this out?

**Comment by tssurya** [comment]
Then I converted the cluster to LGW mode and metrics didn't update :(
I wonder if this is an install time thing only? I thought these things are scraped continuously...

**Comment by tssurya** [comment]
> Then I converted the cluster to LGW mode and metrics didn't update :( I wonder if this is an install time thing only? I thought these things are scraped continuously...

nvm, I was stupidly calling register from the node code.

**Comment by tssurya** [comment]
I am not sure if this metric should go into the node part since "gateway" is kind of dataplane...
https://github.com/ovn-org/ovn-kubernetes/blob/a24a233130fb87e07557d8c1579ad52a861fde96/go-controller/pkg/node/gateway_init.go#L308

**Comment by martinkennelly** [comment]
/lgtm
I know the issue of non-leaders exposing metrics is not nice and we will fix this soon but its not something that should block this PR.

**Review by trozet — APPROVED** [review]

**Pull request merged**
