### PR TITLE
Fix panic if nadController is nil

### PR DESCRIPTION
**Pull request by tssurya**
When multi network feature is not enabled,
the nadController will be nil. So while stopping
the controllers, we need to check if nadController is nil or not, else we'll panic.

panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x193c7ee]
```
goroutine 1 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/network-controller-manager.(*netAttachDefinitionController).GetAllNetworkControllers(0x0)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/network-controller-manager/network_attach_def_controller.go:307 +0x2e
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/network-controller-manager.(*networkControllerManager).Stop(0xc000540210)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/network-controller-manager/network_controller_manager.go:421 +0x5c
main.runOvnKube(0xc0004baa80, 0xc0004baa80?)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:314 +0xbc5
main.main.func1(0xc0003a4800?)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:108 +0x1d
github.com/urfave/cli/v2.(*App).RunContext(0xc0000d8d80, {0x2148e48?, 0xc00051b740}, {0xc000006a00, 0x27, 0x28})
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/v2/app.go:315 +0x9f5
main.main()
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/cmd/ovnkube/ovnkube.go:132 +0xba9
```
Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by cathy-zhou** [comment]
lgtm

**Comment by dcbw** [comment]
lgtm

**Review by maiqueb — APPROVED** [review]
Thanks for the quick fix!

**Review by martinkennelly — APPROVED** [review]

**Review by trozet — APPROVED** [review]

**Pull request merged**
