### PR TITLE
Improve ovn-kube scale by increasing queue handlers

### PR DESCRIPTION
**Pull request by trozet**
Increasing the number of queues has shown a reduction in pod creation
time as well as getting rid of "Timed out waiting for annotations"
errors. In some basic scale tests, assuming heavy load on the cluster
(300ms for each logical port add) and adding 5k pods:

15 pod handlers  - 117s
150 pod handlers - 16s

Under downstream real scale testing, we see a drop from 30.5 seconds
average pod ready time, to 20.8 seconds. The CPU remained about the same
throughout the run, but there is an increased memory cost. I estimate
around 100MB increase in ovnkube-master with this patch during scale
testing of 20 nodes with 5k pods created.

Signed-off-by: Tim Rozet <trozet@redhat.com>

### CODE REVIEW

**Comment by girishmg** [comment]
@trozet Winson came back with these numbers. He is on PTO till Aug 3rd, so sharing it on his behalf.

Baseline (Time taken to bring up 3000 Pods)
```
Tue Jul 27 10:17:56 PDT 2021
303
Tue Jul 27 10:18:57 PDT 2021
1117
Tue Jul 27 10:19:58 PDT 2021
2204
Tue Jul 27 10:21:00 PDT 2021
2908
Tue Jul 27 10:22:02 PDT 2021
2991
Tue Jul 27 10:23:04 PDT 2021
3000
```

With this PR (Time taken to bring up 3000 Pods)
```
Tue Jul 27 20:21:59 PDT 2021
286
Tue Jul 27 20:23:00 PDT 2021
1555
Tue Jul 27 20:24:01 PDT 2021
2770
Tue Jul 27 20:25:03 PDT 2021
3000
```

So, it is significantly faster...

**Comment by trozet** [comment]
After some more testing/investigation, found that although this gave us some better scale, it was not the right solution. The enqueueEvents are not fairly distributed to each queue, so after changing that, we do not need as many queues. In fact, more queues only increases contention across handler threads, and results in higher variation of pod ready consistency. Going to close this and open another PR with a batch of changes that fix these issues.

**Pull request closed without merging**
