### PR TITLE
[WIP] Pod network crd

### PR DESCRIPTION
**Pull request by npinaeva**

### CODE REVIEW

**Comment by maiqueb** [comment]
Hey @npinaeva !

Very happy to see something like this being pushed.

... in fact, I had (year or so ago...) written an openshift enhancement proposal about this - but for secondary networks.

I think it could make sense to generalize this and have a CRD for an OVN-K network.

The aforementioned openshift enhancement is available in https://github.com/openshift/enhancements/pull/811

Any thoughts ? (good or bad ...)

**Comment by npinaeva** [comment]
Hey @maiqueb , I am afraid the purpose of this PR is a bit different: the new PodNetwork object is only supposed to be created by ovn-k itself, it is used instead of the annotations to save and share information about the assigned pod ips (and other network-related info). So users should only have read access to this object, and not request something by creating it.

**Comment by maiqueb** [comment]
> Hey @maiqueb , I am afraid the purpose of this PR is a bit different: the new PodNetwork object is only supposed to be created by ovn-k itself, it is used instead of the annotations to save and share information about the assigned pod ips (and other network-related info). So users should only have read access to this object, and not request something by creating it.

I understand - I never thought of asking you to implement that in this PR - it would happen in a follow-up PR, pushed by someone else.

I don't think the two have to exclusive: we could have the same object for both, with a parameter to indicate a network as the default cluster network. Users would not be able to create these - only secondaries. 

If the CRD's API can fit both use cases, I think it would be preferable to use a single CRD.

**Pull request closed without merging**
