### PR TITLE
ovn/node: use node name as chassis hostname

### PR DESCRIPTION
**Pull request by dcbw**
In some cloud environments the Kube node name is a short name, while
the node's "hostname" is an FQDN. eg:

node.Name: ci-op-h2qtbcsi-99b10-qhxj2-worker-d-6wxxl
hostname:  ci-op-h2qtbcsi-99b10-qhxj2-worker-d-6wxxl.c.openshift-gce-devel-ci.internal

syncNodesPeriodic() assumed they were going to be the same, which
resulted in deleting all chassis records from the SBDB every five
minutes, because ovnkube-node was setting the node's FQDN as the
hostname external_id.

Just make the chassis name the same as the Kube node object to
reduce confusion. ovn-controller doesn't care if it's a real
hostname or not. Nor does anything else.

@trozet @girishmg

### CODE REVIEW

**Comment by trozet** [comment]
@dceara FYI

**Comment by aojea** [comment]
/retest
great catch

**Comment by danwinship** [comment]
So what effect will this have on upgrade? Or is the answer "if you were on an affected system it wouldn't have stayed up long enough for you to be able to upgrade anyway?"

**Comment by girishmg** [comment]
@dcbw should we special case this based on the Cloud Provider, like we do in `clearInitialNodeNetworkUnavailableCondition`.

I have same question as @danwinship. Luckily, in our clusters node.Name is same as `hostname`, so we will not get affected by this change, though.

**Comment by dcbw** [comment]
> So what effect will this have on upgrade? Or is the answer "if you were on an affected system it wouldn't have stayed up long enough for you to be able to upgrade anyway?"

@danwinship it currently affects GCP and perhaps Azure. When the external-id changes ovn-controller will just update the existing chassis record since they are indexed by system-id, not hostname.

**Comment by abhat** [comment]
@dcbw Nice catch. when I had run manual tests for this in OCP, I had tested with AWS only. Sigh. 

How does the hostname external_id get used by the controller? It looks like it gets used in physical.c and binding.c. Not sure about the OVN details there. Other than that clarification, LGTM.

**Comment by dcbw** [comment]
> How does the hostname external_id get used by the controller? It looks like it gets used in physical.c and binding.c. Not sure about the OVN details there. Other than that clarification, LGTM.

@abhat I don't believe OVN cares what the chassis hostname is. ovn-controller just uses that to set the Hostname field of its Chassis record. Most uses of Chassis use the "Name" which (confusingly) is actually the machine-id/system-id from the node's /etc/machine-id file that is supposed to be persistent for the node's install.

**Pull request merged**
