### PR TITLE
fedora: Update OVN to latest version ovn-23.09.0-112.

### PR DESCRIPTION
**Pull request by dceara**
This includes the following relevant changes:
- actions: Use random port selection for SNAT with external_port_range.
  [https://github.com/ovn-org/ovn/commit/7ee483a45df1]
  [https://issues.redhat.com/browse/FDP-301]
  [https://issues.redhat.com/browse/RFE-4980]
- northd: Make sure that affinity flows match on VIP.
  [https://github.com/ovn-org/ovn/commit/859e8d917408]
  [https://issues.redhat.com/browse/FDP-290]
- ovn: Add tunnel PMTUD support.
  [https://github.com/ovn-org/ovn/commit/6d2f9d60760a]
  [https://bugzilla.redhat.com/show_bug.cgi?id=2241711]
- northd: Use proper field for lookup_nd
  [https://github.com/ovn-org/ovn/commit/8e25c1c37aa3]
  [https://issues.redhat.com/browse/FDP-283]
  [https://issues.redhat.com/browse/OCPBUGS-27093]
- northd: Remove the protocol match from ECMP symmetric reply flows.
  [https://github.com/ovn-org/ovn/commit/a36f2955be67]
  [https://issues.redhat.com/browse/FDP-358]
- northd: Explicitly handle SNAT for ICMP need frag.
  [https://github.com/ovn-org/ovn/commit/6a4c412f43d5]
  [https://issues.redhat.com/browse/FDP-159]

### CODE REVIEW

**Comment by dceara** [comment]
CC: @numansiddique @trozet @tssurya @jcaamano

**Comment by tssurya** [comment]
@trozet : remind me, we have a rule for every new OVN feature/fix we need e2e's or some test coverage right? 

1. @trozet Does "OVN SNAT external_port_range" need some specific e2e's or UTs? 
2. "northd: Make sure that affinity flows match on VIP" => @tssurya need's to add an e2e to test ETP=local with Session Affinity set; there is no coverage for that currently.
3. "ovn: Add tunnel PMTUD support" => do we have coverage for this one @jcaamano on our side?
4. https://issues.redhat.com/browse/FDP-283 @trozet will enabling IPV6 lanes upstream catch this and is enough for ICNI or we need new ones?

**Comment by trozet** [comment]
> @trozet : remind me, we have a rule for every new OVN feature/fix we need e2e's or some test coverage right?
> 
> 1. @trozet Does "OVN SNAT external_port_range" need some specific e2e's or UTs?
I cant remember which JIRA this fixes, can you please link?

> 2. "northd: Make sure that affinity flows match on VIP" => @tssurya need's to add an e2e to test ETP=local with Session Affinity set; there is no coverage for that currently.

+1

> 3. "ovn: Add tunnel PMTUD support" => do we have coverage for this one @jcaamano on our side?

@dceara  you need to pull in this commit from me:
https://github.com/ovn-org/ovn-kubernetes/pull/4076/commits/f808ba54d3248d7df6c82ae56d664c3985dd639d

> 4. https://issues.redhat.com/browse/FDP-283 @trozet will enabling IPV6 lanes upstream catch this and is enough for ICNI or we need new ones?

We need to enable ipv6 lanes, and then make sure we have a test case where we modify the mac of the external gateway, simulate it sending a GARP or unsolicited neighbor advertisement, and make sure traffi continues to flow correctly.

> Question is do we open issues for these or do we get the tests in before the bump.. which might slow some things down depending on how urgent each of these bugs are.

Ideally I don't want this to get merged until we have tests in place. I can help with 4, if you need to focus on 2 @tssurya. 3 already has a test, @dceara needs to pull it in here. For number 1, just need more info.

**Comment by trozet** [comment]
Thanks @dceara So for 1, we haven't enabled that behavior in OVNK yet, so we can wait on tests for that until its actually implemented. You added 3. So we need tests for 2 and 4.

**Comment by trozet** [comment]
flake at   [FAIL] Node IP and MAC address migration when the node IPv4 address is updated when ETP=Local service with host network backend is configured [It] makes sure that the flows are updated with new IP address (update kubelet first, the IP address later)
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/node_ip_mac_migration.go:524

https://github.com/ovn-org/ovn-kubernetes/actions/runs/7731553188/job/21080352376?pr=4114

**Comment by trozet** [comment]
created https://github.com/ovn-org/ovn-kubernetes/issues/4119

**Comment by trozet** [comment]
Part of 4 is done, the ipv6 tests now pass for external gw:
https://github.com/ovn-org/ovn-kubernetes/pull/4124/commits/69eb0e77a4271214c6e8469dae61defd14868687

I'll work on a test case that implements the other part of 4.

@tssurya can you give an update on 2 please?

**Comment by tssurya** [comment]
> 
> Let me know if you need me to cherry pick more fixes. The PR has `Maintainers are allowed to edit this pull request. ` set so feel free to add more to it otherwise.
> 
> Thanks!

ack taking you on this offer, I am done with (2) and taking liberty to push this PR here. This e2e will fail at https://github.com/ovn-org/ovn-kubernetes/pull/4141 and must pass here

**Comment by tssurya** [comment]
The test is not passing... we hit:
```

12:53:05.880069 eth0  Out ifindex 135 02:42:ac:17:00:03 ethertype ARP (0x0806), length 48: Ethernet (len 6), IPv4 (len 4), Request who-has 172.23.0.2 tell 172.23.0.3, length 28
12:53:05.880137 eth0  In  ifindex 135 02:42:ac:17:00:02 ethertype ARP (0x0806), length 48: Ethernet (len 6), IPv4 (len 4), Reply 172.23.0.2 is-at 02:42:ac:17:00:02, length 28
12:53:05.880140 eth0  Out ifindex 135 02:42:ac:17:00:03 ethertype IPv4 (0x0800), length 57: (tos 0x0, ttl 64, id 58972, offset 0, flags [DF], proto UDP (17), length 37)
    172.23.0.3.46406 > 192.168.10.0.10001: UDP, length 9
12:53:05.881851 eth0  In  ifindex 135 02:42:ac:17:00:02 ethertype IPv4 (0x0800), length 79: (tos 0x0, ttl 61, id 62686, offset 0, flags [DF], proto UDP (17), length 59)
    192.168.10.0.10001 > 172.23.0.3.46406: UDP, length 31
12:53:05.881863 eth0  Out ifindex 135 02:42:ac:17:00:03 ethertype IPv4 (0x0800), length 107: (tos 0xc0, ttl 64, id 63753, offset 0, flags [none], proto ICMP (1), length 87)
    172.23.0.3 > 192.168.10.0: ICMP 172.23.0.3 udp port 46406 unreachable, length 67
        (tos 0x0, ttl 61, id 62686, offset 0, flags [DF], proto UDP (17), length 59)
    192.168.10.0.10001 > 172.23.0.3.46406: UDP, length 31
12:53:11.199601 eth0  Out ifindex 135 02:42:ac:17:00:03 ethertype IPv4 (0x0800), length 57: (tos 0x0, ttl 64, id 19455, offset 0, flags [DF], proto UDP (17), length 37)
    172.23.0.3.45711 > 192.168.10.0.10001: UDP, length 9
12:53:11.207340 eth0  In  ifindex 135 02:42:ac:17:00:02 ethertype ARP (0x0806), length 48: Ethernet (len 6), IPv4 (len 4), Request who-has 172.23.0.3 tell 172.23.0.2, length 28
12:53:11.207346 eth0  Out ifindex 135 02:42:ac:17:00:03 ethertype ARP (0x0806), length 48: Ethernet (len 6), IPv4 (len 4), Reply 172.23.0.3 is-at 02:42:ac:17:00:03, length 28
12:53:11.269369 eth0  Out ifindex 135 02:42:ac:17:00:03 ethertype IPv4 (0x0800), length 57: (tos 0x0, ttl 64, id 31159, offset 0, flags [DF], proto UDP (17), length 37)
    172.23.0.3.37212 > 192.168.10.0.10001: UDP, length 9
```
I think this is related to netcat somehow? When I pin the source port it passes but I am unsure if session affinity will actually kick in like that... Let's see next week

**Comment by tssurya** [comment]
ah wait disregard the previous comment.. ROFL, IT's some funny thing OVN does since it drops the packet, I need to give it some time after the drop for the learn flows to be installed before retrying..

**Comment by dceara** [comment]
> /assign @trozet : let's merge this?

We need [ovn23.09-112](https://src.fedoraproject.org/rpms/ovn/pull-request/4) (for the ecmp symmetric reply fix for ipv6) first.  I'll update this PR as soon as the new fedora build is available.

**Comment by dceara** [comment]
I updated the bump so it picks up -112.  I also cherry picked @trozet's commits from #4124

**Comment by trozet** [comment]
I added an extra e2e test to cover MAC changing on an external gateway. I'm seeing some interesting behavior where packets with the same 5 tuple seem to end up at different gateways. We need to figure this out and include that test case before we merge this PR imo.

Example job:
https://github.com/ovn-org/ovn-kubernetes/actions/runs/7878265490/job/21496888471?pr=4124

commit with new test case:
https://github.com/ovn-org/ovn-kubernetes/pull/4124/commits/66d7d208b0c8271eb9731e3a1b6f745d0067871f

**Comment by dceara** [comment]
> I added an extra e2e test to cover MAC changing on an external gateway. I'm seeing some interesting behavior where packets with the same 5 tuple seem to end up at different gateways. We need to figure this out and include that test case before we merge this PR imo.
> 
> Example job: https://github.com/ovn-org/ovn-kubernetes/actions/runs/7878265490/job/21496888471?pr=4124
> 
> commit with new test case: [66d7d20](https://github.com/ovn-org/ovn-kubernetes/commit/66d7d208b0c8271eb9731e3a1b6f745d0067871f)

From the linked job's e2e DBs, I can see that in the OVS database we have:
`Datapath.capabilities.max_hash_alg = 0`.

That means the algorithm selected for hashing is `OVS_HASH_ALG_L4`:
```
/* Data path hash algorithm for computing Datapath hash.
 *
 * The algorithm type only specifies the fields in a flow
 * will be used as part of the hash. Each datapath is free
 * to use its own hash algorithm. The hash value will be
 * opaque to the user space daemon.
 */
enum ovs_hash_alg {
	OVS_HASH_ALG_L4,
#ifndef __KERNEL__
	OVS_HASH_ALG_SYM_L4,
#endif
	__OVS_HASH_MAX
};
```

Which is known to not be a canonical 5-tuple hash.  It actually uses a random value associated to new TCP sockets and, even worse, changes when retransmissions happen.

This means the kernel this test is running on doesn't have [the following commit](https://github.com/torvalds/linux/commit/e069ba07e6c7af69e119316bc87ff44869095f49):
```
 net: openvswitch: add support for l4 symmetric hashing

Since its introduction, the ovs module execute_hash action allowed
hash algorithms other than the skb->l4_hash to be used.  However,
additional hash algorithms were not implemented.  This means flows
requiring different hash distributions weren't able to use the
kernel datapath.

Now, introduce support for symmetric hashing algorithm as an
alternative hash supported by the ovs module using the flow
dissector.

Output of flow using l4_sym hash:

    recirc_id(0),in_port(3),eth(),eth_type(0x0800),
    ipv4(dst=64.0.0.0/192.0.0.0,proto=6,frag=no), packets:30473425,
    bytes:45902883702, used:0.000s, flags:SP.,
    actions:hash(sym_l4(0)),recirc(0xd)

Some performance testing with no GRO/GSO, two veths, single flow:

    hash(l4(0)):      4.35 GBits/s
    hash(l4_sym(0)):  4.24 GBits/s

Signed-off-by: Aaron Conole <aconole@redhat.com>
Signed-off-by: David S. Miller <davem@davemloft.net
```

So, IMO, either runners should be upgraded to use a newer kernel or we should skip this test or make it account for the lack of 5-tuple canonical hashing in the kernel datapath.

**Comment by tssurya** [comment]
@dceara @LorenzoBianconi : does this bump have https://github.com/ovn-org/ovn/commit/57e5e2b2be249a7de6ead350a241fa537f392192 as well?

**Comment by trozet** [comment]
ok I think the test case is ready to be pulled in: https://github.com/ovn-org/ovn-kubernetes/pull/4124/commits/42dc46df0b174a1b44f2aaba9e29cf5c9ff5b304

**Comment by dceara** [comment]
`ovn-ci / e2e (kv-live-migration, noHA, shared, dualstack, SnatGW, 1br, ic-single-node-zones, 3)` CI failure due to https://github.com/ovn-org/ovn-kubernetes/issues/3986

Retesting.

**Review by trozet — APPROVED** [review]

**Pull request merged**
