### PR TITLE
Update hardware offloads to hardware acceleration

### PR DESCRIPTION
**Pull request by hareeshpc**

### CODE REVIEW

**Comment by hareeshpc** [comment]
@tssurya

**Comment by hareeshpc** [comment]
// @tssurya

**Review by tssurya — CHANGES_REQUESTED** [review]
@hareeshpc : can we remove the nvidia links in this FUP?
otherwise change lgtm

**Comment by hareeshpc** [comment]
> @hareeshpc : can we remove the nvidia links in this FUP? ([#4408 (review)](https://github.com/ovn-org/ovn-kubernetes/pull/4408#pullrequestreview-2101219891) we had a FUP item action there for this) otherwise change lgtm

Thanks. Done
FYI, I had also removed the empty "Support DPU Acceleration" section till we submit some content for it.

**Review by tssurya — APPROVED** [review]

**Pull request merged**
