### PR TITLE
Enable ipv6 for e2e control-plane shard

### PR DESCRIPTION
**Pull request by jluhrsen**
Signed-off-by: Jamo Luhrsen <jluhrsen@gmail.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by jluhrsen** [comment]
/hold

need to investigate failures in the v6 jobs this PR enables

**Comment by aojea** [comment]
:clap: :heart:

**Review by vpickard — COMMENTED** [review]
Thanks Jamo!

Will there be a separate PR for dualstack control-plane?

**Comment by jluhrsen** [comment]
> Thanks Jamo!
> 
> Will there be a separate PR for dualstack control-plane?

yeah, I'll try to get this working first and we can merge it and I'll move on to dual stack. I did file a separate jira for it.

**Comment by trozet** [comment]
So there are a bunch of failures here, which is probably because the e2e tests assumed ipv4. What is the plan? @jluhrsen are you going to fix them in this PR? I see one failure is:

[Fail] e2e multiple ecmp external gateway validation [BeforeEach] Should validate connectivity to multiple external gateways for an ECMP scenario IPV4 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/e2e.go:1443

So maybe we are not ignoring tests that are ipv4 only as well.

**Comment by jluhrsen** [comment]
> So there are a bunch of failures here, which is probably because the e2e tests assumed ipv4. What is the plan? @jluhrsen are you going to fix them in this PR? I see one failure is:
> 
> [Fail] e2e multiple ecmp external gateway validation [BeforeEach] Should validate connectivity to multiple external gateways for an ECMP scenario IPV4
> /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/e2e.go:1443
> 
> So maybe we are not ignoring tests that are ipv4 only as well.

yes, I will try to address all the different reasons for the failures in this PR. I got busy looking at some other things
this week, but hoping to get back to this asap.

**Comment by jluhrsen** [comment]
@aojea , is there a way to stop builds/CI from running on a PR while I work on it in my own repo? I thought /hold would do that, but I just rebased and force pushed and I see that this PR got updated and looks like CI triggered. it's just a waste of resources at this point.

**Comment by aojea** [comment]
> @aojea , is there a way to stop builds/CI from running on a PR while I work on it in my own repo? I thought /hold would do that, but I just rebased and force pushed and I see that this PR got updated and looks like CI triggered. it's just a waste of resources at this point.

I think that the problem is how github works, once you create the PR to the main repo, any update in your fork will update the PR.
the /hold thing works with prow and kubernetes/opwnshift ci.

Just close the PR , work in your fork, and reopen or create a new one, does that work?

**Comment by jluhrsen** [comment]
> > @aojea , is there a way to stop builds/CI from running on a PR while I work on it in my own repo? I thought /hold would do that, but I just rebased and force pushed and I see that this PR got updated and looks like CI triggered. it's just a waste of resources at this point.
> 
> I think that the problem is how github works, once you create the PR to the main repo, any update in your fork will update the PR.
> the /hold thing works with prow and kubernetes/opwnshift ci.
> 
> Just close the PR , work in your fork, and reopen or create a new one, does that work?

yes, that makes sense. will do it that way. thanks.

**Pull request closed without merging**
