### PR TITLE
Upgrade cache action to v2

### PR DESCRIPTION
**Pull request by as-com**
Signed-off-by: Andrew Sun <asun@redhat.com>

This should make caching go a little faster and consume less space. See: https://github.com/actions/cache/releases/tag/v2.0.0

### CODE REVIEW

**Comment by dcbw** [comment]
works for me assuming it passes CI. One question; have they fixed the cache failures on re-run that we merged https://github.com/ovn-org/ovn-kubernetes/pull/1259 to work around?

**Comment by as-com** [comment]
@dcbw https://github.com/actions/cache/issues/208#issuecomment-630896455
Seems it was an issue with GitHub itself and it was recently fixed.

**Pull request merged**
