### PR TITLE
vendor: update libovsdb

### PR DESCRIPTION
**Pull request by stbenjam**
**- What this PR does and why is it needed**

The current version of libovsdb has a parsing error when handling IPv6
addresses, that was fixed in eBay/libovsdb#20.

Error I'm getting from ovn-kubernetes:

```
ovnkube.go:130] error when trying to initialize go-ovn NB client:
couldn't initialize NBDB client: error creating SSL OVNDBClient for
database OVN_Northbound at address ssl:[fd2e:6f44:5dd8:c956::14]:9641,
ssl:[fd2e:6f44:5dd8:c956::15]:9641,ssl:[fd2e:6f44:5dd8:c956::16]:9641:
failed to connect: dial tcp: address [fd2e:6f44: missing ']' in
address\n
```

Commands run:
 - go get -u github.com/ebay/libovsdb@3332afaeb27c0df7184e92c921e9bf19a4d19a93
 - go mod vendor
 - go mod tidy

**- Special notes for reviewers**

**- How to verify it**

Use IPv6.

**- Description for the changelog**

Revendored libovsdb to fix a parsing error with IPv6 addresses.

### CODE REVIEW

**Comment by stbenjam** [comment]
https://github.com/ovn-org/ovn-kubernetes/pull/1343 already pulls in the patch, but wasn't sure how long it'd be until that lands

**Comment by Billy99** [comment]
FYI - PR  #1343 should merge soon and has this in one of the commits associated with the PR.

**Comment by stbenjam** [comment]
> FYI - PR #1343 should merge soon and has this in one of the commits associated with the PR.

Yup, I saw, thanks! I just wasn't sure how far away it was from merging. 

I got bitten by this in OpenShift since ovn got rebased ovn-kubernetes and pulled in the libovsdb bug and broke my platform.

**Comment by stbenjam** [comment]
#1343 merged, thanks!!

/close

**Pull request closed without merging**
