### PR TITLE
syncNodesPeriodic: get nodes from cache

### PR DESCRIPTION
**Pull request by npinaeva**
Use nodeName lists for syncChassis to make sure
cache objects are not modified.

delete dead code from util/ovs, init() had impact on performance
without being used by anyone
Closes https://github.com/ovn-org/ovn-kubernetes/issues/3682

Commits are unrelated, they are a part of the memory optimization effort, and since they are small enough I decided to group them together.

### CODE REVIEW

**Review by jcaamano — APPROVED** [review]
I am questioning myself why we need syncNodesPeriodic.

Also, both commits seem completly unrelated unless I am missing something.

**Comment by jcaamano** [comment]
re-running failed jobs

**Comment by npinaeva** [comment]
@jcaamano you are right the commits are unrelated, they were the result of a memory optimization process, and both are quite simple and small, so I joined them. If you think it is better to split them, I can do that

**Comment by jcaamano** [comment]
> @jcaamano you are right the commits are unrelated, they were the result of a memory optimization process, and both are quite simple and small, so I joined them. If you think it is better to split them, I can do that

No need, just checking!

**Review by trozet — APPROVED** [review]

**Review by trozet — APPROVED** [review]

**Pull request merged**
