### PR TITLE
Fixes shared gateway mode checks

### PR DESCRIPTION
**Pull request by trozet**
The current code for detecting the NIC with shared gateway mode assumes
the naming format of the bridge is "br-<nic name>". This is not always
the case an a typical OVS bridge will use the same name for the OVS port
and interface as the brdige. This patch handles that use case.

Additionally, checks for ofport were using "--if-exists" which will not
return an error if the ofport does not exist for that port.

Signed-off-by: Tim Rozet <trozet@redhat.com>

### CODE REVIEW

**Comment by trozet** [comment]
@girishmg

**Comment by trozet** [comment]
I just realized this patch is wrong. The logic is trying to find the physical port not the OVS port.

**Comment by girishmg** [comment]
@trozet /lgtm

**Comment by trozet** [comment]
This works downstream for me in OpenShift. Test cases seem to freeze up, not sure why yet.

**Comment by trozet** [comment]
not sure what this is about:

Executed commands do not match expected commands!
[00] ! /fake-bin/ovn-nbctl --timeout=15 --data=bare --no-heading --columns=_uuid find ACL match="ip4.src == {$a4417941599443114881} && outport == @pg-name" external-ids:namespace=testing external-ids:policy=policy external-ids:Ingress_num=0 external-ids:policy_type=Ingress
[01] ! /fake-bin/ovn-nbctl --timeout=15 set acl 94407fe0-2c15-4a63-baea-ab4af0ea5bb8 match="ip4.src == {$a4417941599443114881, $a7467980285203883600} && outport == @pg-name"
FAIL	github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn	3.983s
FAIL

**Comment by danwinship** [comment]
> not sure what this is about:

I saw that recently and then it went away in a retest. I think there's a race condition

**Comment by trozet** [comment]
> > not sure what this is about:
> 
> I saw that recently and then it went away in a retest. I think there's a race condition

Filed https://github.com/ovn-org/ovn-kubernetes/issues/1543

**Pull request merged**
