### PR TITLE
update the linter used for local testing so it matches the ci version

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by trozet** [comment]
already merged via https://github.com/ovn-org/ovn-kubernetes/pull/2889

**Comment by trozet** [comment]
nvm...

**Comment by tssurya** [comment]
/lgtm
unit test failing might get fixed due to https://github.com/ovn-org/ovn-kubernetes/pull/2887

**Comment by tssurya** [comment]
@JacobTanenbaum : wanna update this to include your sign-off?

**Comment by JacobTanenbaum** [comment]
@tssurya sorry, was moving to fast updated with sign-off

**Review by tssurya — APPROVED** [review]

**Pull request merged**
