### PR TITLE
WIP install prometheus in kind

### PR DESCRIPTION
**Pull request by aojea**
it allows to get metrics from the different components, very
useful for micro-bench markings and to get baselines.

Signed-off-by: Antonio Ojea <aojea@redhat.com>

### CODE REVIEW

**Comment by aojea** [comment]
I still have to figure out the ovn/ovs metrics, @girishmg you mentioned some time ago that you had some dashboards, did you get to publish them?

**Comment by alexanderConstantinescu** [comment]
FWIW: I already have a PR for this: https://github.com/ovn-org/ovn-kubernetes/pull/1885

**Comment by aojea** [comment]
> FWIW: I already have a PR for this: #1885

I didn't know, however, I looked at that project and is not excessive for this?
We only want a few metrics, the cluster topology is always the same ... that prometheus operator seems overcomplicated to me... and we are very resource constrained in the CI

**Comment by alexanderConstantinescu** [comment]
> We only want a few metrics, the cluster topology is always the same ... 

I found benefit in deploying kube-state-metrics and seeing what metrics are delivered with standard Kubernetes, so that we don't duplicate the work in our component. There are a bunch of metrics for services/endpoints/etc already delivered there. 

> that prometheus operator seems overcomplicated to me...

I think prometheus operator is beneficial because they know what they are doing and have already done the work for us. I would like to avoid writing all the yamls and deployment stanzas when someone already has done so and officially supports it. 

>  and we are very resource constrained in the CI

My PR was not intended to be run in CI, and from the looks of it: neither is yours (the deployment defaults to false). I don't think we should run it in Kind CI either.

**Pull request closed without merging**
