### PR TITLE
Reduce logging while waiting for gateway and management port

### PR DESCRIPTION
**Pull request by pecameron**
sdn-735 [ovn] less confusing gateway and management port wait messages
https://issues.redhat.com/browse/SDN-735

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@dcbw PTAL

**Comment by russellb** [comment]
thanks for doing this :)

**Comment by dcbw** [comment]
@girishmg look OK?

**Comment by girishmg** [comment]
@dcbw LGTM.

I think we need to fix these Ready function to not perform ovn-nbctl calls.. We should use some node annotation to check if the ovnkube-node can proceed

**Pull request merged**
