### PR TITLE
removing the hybrid overlay externalGW code

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
as there is now code to implement external gateway outside of
hybrid-overlay I am removing the external gateway code inside of the
hybrid-overlay

Signed-off-by: Jacob Tanenbaum <jtanenba@redhat.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
I am not fully sure I understand why this is being removed.

> as there is now code to implement external gateway outside of hybrid-overlay I am removing the external gateway code inside of the hybrid-overlay

Could you expand on that? I am not very aware of what has happened before and the back-ground to this PR.

**Comment by JacobTanenbaum** [comment]
we would prefer to use https://github.com/ovn-org/ovn-kubernetes/pull/1508 over the hybrid overlay external GW

**Review by trozet — APPROVED** [review]

**Pull request merged**
