### PR TITLE
ovn-dbchecker: upgrade DB schema

### PR DESCRIPTION
**Pull request by trozet**
Adds support for upgrading db schema in HA and noHA deployments.

### CODE REVIEW

**Comment by trozet** [comment]
@girishmg @dceara

**Comment by dceara** [comment]
Turns out there's no need to do the schema upgrade from within the ovn-dbchecker if the deployment is standalone.  ovn-ctl [will take care of it.](https://github.com/ovn-org/ovn/blob/fd8b0170b833553768849505a9793cd90babfb79/utilities/ovn-ctl#L225)

**Comment by trozet** [comment]
Tested upgrade with HA cluster and it worked:
First upgraded node:
```
=============== ovn-dbchecker (wait for sb-ovsdb) ========== OVNKUBE_DB
=============== ovn-dbchecker ========== OVNKUBE_DB
I1206 20:22:15.919212      37 ovs.go:95] Maximum command line arguments set to: 191102
I1206 20:22:15.927257      37 ovndbmanager.go:43] Starting DB Checker to ensure cluster membership and DB consistency
I1206 20:22:16.020742      37 ovndbmanager.go:435] OVN_Northbound DB schema successfully upgraded from: "5.32.1", to "5.34.1"
I1206 20:22:16.020771      37 ovndbmanager.go:70] Starting ensure routine for Raft db: /etc/ovn/ovnnb_db.db
I1206 20:22:16.053773      37 ovndbmanager.go:435] OVN_Southbound DB schema successfully upgraded from: "20.20.0", to "20.21.0"
I1206 20:22:16.053806      37 ovndbmanager.go:70] Starting ensure routine for Raft db: /etc/ovn/ovnsb_db.db
```

2nd and 3rd node: 
```
I1206 20:24:15.068891      37 ovs.go:95] Maximum command line arguments set to: 191102
I1206 20:24:15.075784      37 ovndbmanager.go:43] Starting DB Checker to ensure cluster membership and DB consistency
I1206 20:24:15.101666      37 ovndbmanager.go:425] No OVN_Southbound DB schema upgrade is required. Current version: 20.21.0, target: 20.21.0
I1206 20:24:15.101695      37 ovndbmanager.go:70] Starting ensure routine for Raft db: /etc/ovn/ovnsb_db.db
I1206 20:24:15.101720      37 ovndbmanager.go:425] No OVN_Northbound DB schema upgrade is required. Current version: 5.34.1, target: 5.34.1
I1206 20:24:15.101729      37 ovndbmanager.go:70] Starting ensure routine for Raft db: /etc/ovn/ovnnb_db.db
```

**Comment by dceara** [comment]
LGTM, thanks!

**Pull request merged**
