### PR TITLE
Refactoring bash scripts in cluster-network-operator/../ovnkube-master.yaml 

### PR DESCRIPTION
**Pull request by sdsen**
- **What this PR does and why is it needed**
This pull request refactors the bash scripts present in cluster-network-operator/../ovnkube-master.yaml. The goal being separation of YAML and bash script into separate files.
- **Special notes for reviewers**

- **How to verify it**
The verification of correct working of the script will happen when Cluster-Network-Operator invokes it inside ovnkube-master.yaml. The specific instructions to check the same, are provided in the relevant CNO pull request.

Co-authored by : Palani Kodeswaran palani.kodeswaran@in.ibm.com

Signed-off-by: Sayandeep <sayandes@in.ibm.com>

### CODE REVIEW

**Comment by abhat** [comment]
@sdsen, @palanik1 - looks like there are some merge conflicts in your uploaded changes, can you please resolve the conflicts and push again? Also, please include a description for the PR as per the template.

**Comment by dcbw** [comment]
Are we sure the bash scripts here are synced with current CNO scripts? Some IPsec stuff landed recently...

**Comment by alexanderConstantinescu** [comment]
Question: is there a reason this patch is targeting upstream, when it's clearly an OpenShift specific change?

**Comment by palanik1** [comment]
@alexanderConstantinescu We are modifying the OVN-K dockerfile to include copy our bash script into the image, and hence the PR to upstream. Let us know if this makes sense.

**Comment by palanik1** [comment]
@dcbw I believe the ipsec CNO yaml  starts two new containers and does not affect existing containers. Will take a look.

**Comment by palanik1** [comment]
@dcbw Thoughts?

**Pull request closed without merging**
