### PR TITLE
E2E: fix tests stuck waiting on a channel

### PR DESCRIPTION
**Pull request by oribon**
These tests run checkContinuousConnectivity in a goroutine and wait on the podChan to continue. The problem is that if the goroutine fails to create a pod it sends a msg to the errChan and exits, making the test hang indefinitely until the global timeout kicks in (3hrs).
Fixing checkContinuousConnectivity to send a nil to the errChan if the pod was created successfully, and the callers to wait for that nil before trying to get the pod.

Signed-off-by: Ori Braunshtein <obraunsh@redhat.com>

https://github.com/ovn-org/ovn-kubernetes/runs/8228933899?check_suite_focus=true

### CODE REVIEW

**Comment by npinaeva** [comment]
I would say that the fact that `checkContinuousConnectivity` may send connectivity error and pod creation error the same way, but it should be handled differently is a bit ugly, so wdyt if we split it into create pod and connectivity check functions, because every caller waits for pod to be created first anyway.
So it can create pod without new goroutine, then if it was created successfully, start connectivity checks with single error channel.

**Comment by npinaeva** [comment]
Let's add some comments to `checkContinuousConnectivity` for the future generations, saying what we expect to get on those channels, like that you will get error first, if it is not nil, then you should get pod too, then next error will be about connectivity, wdyt?

**Comment by oribon** [comment]
> I would say that the fact that `checkContinuousConnectivity` may send connectivity error and pod creation error the same way, but it should be handled differently is a bit ugly, so wdyt if we split it into create pod and connectivity check functions, because every caller waits for pod to be created first anyway. So it can create pod without new goroutine, then if it was created successfully, start connectivity checks with single error channel. EDIT: probably doesn't worth it, just some clear comments on what to expect should be enough

I agree that it is a bit ugly but in the same time I chose this small fix because I did not want to invest too much time in fixing/refactoring as this channel approach shows up in more places in these tests.


> Let's add some comments to `checkContinuousConnectivity` for the future generations, saying what we expect to get on those channels, like that you will get error first, if it is not nil, then you should get pod too, then next error will be about connectivity, wdyt?

good idea, added and also mentioned that this approach might be sub-optimal and could be refactored

**Comment by npinaeva** [comment]
/lgtm
one more bug is fixed, great work!

**Review by trozet — APPROVED** [review]

**Pull request merged**
