### PR TITLE
Update to urfave/cli/v2 and implement signal handling

### PR DESCRIPTION
**Pull request by dave-tucker**
This PR updates the dependency on urfave/cli to v2 which allows for a context to the be passed to the cli commands.

I then implemented a signal handler which will close this context in response to `SIGTERM`, `SIGHUP`, `SIGQUIT` and `SIGINT` signals. This will then trigger the `stopCh` that is shared by controller components to be closed and should allow for graceful shutdown.

I'm not aware of this causing any issues today, but it would be better to give the process a chance to exit gracefully to avoid being interrupted writing data to disk or transferring commands over a socket etc...

The context will also be useful if/when we migrate to the latest `client-go` package.

### CODE REVIEW

**Comment by trozet** [comment]
ingress test failed with: 
   Message: "clusterrolebindings.rbac.authorization.k8s.io \"ingress-4146--cluster-admin\" already exists",

I wonder if this ingress is getting created by the test and randomly conflicting with the ingress we create? Or something in the tests is not cleaning up correctly? Need to look into it later.

**Comment by dave-tucker** [comment]
@trozet PTAL. I've added the signal handling stuff here too as it's only a few extra lines of code.
Also makes this into more of a feature vs. busywork PR :wink:

**Comment by trozet** [comment]
@girishmg @dcbw @danwinship PTAL

**Comment by girishmg** [comment]
@dave-tucker we do some signal handling here as well

```
func setupPIDFile(pidfile string) error {
	c := make(chan os.Signal, 2)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	go func() {
		<-c
		delPidfile(pidfile)
		os.Exit(1)
	}()
```

is it possible to merge these things into one?

**Comment by dave-tucker** [comment]
Good catch @girishmg.
I've removed the signal handling logic from the `setupPidFile` function.
The call to `deletePidFile` is `defer`'ed just before the call to `setupPidFile` so there is no need for it to be duplicated.
The `runOvn` function waits for the context to be closed (i.e on receipt of a signal) and then the defered function will execute and the file will be deleted.

**Pull request merged**
