### PR TITLE
[libovsdb] Replace UUID for referential fields

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
This PR implements a UUID replacement mechanism for referential fields. During unit tests: libovsdb will generate UUIDs for referential fields. We cannot know these before running the tests, so we'll need to have a mechanism that replaces them once the test results are evaluated. This will allow one to write tests such as:

```go
		expectedDatabaseState := &nbdb.LogicalRouter{
			UUID:         "GR_test-node-UUID",
			Name:         "GR_test-node",
			LoadBalancer: []string{"lb1", "lb2"}, <--- referential fields
			Options: map[string]string{
				"lb_force_snat_ip":              "router_ip",
				"snat-ct-zone":                  "0",
				"always_learn_from_arp_request": "false",
				"dynamic_neigh_routers":         "true",
				"chassis":                       "SYSTEM-ID",
			},
			ExternalIDs: map[string]string{
				"physical_ip":  "169.254.33.2",
				"physical_ips": "169.254.33.2",
			},
			Ports:        []string{"port1", "port2"}, <--- referential fields
			StaticRoutes: []string{"route1", "route2"}, <--- referential fields
		}

		gomega.Eventually(libovsdbOvnNBClient).Should(libovsdbtest.HaveData(expectedDatabaseState))
```

the only gotcha on the developer's side is to have a unique named UUID value for all expected referential UUIDs.

I thought https://github.com/ovn-org/ovn-kubernetes/pull/2369 would implement this, but it didn't work for me (except for the actual `UUID` field), so maybe I did something wrong with my test setup?

/assign @jcaamano 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by jcaamano** [comment]
@alexanderConstantinescu named UUIDs just work as named UUIDs, you need to define in the database state the actual things you are referencing to. So define the loadbalancers lb1 lb2 etc. 

Look at https://github.com/jcaamano/ovn-kubernetes/blob/3f7c4fd9e8b8d46b784c897b16041b67ae5545da/go-controller/pkg/ovn/policy_test.go#L111 as reference

There we define a expected database state where portgroups have references to ACLs via named uuids and the ACLs are as well in the expected database state. So we actually need to check that things are pointing to where they should.

**Comment by jcaamano** [comment]
By the way, you can define the expected DB state of your example and use it with `HaveDataIgnoringUUIDs`, the length of the referential fields will still be checked to match. But I think that you need to define what you are referencing to properly test.

**Comment by jcaamano** [comment]
To be clear, to define a named UUID in the tests you need to use a non empty string (preferably somehitng that is not actually a UUID to avoid confusion) in the UUID field of a model. So in your example there, `lb1` is not a named UUID because you are not actually using it as a UUID in any model of your expected database state.

**Comment by alexanderConstantinescu** [comment]
Yes, you're right. I think I got confused because the functions I am testing (`gatewayInit`) are setting half of the things up using `ovn-nbctl` and the other half with libovsdb. Thanks for the pointers!

**Pull request closed without merging**
