### PR TITLE
Adds back checking OF flows for CNI

### PR DESCRIPTION
**Pull request by trozet**
We see at scale that this can happen:
1. CNI delete
2. OVN is so busy it takes 30 seconds to remove the old logical port
3. CNI ADD within 30 seconds
4. ovn-controller sees old logical switchport, binds and considers new
   pod up, but no traffic works
5. sometime later OVN gets updated, and ovn-controller updates the pod
   with the new flows and traffic finally works

To solve this problem we need to have a minimal check to ensure the
right flows are present for the pod before we check if ovn_installed is
true. This change adds back the checks for mac address and of port
number.

Signed-off-by: Tim Rozet <trozet@redhat.com>

### CODE REVIEW

**Comment by trozet** [comment]
@dceara

**Comment by dceara** [comment]
@trozet The change makes sense given the description in your commit message (I didn't review the specifics though).  However, I wonder if it would help to not reuse old logical switch ports names and instead add a unique suffix to the LSP name (e.g., a monotonically increasing seqno).  Not sure if that's easy to implement but it would save some `ovs-ofctl dump-flows` runs.

**Comment by trozet** [comment]
rebased

**Pull request merged**
