### PR TITLE
Added unit test for RunOVSDBTool()

### PR DESCRIPTION
**Pull request by anfredette**
Signed-off-by: Andre Fredette <afredette@redhat.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by anfredette** [comment]
@trozet @vjayaramrh @sheetalsingala @JacobTanenbaum FYI, please review. Thanks, Andre

**Comment by sheetalsingala** [comment]
LGTM

**Comment by anfredette** [comment]
FYI, I amended my commit to fix a comment. All else is the same.

**Review by trozet — APPROVED** [review]

**Pull request merged**
