### PR TITLE
Delete per pod nat when adding gw routes to namespace

### PR DESCRIPTION
**Pull request by fedepaol**
**- What this PR does and why is it needed**

When a gw pod gets the external gateway annotation, it adds the specific
routes to the external gateway for existing pods, but it does not remove
the SNAT that was added when the pod was created.

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm

**Review by trozet — CHANGES_REQUESTED** [review]
with the job names, its hard to decipher which one has disable snat or not.. can we fix this?
ovn-ci / e2e (control-plane, true, true, true, true, HA, true, shared, ipv4, IPv4, true, false)

**Comment by fedepaol** [comment]
> with the job names, its hard to decipher which one has disable snat or not.. can we fix this?
> ovn-ci / e2e (control-plane, true, true, true, true, HA, true, shared, ipv4, IPv4, true, false)

Updated, let's see if I broke it :-)

**Comment by fedepaol** [comment]
@trozet looks better!

**Review by trozet — APPROVED** [review]
nice thanks!

**Pull request merged**
