### PR TITLE
fedora: Update OVN to 23.06.0-0.

### PR DESCRIPTION
**Pull request by numansiddique**
OVN 23.06.0 was released on 2023-06-02.

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by tssurya** [comment]
@jordigilh : we are having flakes in UTs:https://github.com/ovn-org/ovn-kubernetes/actions/runs/5164604041/jobs/9303613408?pr=3639 around the new Admin Policy Route feature: PTAL

**Review by tssurya — APPROVED** [review]
/lgtm

**Comment by tssurya** [comment]
thanks @numansiddique 
@qinqon: This should bring in the OVN changes that you wanted :)

**Comment by qinqon** [comment]
> thanks @numansiddique @qinqon: This should bring in the OVN changes that you wanted :)

Thanks !

**Pull request merged**
