### PR TITLE
Revert "Skip kube proxy connection reset test"

### PR DESCRIPTION
**Pull request by aojea**
This reverts commit 24f2e9e40b5d216e0ece0fc5fed8a7e3507c926b.

### CODE REVIEW

**Comment by abhat** [comment]
LGTM.

**Comment by aojea** [comment]
https://github.com/ovn-org/ovn-kubernetes/runs/1043462174?check_suite_focus=true

we have to investigate it, all test timed out

**Comment by aojea** [comment]
> https://github.com/ovn-org/ovn-kubernetes/runs/1043462174?check_suite_focus=true
> 
> we have to investigate it, all test timed out

and with a familar error @trozet 

> result "", err failed to configure pod interface: timed out waiting for pod flows for p
od: dns-test-7d643b8c-d154-46dc-9d72-c8497856ec01, error: timed out waiting for the condition

**Comment by trozet** [comment]
@aojea I never see ovn-controller on control-plane-3 bind the port for dns-test-7d643b8c-d154-46dc-9d72-c8497856ec01. Tells me either its an OVN problem or a ebay/go bindings problem. It would be nice if we could enable some logging on northd to see when ports are created. The northd log is pretty useless right now.

**Comment by aojea** [comment]
it happened again in the same job
https://github.com/ovn-org/ovn-kubernetes/pull/1644/checks?check_run_id=1050444902
:thinking:

**Comment by aojea** [comment]
another occurrence https://github.com/ovn-org/ovn-kubernetes/pull/1640, same job timing out because the tests are timing out in another PR
https://github.com/ovn-org/ovn-kubernetes/pull/1640/checks?check_run_id=1050665833

**Pull request merged**
