### PR TITLE
make svc_template_support configurable, default is enabled

### PR DESCRIPTION
**Pull request by cathy-zhou**
**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by tssurya** [comment]
Is there a reason why we don't want to use LB Templates?

**Comment by girishmg** [comment]
> Is there a reason why we don't want to use LB Templates?

There are several issues we found downstream. @cathy-zhou  can you please raise issues for:
1. Performance regression while using service templates.
2. If a K8s nodes have different set of IP addresses, then the template doesn't work as expected. The ovn-controller on nodes with lesser number of IPs  will interpret the template variable as a 'raw string' and spews out lot of errors.

**Comment by cathy-zhou** [comment]
> > Is there a reason why we don't want to use LB Templates?
> 
> There are several issues we found downstream. @cathy-zhou can you please raise issues for:
> 
> 1. Performance regression while using service templates.
> 2. If a K8s nodes have different set of IP addresses, then the template doesn't work as expected. The ovn-controller on nodes with lesser number of IPs  will interpret the template variable as a 'raw string' and spews out lot of errors.

Fro 2, I just filed https://github.com/ovn-org/ovn-kubernetes/issues/4301. We are still investigating the performance issue and will file one once we know more.

**Comment by girishmg** [comment]
@cathy-zhou can you please rebase?

**Review by flavio-fernandes — CHANGES_REQUESTED** [review]
@cathy-zhou Please also add this to https://github.com/ovn-org/ovn-kubernetes/blob/master/helm/ovn-kubernetes/values.yaml so helm can benefit from it.

**Comment by cathy-zhou** [comment]
> 1. Performance regression while using service templates.
@hzhou8 do you have corresponding issue filed for the offloading performance issue when svc_template is enabled? if so, can you post the link to it?

**Comment by cathy-zhou** [comment]
>  Please also add this to https://github.com/ovn-org/ovn-kubernetes/blob/master/helm/ovn-kubernetes/values.yaml so helm can benefit from it.
@flavio-fernandes please take a look

**Review by girishmg — APPROVED** [review]
LGTM

**Comment by hzhou8** [comment]
> > 1. Performance regression while using service templates.
> >    @hzhou8 do you have corresponding issue filed for the offloading performance issue when svc_template is enabled? if so, can you post the link to it?

I don't have an issue reported yet, but here are the details:

When LB template is enabled, a priority 120 flow is missing in the UNSNAT stage that skips the UNSNAT for LB VIPs that are also used as SNAT IP. The flow was added by: [832893bdbb42](https://github.com/ovn-org/ovn/commit/832893bdbb42fd121f0b8de90514e27a20356507) ("ovn-northd: Skip unsnat flows for load balancer vips in router ingress pipeline")

The LB template implementation in OVN didn't handle this properly, and the flow is missing if template is used. (It is actually difficult to handle with template, so this can be a limitation of LB template) - Because of this missing flow, traffic to node-port is not offloaded, and performance drops significantly. But this is only for our downstream environment. The full story is more complex:

The above commit [832893bdbb42](https://github.com/ovn-org/ovn/commit/832893bdbb42fd121f0b8de90514e27a20356507) itself has a [problem](https://issues.redhat.com/browse/FDP-291), and this priority-120 flow is again removed by a bug fix:
[ffe267317c25](https://github.com/ovn-org/ovn/commit/ffe267317c252b1aac864b6d18c89beebd4d3846) ("northd: Don't skip the unSNAT stage for traffic towards VIPs.") This bug fix is also backported to 23.06 but not to our downstream branch yet.

So, enabling LB template resulted in HW offload problem in our downstream where the above bug fix doesn't exist, and disabling LB template restores the HW offload. However, for current upstream branches with the above fix [ffe267317c25](https://github.com/ovn-org/ovn/commit/ffe267317c252b1aac864b6d18c89beebd4d3846), it is very likely that the HW offload problem is present regardless of the LB template. This is yet to be verified. If it is verified, then we will need to provide a fix in OVN, and we are not sure yet if we can make LB template work with HW offload, which depends on the new fix in OVN.

**Comment by flavio-fernandes** [comment]
> > Please also add this to https://github.com/ovn-org/ovn-kubernetes/blob/master/helm/ovn-kubernetes/values.yaml so helm can benefit from it.
> > @flavio-fernandes please take a look

awesome. TYSM!

**Comment by flavio-fernandes** [comment]
LGTM

**Review by flavio-fernandes — APPROVED** [review]

**Pull request merged**
