### PR TITLE
[WIP] Migrate to ginkgo v2 / bump k8s deps to 1.26

### PR DESCRIPTION
**Pull request by bpickard22**
WIP pr for migratiing to ginkgo v2.

What is already done 
- Removed ginkgo v1 imports and replace with v2
- Fix current e2e tests to use v2
- Update go version and k8s deps 

What still needs to be done

Our current test suite uses some custom reporters which is no longer supported in v2. 
This is causing some  ginkgo flags to be set multiple times which will result in a panic 
if you attempt to run the tests

Migration docs here -> https://onsi.github.io/ginkgo/MIGRATING_TO_V2

### CODE REVIEW

**Comment by tssurya** [comment]
I mean we need to get our tests to 1.28, that's all I care about mainly - I am working on starting OVNK 1.28 rebase real soon. My understanding is that this is needed in order for that to happen?

**Comment by trozet** [comment]
@bpickard22 I think only the final commit: Update ginko version and go version is needed now. Want to rebase?

**Pull request closed without merging**
