### PR TITLE
Set node switch's router port's addresses to "router".

### PR DESCRIPTION
**Pull request by hzhou8**
Currently the LSP that connects the node switch to the cluster router
has its "addresses" column set to LRP's MAC address, which is incomplete
(missing IP) and redundant (MAC is already specified in the peer LRP).
What's worse, it leads to a problem that the ARP responder flows are not
installed for the LRP's IPs on the switch pipeline, which in turn causes
that all ARP requests from VIFs on the LS to the LRP's IP get flooded on
the LS and one of the copies hits the LR pipeline, which in turn leads to
mac-binding learning for the VIFs IP-MAC pair, propagating to SB DB,
and ovn-controllers installs extra OVS flows because of this. All these
are unnecessary because the VIFs' IP-MAC are known beforehand and no
need for the dynamic mac-bindings.

This patch fixes the problem by setting the LSP's addresses to "router",
because OVN will inteprete this keyword and install ARP responder flows
for its peer LRP's IPs.

Signed-off-by: Han Zhou <hzhou@ovn.org>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by girishmg** [comment]
LGTM.. just checking to make sure if we need `upgarde` path.

**Comment by girishmg** [comment]
ok, i tried that command on an existing logical topology and it does overwrite the previous value in the `addresses` column. So, no separate upgrade path is required.

**Comment by dcbw** [comment]
@girishmg @hzhou8 I'm not 100% sure about this patch; I tried it in an OpenShift setup and it had intermittent issues (like kubectl would take forever to respond). I'll do more tests to isolate whether this patch is the cause or not.

**Comment by hzhou8** [comment]
> @girishmg @hzhou8 I'm not 100% sure about this patch; I tried it in an OpenShift setup and it had intermittent issues (like kubectl would take forever to respond). I'll do more tests to isolate whether this patch is the cause or not.

@dcbw sorry that I didn't notice your message earlier. It looks unlikely to me that this change would cause kubectl slowness. It would introduce one more OVS flow per LSP (for ARP responder), but reduces two flows in table 66 & 67 per LSP (created for mac-bindings). As to control plane, it avoids the churns of dynamic mac-binding creations, so should be less cost overall. Let me know if the slowness of kubectl turns out to be caused by this patch.

**Comment by hzhou8** [comment]
@dcbw @girishmg I just thought about another churn that could be introduced by this patch: by default the ARP responder flow is added after northd seeing the LSP's up=true, which means after the LSP is bound on the chassis, northd would have another round of compute to generate the ARP responder flow for the LSP and update the SB again, which is then propagated to the ovn-controller. However, OVN has an option to avoid this churn: ovn-nbctl set NB_Global . options:ignore_lsp_down=true.

**Comment by hzhou8** [comment]
@dcbw @girishmg 
> It would introduce one more OVS flow per LSP (for ARP responder)

Sorry that I've to correct myself. It is not even adding flows per LSP, because LSPs already has the ARP responder flows even before this change. This change adds an ARP responder flow per LRP (per node) only. So it is even less to worry. (sorry that my head wasn't clear today)

**Pull request merged**
