### PR TITLE
[WIP] Test master kubernetes branch

### PR DESCRIPTION
**Pull request by aojea**
Compile the e2e binary from the master branch of kubernetes to be able to run the SCTP network policy tests

Signed-off-by: Antonio Ojea <aojea@redhat.com>

### CODE REVIEW

**Comment by danwinship** [comment]
I didn't mean we should switch to kube master right now. I was just wondering if we would be able to test the SCTP NetworkPolicy tests eventually. Note that there are other SCTP tests already in 1.19. (and maybe 1.18?)

**Comment by aojea** [comment]
> I didn't mean we should switch to kube master right now. I was just wondering if we would be able to test the SCTP NetworkPolicy tests eventually. Note that there are other SCTP tests already in 1.19. (and maybe 1.18?)

yeah, I just want to run them, it is a bit brute force I know, but only want to check the results

**Comment by aojea** [comment]
@danwinship SCTP tests are running and passing, can I assume that if they run is because the VM is loading the sctp module?

https://github.com/ovn-org/ovn-kubernetes/pull/1659/checks?check_run_id=1062838492

**Comment by danwinship** [comment]
> can I assume that if they run is because the VM is loading the sctp module?

Yes, they wouldn't pass otherwise. Also:

```
2020-09-02T17:48:23.8698043Z [1mSTEP[0m: getting the state of the sctp module on nodes
2020-09-02T17:48:23.8698370Z Sep  2 17:48:13.031: INFO: Executing cmd "lsmod | grep sctp" on node ovn-control-plane
2020-09-02T17:48:23.8698906Z Sep  2 17:48:15.188: INFO: ExecWithOptions {Command:[nsenter --mount=/rootfs/proc/1/ns/mnt -- sh -c lsmod | grep sctp] Namespace:sctp-1753 PodName:hostexec-ovn-control-plane-gd484 ContainerName:agnhost Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:true}
2020-09-02T17:48:23.8699115Z Sep  2 17:48:15.188: INFO: >>> kubeConfig: /home/runner/admin.conf
2020-09-02T17:48:23.8699440Z Sep  2 17:48:15.278: INFO: the sctp module is loaded on node: ovn-control-plane
```

**Comment by aojea** [comment]
ovn has switched to 1.19 https://github.com/ovn-org/ovn-kubernetes/pull/1658

**Pull request closed without merging**
