### PR TITLE
enable test conntrack nodeport

### PR DESCRIPTION
**Pull request by aojea**

### CODE REVIEW

**Comment by aojea** [comment]
hmm only local port fails :thinking:

**Comment by dcbw** [comment]
@aojea did we fix the IPBlock CIDR/Except thing now with jacob's recent PR?

**Comment by aojea** [comment]
> @aojea did we fix the IPBlock CIDR/Except thing now with jacob's recent PR?

yeah, it seem so https://github.com/ovn-org/ovn-kubernetes/commit/d93d11ad2cc417f6f99ccfa9bc7fcc8c83ca5cee#diff-196a5a05999fc3ba1ae1d0744209afb7

**Comment by aojea** [comment]
it failed
```
Summarizing 3 Failures:

[Fail] [sig-network] Conntrack [It] should be able to preserve UDP traffic when server pod cycles for a NodePort service 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/conntrack.go:195

[Fail] [sig-network] Conntrack [It] should be able to preserve UDP traffic when server pod cycles for a NodePort service 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/conntrack.go:170

[Fail] [sig-network] Conntrack [It] should be able to preserve UDP traffic when server pod cycles for a ClusterIP service 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/conntrack.go:250
```

**Comment by aojea** [comment]
@trozet this passed last time, if it passes again I think we can merge so we run the test

**Comment by aojea** [comment]
@trozet @dcbw an easy PR to review :)

**Comment by aojea** [comment]
superseded by https://github.com/ovn-org/ovn-kubernetes/pull/1870

**Pull request closed without merging**
