### PR TITLE
Update OVN 23.09 to latest version - ovn-23.09.0-81.

### PR DESCRIPTION
**Pull request by numansiddique**
**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by trozet** [comment]
hmm PMTUD flaked in one job, Load Balancer Service Tests with MetalLB [It] Should ensure load balancer service works with pmtu

Could be related to the change in OVN. We should retest a few times.

**Comment by pperiyasamy** [comment]
> hmm PMTUD flaked in one job, Load Balancer Service Tests with MetalLB [It] Should ensure load balancer service works with pmtu
> 
> Could be related to the change in OVN. We should retest a few times.

@trozet @numansiddique Yes, MetalLB is advertising lb service route correctly, can see ip route present for Lb IP in frr container with required ECMP configuration towards speaker nodes. So Looks like something is broken with OVN or br-ext OF pipeline.

```
192.168.10.0 nhid 85 proto bgp metric 20 
	nexthop via 172.18.0.3 dev eth0 weight 1 
	nexthop via 172.18.0.2 dev eth0 weight 1 
	nexthop via 172.18.0.4 dev eth0 weight 1 

```
Can also see Load_balancer, LSP and SNAT entries present for `lbservice-test` service and endpoints appropriately.

**Comment by trozet** [comment]
no idea how last run passed every job, running again :confused:

**Comment by trozet** [comment]
passed again, running a 4th time

**Comment by trozet** [comment]
passed again, running 5th time

There have been flakes related to pmtud with local gw mode + IC single zone that are consistent.

**Comment by dceara** [comment]
> There have been flakes related to pmtud with local gw mode + IC single zone that are consistent:
> 
> https://github.com/ovn-org/ovn-kubernetes/actions/runs/7117973398/job/19610169374?pr=4039
> 
> Summarizing 2 Failures: [FAIL] Load Balancer Service Tests with MetalLB [It] Should ensure load balancer service works with pmtu /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/service.go:1079

I ran this locally (kernel 6.2.7-200.fc37.x86_64) in a loop 20 times and it all passed just fine with this PR applied:
```
# . ./env.sh; make -C test control-plane WHAT="Load Balancer Service Tests with MetalLB"
[...]
[ReportAfterSuite] PASSED [0.003 seconds]
------------------------------

Ran 3 of 241 Specs in 66.816 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 238 Skipped
--- PASS: TestE2E (66.83s)
PASS
ok      github.com/ovn-org/ovn-kubernetes/test/e2e      66.881s
+ popd
~/ovn-kubernetes/test
make: Leaving directory '/root/ovn-kubernetes/test'

# grep passed test/_artifacts/junit_control-plane_01.xml
          <testcase name="[BeforeSuite]" classname="E2e Suite" status="passed" time="0.003118975"></testcase>
          <testcase name="[It] Load Balancer Service Tests with MetalLB Should ensure connectivity works on an external service when mtu changes in intermediate node" classname="E2e Suite" status="passed" time="16.666134539"></testcase>
          <testcase name="[It] Load Balancer Service Tests with MetalLB Should ensure load balancer service works with pmtu" classname="E2e Suite" status="passed" time="20.113792897"></testcase>
          <testcase name="[It] Load Balancer Service Tests with MetalLB Should ensure load balancer service works with 0 node ports when ETP=local" classname="E2e Suite" status="passed" time="30.020478014"></testcase>
```

**Comment by trozet** [comment]
@dceara @numansiddique @LorenzoBianconi  I was able to reproduce the failure it looks like a regression introduced by the ICMP handling flows added for geneve. The issue happens when an ICMP needs frag packet is forwarded by from one node to another via geneve. So if we have this topology:

external router (1200 mtu)---- > needs frag ----> ovn-worker ----->geneve ovn-worker2----pod

The packet is dropped on ovn-worker2 and not delivered to the pod:

```
  20:03:07.694455 genev_sys_6081 P   ifindex 4 0a:58:0a:f4:01:01 ethertype IPv4 (0x0800), length 596: (tos 0xc0, ttl 61, id 39722, offset 0, flags [none], proto ICMP (1), length 576)
      100.64.0.2 > 10.244.1.27: ICMP 100.64.0.2 unreachable - need to frag (mtu 1200), length 556
        (tos 0x0, ttl 61, id 7059, offset 0, flags [DF], proto TCP (6), length 6792)

Dropped by flow:
recirc_id(0),tunnel(tun_id=0x1,src=172.18.0.3,dst=172.18.0.4,geneve({class=0x102,type=0x80,len=4,0x10005/0xffff7fff}),flags(-df+csum+key)),in_port(2),eth(src=00:00:00:00:00:00/01:00:00:00:00:00),eth_type(0x0800),ipv4(proto=1,frag=no),icmp(type=3,code=4), packets:7, bytes:4130, used:5.623s, actions:drop

```

In the working case we can see the ICMP needs frag arrive at both the geneve iface as well as the pod on the node:

```
  20:38:44.826505 genev_sys_6081 P   ifindex 4 0a:58:0a:f4:01:01 ethertype IPv4 (0x0800), length 596: (tos 0xc0, ttl 61, id 7469, offset 0, flags [none], proto ICMP (1), length 576)
      100.64.0.4 > 10.244.1.11: ICMP 100.64.0.4 unreachable - need to frag (mtu 1200), length 556
        (tos 0x0, ttl 61, id 52381, offset 0, flags [DF], proto TCP (6), length 6792)
      10.244.1.11.80 > 100.64.0.4.47844: Flags [P.], seq 6740:13480, ack 1, win 505, options [nop,nop,TS val 2293414869 ecr 4116842542], length 6740: HTTP
  20:38:44.826993 6303cc4423eee7e Out ifindex 15 0a:58:0a:f4:01:01 ethertype IPv4 (0x0800), length 596: (tos 0xc0, ttl 61, id 7468, offset 0, flags [none], proto ICMP (1), length 576)
      100.64.0.4 > 10.244.1.11: ICMP 100.64.0.4 unreachable - need to frag (mtu 1200), length 556
        (tos 0x0, ttl 61, id 52376, offset 0, flags [DF], proto TCP (6), length 6792)
      10.244.1.11.80 > 100.64.0.4.47844: Flags [P.], seq 0:6740, ack 1, win 505, options [nop,nop,TS val 2293414869 ecr 4116842542], length 6740: HTTP
```

In the working case, it does not hit any icmp+geneve specific flow. Do you need me to open a bug for you to track this?

**Comment by dceara** [comment]
> @dceara @numansiddique @LorenzoBianconi I was able to reproduce the failure it looks like a regression introduced by the ICMP handling flows added for geneve. The issue happens when an ICMP needs frag packet is forwarded by from one node to another via geneve. So if we have this topology:
> 
> external router (1200 mtu)---- > needs frag ----> ovn-worker ----->geneve ---->ovn-worker2----pod
> 

Wow, I really wonder why I didn't hit this path even once.  Anyway, great catch!

> The packet is dropped on ovn-worker2 and not delivered to the pod:
> 
> ```
>   20:03:07.694455 genev_sys_6081 P   ifindex 4 0a:58:0a:f4:01:01 ethertype IPv4 (0x0800), length 596: (tos 0xc0, ttl 61, id 39722, offset 0, flags [none], proto ICMP (1), length 576)
>       100.64.0.2 > 10.244.1.27: ICMP 100.64.0.2 unreachable - need to frag (mtu 1200), length 556
>         (tos 0x0, ttl 61, id 7059, offset 0, flags [DF], proto TCP (6), length 6792)
> 
> Dropped by flow:
> recirc_id(0),tunnel(tun_id=0x1,src=172.18.0.3,dst=172.18.0.4,geneve({class=0x102,type=0x80,len=4,0x10005/0xffff7fff}),flags(-df+csum+key)),in_port(2),eth(src=00:00:00:00:00:00/01:00:00:00:00:00),eth_type(0x0800),ipv4(proto=1,frag=no),icmp(type=3,code=4), packets:7, bytes:4130, used:5.623s, actions:drop
> ```

This is likely because we "swap" logical inport/outport for all ICMP errors received from geneve.

> 
> In the working case we can see the ICMP needs frag arrive at both the geneve iface as well as the pod on the node:
> 
> ```
>   20:38:44.826505 genev_sys_6081 P   ifindex 4 0a:58:0a:f4:01:01 ethertype IPv4 (0x0800), length 596: (tos 0xc0, ttl 61, id 7469, offset 0, flags [none], proto ICMP (1), length 576)
>       100.64.0.4 > 10.244.1.11: ICMP 100.64.0.4 unreachable - need to frag (mtu 1200), length 556
>         (tos 0x0, ttl 61, id 52381, offset 0, flags [DF], proto TCP (6), length 6792)
>       10.244.1.11.80 > 100.64.0.4.47844: Flags [P.], seq 6740:13480, ack 1, win 505, options [nop,nop,TS val 2293414869 ecr 4116842542], length 6740: HTTP
>   20:38:44.826993 6303cc4423eee7e Out ifindex 15 0a:58:0a:f4:01:01 ethertype IPv4 (0x0800), length 596: (tos 0xc0, ttl 61, id 7468, offset 0, flags [none], proto ICMP (1), length 576)
>       100.64.0.4 > 10.244.1.11: ICMP 100.64.0.4 unreachable - need to frag (mtu 1200), length 556
>         (tos 0x0, ttl 61, id 52376, offset 0, flags [DF], proto TCP (6), length 6792)
>       10.244.1.11.80 > 100.64.0.4.47844: Flags [P.], seq 0:6740, ack 1, win 505, options [nop,nop,TS val 2293414869 ecr 4116842542], length 6740: HTTP
> ```
> 
> In the working case, it does not hit any icmp+geneve specific flow. Do you need me to open a bug for you to track this?

Yes, please!  As you suggested offline a potential solution might be to make the additional icmp+geneve flows only match on traffic originated locally.

Checking the available fields we can match on I see:
```
    /* "tun_src".
     *
     * The IPv4 source address in the outer IP header of a tunneled packet.
     *
     * For non-tunneled packets, the value is 0.
     *
     * Type: be32.
     * Maskable: bitwise.
     * Formatting: IPv4.
     * Prerequisites: none.
     * Access: read/write.
     * NXM: NXM_NX_TUN_IPV4_SRC(31) since v2.0.
     * OXM: none.
     * Prefix lookup member: tunnel.ip_src.
     */
    MFF_TUN_SRC,
```
Maybe we can add an extra match to those icmp error flows, to only match on `tun_src = <local-ip>`.  @LorenzoBianconi what do you think?

In any case, @trozet, it would be great if you could open a bug for us to track the fix for this.

**Comment by numansiddique** [comment]
@trozet can you also attach OVN dbs please to the bug

**Comment by trozet** [comment]
Filed https://issues.redhat.com/browse/FD-3253

**Comment by tssurya** [comment]
nice catch @trozet !
I remember that when we did https://issues.redhat.com/browse/FD-2283 we had specifically done some flows for this same path, GRnode1->cluster-router->GENEVE->cluster-router->switchnode2->pod. Perhaps that fix got overthrown by the new fix?

**Comment by numansiddique** [comment]
I actually thought of this scenario before accepting @LorenzoBianconi's patch.

I was under the impression that,  ovn-k would set gateway_mtu value on the GW router with the lesser MTU and this would result in OVN generating ICMP need frag (by making use of check_pkt_larger).    But looks like my assumption was wrong.

**Comment by tssurya** [comment]
@trozet : started https://github.com/ovn-org/ovn-kubernetes/pull/4053 based on what we spoke.. PTAL.

**Pull request closed without merging**
