### PR TITLE
switch to newer fedora:34 so to enable ovn 20.12

### PR DESCRIPTION
**Pull request by dyusupov**
current version fedora:32 will install older version.
newer version needs to be tested on more periodic basis as per master branch

Signed-off-by: Dmitry Yusupov <dyusupov@nvidia.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by dcbw** [comment]
@aojea what do you think?

**Comment by aojea** [comment]
> @aojea what do you think?

I´m not too familiar with the OVN releasing process for fedora, but we should use whatever is better for us to pick the OVN changes that we want to test/use ...

**Comment by dyusupov** [comment]
@girishmg @dcbw @aojea we also need this in terms of to enable testing of --fair acl metering flag

**Comment by aojea** [comment]
> @girishmg @dcbw @aojea we also need this in terms of to enable testing of --fair acl metering flag

yeah, I wanted to mean that the closer we are to get the new features the better, if the OVN team release sooner in fedora 34 we should use it

**Comment by aojea** [comment]
I was wondering if we should pin the ovs/ovn versions to and bumping them manually , so we can identify possible regressions/incompatibilites between ovn-kube and ovn

**Comment by dyusupov** [comment]
> I was wondering if we should pin the ovs/ovn versions and bumping them manually , so we can identify possible regressions/incompatibilites between ovn-kube and ovn

I think it is a fine idea and in the same line of thoughts we should at some point think wrt. stable branch that will be pinned to an older version of ovs/ovn, perhaps naming it after ovn, like ovn-kubernetes-20.12 etc. I think @dcbw brought this up to one of community meetings  but we've never concluded on it.

**Comment by aojea** [comment]
branching can be expensive to maintain at this stage and for this type of project, I will happy just with tagging and and doing a "kind" of release explaining the ovn/ovs/kubernetes versions that weren't tested at that time, so we can have a temporal reference

**Review by trozet — APPROVED** [review]
/lgtm

**Pull request merged**
