### PR TITLE
unit tests for functions in util/net.go file

### PR DESCRIPTION
**Pull request by vjayaramrh**
Signed-off-by: Vishwanath Jayaraman <vjayaram@redhat.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by dcbw** [comment]
I forget if I asked this in a different PR... but ovnkube testing uses ginkgo/gomega, but these don't. Any particular reason why?

**Comment by vjayaramrh** [comment]
> I forget if I asked this in a different PR... but ovnkube testing uses ginkgo/gomega, but these don't. Any particular reason why?

In late April, @trozet @abhat ( and others as part of post-scrum discussion)  and I discussed about Unit Tests and using testify and mocks for writing the Unit Tests for the ovs.go file. The summary of the discussion at that time and later was that for unit tests 1) would rely on using testify and mocks for unit tests 2) use BDD approach supported by GIngko /Gomega for component/functions/behavior driven tests.
The first PR using testify and mocks is at https://github.com/ovn-org/ovn-kubernetes/pull/1333. In the PR description, I have shared some links related to testify/mocks as well.

@dcbw Let me know if there is a discussion with you, @trozet @girishmg @abhat and @danwinship over a blue jeans call to further discuss this and I can set that up. Thanks

**Comment by vjayaramrh** [comment]
> I forget if I asked this in a different PR... but ovnkube testing uses ginkgo/gomega, but these don't. Any particular reason why?
Additional data point: the current tests can be thought of as standard go tests (provided by go's testing package) but uses the assertions/mocks (where needed) provided by testify.

**Comment by trozet** [comment]
@dcbw current plan is to get unit testing done with testify. We decided it was better than ginkgo/gomega for just unit testing. After we get all the proper unit tests added, @vjayaramrh will go back and remove duplicate unit tests that are in ginkgo. We may still keep the ginkgo stuff to help with functional tests.

**Pull request merged**
