### PR TITLE
Add ip6tables for linux mgmt port setup

### PR DESCRIPTION
**Pull request by russellb**
This code used iptables only, and will now use ip6tables if the
management port's address is IPv6.  During cleanup, it will cleanup
both IPv4 and IPv6 rules, just in case.

### CODE REVIEW

**Comment by russellb** [comment]
/cc @markmc 

reworked from your original patch to be conditional (at least during setup)

**Comment by danwinship** [comment]
There's iptables code in `pkg/cluster/gateway_localnet.go` that needs to be updated too (to poke holes in the localfirewall, and to set up NodePort services correctly). So this is correct but incomplete.

**Comment by russellb** [comment]
> There's iptables code in `pkg/cluster/gateway_localnet.go` that needs to be updated too (to poke holes in the local firewall, and to set up NodePort services correctly). So this is correct but incomplete.

Thanks, I'll take a look.  Those changes may be in another commit.  I was going through the commits in our ipv6 fork 1-by-1 and posting them, with some updates if needed.

**Comment by russellb** [comment]
OK, I'll post here if it hasn't merged yet, or as a follow-up PR

**Comment by russellb** [comment]
@dcbw @danwinship added another commit to this PR

note the commit message, where this won't actually do anything yet, as more work is needed to make the localnet gateway config not be hard coded to IPv4.  That will come in future PRs ...

**Comment by girishmg** [comment]
@russellb can you please add Signed-off-by to your commits? Thanks.

**Comment by russellb** [comment]
> @russellb can you please add Signed-off-by to your commits? Thanks.

done

**Comment by russellb** [comment]
This is now included in a larger IPv6 PR - https://github.com/ovn-org/ovn-kubernetes/pull/968

**Pull request closed without merging**
