### PR TITLE
Add required capabilities for ovnkube-node

### LINKED ISSUE #1350: ovnkube-node cannot be launched due to lack of capabilities
Install latest ovn-kubernetes(i.e. master) in vanilla kubernetes, then ovn-node gets failure `] failed to initialize iptables: could not get iptables version: exit status 125` then exit, due to lack of capabilities for ovnkube-node container in ovnkube-node.yml.

```
[centos@kube-master1 yaml]$ kubectl get -n ovn-kubernetes pod
NAME                              READY   STATUS              RESTARTS   AGE
ovnkube-db-5cc9744b8-knhwg        2/2     Running             0          15m
ovnkube-master-68d48cd588-pmnjx   3/3     Running             2          15m
ovnkube-node-4tp8g                0/3     Running             0          23s
ovnkube-node-6fc4w                0/3     ContainerCreating   0          23s
[centos@kube-master1 yaml]$ kubectl -n ovn-kubernetes logs ovnkube-node-4tp8g ovnkube-node
================== ovnkube.sh --- version: 3 ================
 ==================== command: ovn-node
 =================== hostname: kube-master1
 =================== daemonset version 3
 =================== Image built from ovn-kubernetes ref: refs/heads/master  commit: ac35a2e6248b96409bd774df961a486ee470b488
(snip)
=============== ovn-node ========== running
(snip)
I0520 02:47:35.515918   14179 ovs.go:246] exec(13): /usr/bin/ovs-vsctl --timeout=15 --if-exists get Open_vSwitch . external_ids:system-id
I0520 02:47:35.599372   14179 ovs.go:249] exec(13): stdout: "\"cbbbe1c3-92e2-4fab-be51-4a7f48909b6a\"\n"
I0520 02:47:35.599417   14179 ovs.go:250] exec(13): stderr: ""
F0520 02:47:35.601419   14179 ovnkube.go:129] failed to initialize iptables: could not get iptables version: exit status 125
=============== pid 14179 terminated ==========
```

Environment
ovn-kubernetes: master
Centos: Centos7
```
[centos@kube-master1 ~]$ uname -a
Linux kube-master1 5.6.14-1.el7.elrepo.x86_64 #1 SMP Tue May 19 12:17:13 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by s1061123**
Signed-off-by: Tomofumi Hayashi <tohayash@redhat.com>

This fixes #1350 

**- What this PR does and why is it needed**

This PR addes capabilities required to run ovnkube-node and it is necessary to run ovnkube-node.

**- Special notes for reviewers**

**- How to verify it**

`kubectl create -f ovn-org/ovn-kubernetes/dist/yaml/ovnkube-node.yaml`

**- Description for the changelog**

Fix capabilities in ovnkube-node

### CODE REVIEW

**Comment by girishmg** [comment]
@s1061123 can you please explain why do you need each of those capabilities that you have included in your PR? What errors are you seeing without them? We want to run ovnkube-node daemon with as much least capabilities as possible. Thanks.

**Comment by s1061123** [comment]
I've put the error log in issue #1350, as following.

`F0520 02:47:35.601419   14179 ovnkube.go:129] failed to initialize iptables: could not get iptables version: exit status 125`

I don't know the details why we need the additional capability because I don't look into ovnkube-node code. I only know ovnkube-node will be failed without the capability. Of course you can modify ovnkube-node code to run it with current capability and it is trade-off.

I just report with candidate fix. I'm pretty okey if you don't want it and close it because I got the fix in my side.

**Comment by trozet** [comment]
@s1061123 I think what @girishmg is getting is we would like to understand why you see this and we don't on different platforms. Can you try a KIND deployment and see if you hit it there?

@danwinship it looks like you think it is chroot failure. @s1061123 can you try reducing your added permissions to just "SYS_CHROOT" and see if that by itself fixes it?

**Comment by trozet** [comment]
I don't think we ever found out why these capabilities were needed, and we also reduced the ones we were previously using and don't have any issues in KIND.

**Pull request closed without merging**
