### PR TITLE
Add SCTP support for network policy

### PR DESCRIPTION
**Pull request by trozet**
Signed-off-by: Tim Rozet <trozet@redhat.com>

### CODE REVIEW

**Comment by trozet** [comment]
@danwinship @dcbw

**Comment by trozet** [comment]
Partial fix for #1120

**Comment by danwinship** [comment]
lgtm

**Comment by trozet** [comment]
a new test executed which failed using ingress:
[Fail] [sig-network] Loadbalancing: L7 [BeforeEach] GCE [Slow] [Feature:Ingress] should create ingress with pre-shared certificate

Verified this test will pass if we add an ingress controller to KIND deployments. Will add a follow up commit to add this.

**Comment by trozet** [comment]
@dcbw @danwinship PTAL

**Comment by russellb** [comment]
lgtm

**Pull request merged**
