### PR TITLE
EgressIP: cleanup stale e2e test data + wait for setup

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
Egress IP e2e tests were flaking because of two reasons:

1. We were not waiting for the egress IP setup to complete
before starting connectivity tests. This is done now by
obeserving the status change, and then performing the
connectivity test

2. When any subsequent test retry happened, we never cleaned
up stale test data from the run in N-1, leading to state
mismatch and flaky failures

Spin-off from https://github.com/ovn-org/ovn-kubernetes/pull/2032#issuecomment-777819636

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by trozet — APPROVED** [review]
/lgtm @alexanderConstantinescu can you please just rebase?

**Comment by alexanderConstantinescu** [comment]
> /lgtm @alexanderConstantinescu can you please just rebase?

Done

**Review by trozet — APPROVED** [review]
/lgtm

**Pull request merged**
