### PR TITLE
Enable IGMP Querier only if a source IPv4 is available.

### PR DESCRIPTION
**Pull request by dceara**
Fixes: c3def15ad986 ("Add multicast support.")
Signed-off-by: Dumitru Ceara <dceara@redhat.com>

### CODE REVIEW

**Comment by danwinship** [comment]
So what does this mean? What exactly does this PR end up doing in an IPv6-only environment? Does IPv6 multicast just work fine even without the IGMP querier?

**Comment by dceara** [comment]
> So what does this mean? What exactly does this PR end up doing in an IPv6-only environment? Does IPv6 multicast just work fine even without the IGMP querier?

IGMP is only for IPv4. IGMP querier needs a source IPv4 address for switch self originated membership queries. The querier is useful because it refreshes IPv4 multicast group memberships but IPv4 multicast works fine even when only IGMP Snoop is enabled (groups will be timed out according to the multicast configuration).

The PR just avoids trying to set the `mcast_ip4_src` to an IPv6 value because that would generate an error log in `ovn-controller` and just disable querier anyway.

As far as I see there's no clear way to differentiate in ovn-k8s between an IPv6-only environment and a dual IPv4-IPv6 environment. With this in mind we can just enable IGMP snooping in case there's both IPv4 and IPv6 traffic in the cluster such that at least the IPv4 traffic is forwarded properly.

OVN doesn't have support for IPv6 multicast snooping (MLD) and IPv6 multicast relay yet. It's planned for OVN 2.13. At that point we would also enable MLD snooping by default and MLD querier when we have an IPv6 address that we can use as source for the queries.

Given the above, at this point in ovn-k8s, IPv6 multicast traffic will just be flooded in the logical switch broadcast domain and will never be routed outside the node.

**Comment by danwinship** [comment]
ok. lgtm

**Pull request merged**
