### PR TITLE
Changes for klog v2.

### PR DESCRIPTION
**Pull request by tfherbert**
Updated by go mod tidy.

Signed-off-by: Thomas F Herbert <therbert@redhat.com>

Fixes #1886062 against openshift/ovn-kubernetes.

This is related to a bug in openshift/ovn-k.  Logging is broken because of kubernetes upstream change to klog v2. This fix should also help with ovn-kubernetes in upstream kubernetes subsequent to the change to golang 1.19.

Updates klog to v2 consistent with upstream kubernetes.

### CODE REVIEW

**Comment by tfherbert** [comment]
@alexanderConstantinescu

**Comment by alexanderConstantinescu** [comment]
Just FYI: usually what we do when we have PRs which need new package imports is that we create one commit for the change required to `go.mod`, then another for the re-vendoring files, then a subsequent commit for the changes needed to the code. That is done as to ease the reviewing process. In this case I think this is fine since the changes to the code base are small enough for the review to be done easily. 

However, I just downloaded the logs from the CI run: https://github.com/ovn-org/ovn-kubernetes/suites/1415423233/artifacts/23702559

And saw the following in ovnkube-master:

```
2020-10-28T20:35:23.201758152Z stdout F info: Waiting for process_ready ovnkube-master to come up, waiting 1s ...
2020-10-28T20:35:23.215360388Z stderr F I1028 20:35:23.215179      41 config.go:1374] Default config: {MTU:1400 ConntrackZone:64000 EncapType:geneve EncapIP: EncapPort:6081 InactivityProbe:100000 OpenFlowProbe:180 RawClusterSubnets:10.244.0.0/16 ClusterSubnets:[{CIDR:10.244.0.0/16 HostSubnetLength:24}]}
2020-10-28T20:35:23.215520691Z stderr F I1028 20:35:23.215446      41 config.go:1375] Logging config: {File:/var/log/ovn-kubernetes/ovnkube-master.log CNIFile:/var/log/ovn-kubernetes/ovn-k8s-cni-overlay.log Level:5 LogFileMaxSize:100 LogFileMaxBackups:5 LogFileMaxAge:5}
```  

Do you happen to know why it says it's logging everything the `ovnkube` process is doing on `stderr`? Ex: `Default config: {MTU:1400 ConntrackZone:64000 EncapType:geneve EncapIP: EncapPort:6081 InactivityProbe:100000 OpenFlowProbe:180 RawClusterSubnets:10.244.0.0/16 ClusterSubnets:[{CIDR:10.244.0.0/16 HostSubnetLength:24}]}` 

That should be logged on `stdout`...the log is generated here:

https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/config/config.go#L1374

**Comment by tfherbert** [comment]
As for separating commit for vendoring, I think you are right. Initially in SDN and ovn-k downstream, I did it this way. On this PR, I re-based before generating PR because actual changes in the code were seemingly tiny WRT to vendoring changes.

As for the stderr vs stdout. I wonder if the change from v1 to v2 had a side affect of jumping a log level which could inadvertently cause a side affect where logging would go from stdout to stderr. Let me try to track that down. Maybe to debug, I should submit a do-not-merge PR with the change to V2 backed out in only this file.

**Comment by alexanderConstantinescu** [comment]
> As for the stderr vs stdout. I wonder if the change from v1 to v2 had a side affect of jumping a log level which could inadvertently cause a side affect where logging would go from stdout to stderr.

I am not sure, everything logged in ovnkube-master is denoted `stderr`, even things which are logged as `klog.Infof` without specifying log level....well, it has a log-level (which is 2). 

Anyways, could you also tell me what the `F` denotes in: 

```
2020-10-28T20:35:23.215360388Z stderr F I1028 20:35:23.215179      41 config.go:1374] 
```

The first column: `2020-10-28T20:35:23.215360388Z` is date-time
The second: `stderr` is the file descriptor the process wrote to? 
The third: `F` .... ?
The fourth: `I1028` is the date and level logged on (either I for info, W, for warning or E for error)
The fifth: `20:35:23.215179` would seem to be time, but it does not match date-time, so what is that?
The sixth: `41` the process ID
The seventh: `config.go:1374` file and line number captured on.

**Comment by tfherbert** [comment]
Infof is a formatting variant kind of like printf in C. It allows you to pass in a formatted argument. https://github.com/kubernetes/klog/blob/master/klog.go#L1352
Of more interest is the "v" which specifies verbosity with an implied log file. I am checking to see if there are semantic differences with V2.

**Comment by aojea** [comment]
I think that you need to rebase this on master :thinking:

**Comment by alexanderConstantinescu** [comment]
@tfherbert : I think you've re-based in the "wrong direction" somehow.

**Comment by tfherbert** [comment]
Fixing.

**Comment by tfherbert** [comment]
Moving to draft, do-not-merge status. New PR will be submitted after earlier commit already added klog/v2 to vendor.

**Comment by tfherbert** [comment]
Refer to PR #1817

**Pull request closed without merging**
