### PR TITLE
Remove NAD controllers circular dependency

### PR DESCRIPTION
**Pull request by npinaeva**
```
type networkControllerManager struct {
   nadController *netAttachDefinitionController
}

type netAttachDefinitionController struct {
   ncm   NetworkControllerManager
}
```
Create a new struct ovnkubeMaster, that creates the default network controller, and nad controller when EnableMultiNetwork is true. Move non-NADNetworkController realted functionality from the networkControllerManager to ovnkubeMaster.
To avoid circular import, move network-controller-manager folder to ovn.
Move DefaultNetworkController node handling function form master.go to node.go

Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>

### CODE REVIEW

**Comment by maiqueb** [comment]
@npinaeva could you explain in the PRs description what exactly triggers this circular import ? It's not clear to me.

**Comment by npinaeva** [comment]
@cathy-zhou it's not circular import, but circular dependency I have in the description: 2 objects have references to each other

**Comment by maiqueb** [comment]
> @cathy-zhou it's not circular import, but circular dependency I have in the description: 2 objects have references to each other

my bad. Thanks.

**Comment by msherif1234** [comment]
Hmm as part of https://github.com/numansiddique/ovn-kubernetes/pull/11/commits/b644a75f82fd4fb316f642cfeae3e168a71ef430 I split network-controller-manager pkg into two parts to keep nad part in this pkg so we can use it in cluster-manager PR
wouldn't this PR collide with those changes ?

**Comment by jcaamano** [comment]
One of the things we tried to do with secondary networks is avoiding adding more stuff than necessary to the ovn package, and create new packages instead as it is already quite big and we just keep adding stuff. This reverses this a bit and goes again in the opposite direction.

Would it be possible to have `ovnkubeMaster` in it's own `pkg/master` package and keep the network controller manager in the package that it was?

**Comment by npinaeva** [comment]
yeah so this is actually the first step from https://github.com/ovn-org/ovn-kubernetes/pull/3413/commits
`ovnkubeMaster` should create default network controller and NADcontroller so `networkControllerManager` needs to go to ovn package anyway since it creates secondary ovn controllers, but as @msherif1234 noticed, if cluster manager is external to `ovn` package, and needs to use NADcontroller, we can leave it in an external package.

**Comment by tssurya** [comment]
> Hmm as part of [numansiddique@b644a75](https://github.com/numansiddique/ovn-kubernetes/commit/b644a75f82fd4fb316f642cfeae3e168a71ef430) I split network-controller-manager pkg into two parts to keep nad part in this pkg so we can use it in cluster-manager PR wouldn't this PR collide with those changes ?

Let's ensure the IC bits in https://github.com/ovn-org/ovn-kubernetes/pull/3127 get in first to avoid numan having to rebase again since this is not super critical?

**Pull request closed without merging**
