### PR TITLE
persist the mac address associated with br-nexthop OVS internal port

### LINKED ISSUE #946: Localnet gateway br-nexthop needs to be resynced on node reboot
The MAC address of br-nexthop always changed after node reboot. However, when pod try to communicate with the node IP, the GR router of OVN keeps using the old MAC address of br-nexthop as the dst_mac. And it doesn’t work.  The only way I can make it work is to ping 169.254.33.2 on the node.  I guess it updates the ARP table of GR router.

### PR DESCRIPTION
**Pull request by girishmg**
Fixes #946

@dcbw @shettyg PTAL

### CODE REVIEW

**Comment by dcbw** [comment]
@girishmg won't this just re-set the MAC of a newly-created br-nexthop? eg if the node reboot, and the interface is gone, then the node re-creates br-nexthop and it gets a new MAC, we'll just be using the new MAC instead of the old one?

**Comment by girishmg** [comment]
@dcbw should we then have a fixed well-known MAC address for the br-nexthop? Say, 
00:00:a9:fe:21:01 (hex representation of 169.254.33.1)?

**Comment by dcbw** [comment]
Decision from the call was to do fixed MAC

**Comment by girishmg** [comment]
@dcbw PTAL

**Pull request merged**
