### PR TITLE
Fix panic in UT

### PR DESCRIPTION
**Pull request by tssurya**
This was introduced in https://github.com/ovn-org/ovn-kubernetes/pull/4713 but seriously I don't know why UT CI did not fail in that PR?

Fixes: #4765

### CODE REVIEW

**Comment by pperiyasamy** [comment]
The run https://github.com/ovn-org/ovn-kubernetes/actions/runs/11251572547/job/31282909395?pr=4762 hits this as well.

**Comment by tssurya** [comment]
let's see if CI passes now

**Comment by kyrtapz** [comment]
> This was introduced in #4713 but seriously I don't know why UT CI did not fail in that PR?

Maybe that's because we are not resetting the runner and one describe block sets it so depending on which goes first it works or crashes?
I think we are missing this in both blocks:
```
	AfterEach(func() {
		util.ResetRunner()
	})
```

**Review by kyrtapz — APPROVED** [review]

**Comment by tssurya** [comment]
> Maybe that's because we are not resetting the runner and one describe block sets it so depending on which goes first it works or crashes? I think we are missing this in both blocks:
> 
> ```
> 	AfterEach(func() {
> 		util.ResetRunner()
> 	})
> ```

yea perhaps though it is funny is started perma failing since morning he he he
but good catch here, I have repushed with this

**Comment by tssurya** [comment]
This PR only touches unit tests, has no changes to e2e's has an lgtm, merging it

**Pull request merged**
