### PR TITLE
Remove CNI CMD Check

### PR DESCRIPTION
**Pull request by trozet**
The check isn't really used for anything and causes a performance impact
on CRIO setups due to being called right after CNI ADD for container
creation.

Signed-off-by: Tim Rozet <trozet@redhat.com>

### CODE REVIEW

**Comment by trozet** [comment]
@girishmg

**Comment by girishmg** [comment]
@trozet @dcbw besides calling CMD_CHECK immediately after CMD_ADD doesn't `kubelet` depend on CMD_CHECK to check if the pod interfaces are all configured fine?

**Comment by dcbw** [comment]
> @trozet @dcbw besides calling CMD_CHECK immediately after CMD_ADD doesn't `kubelet` depend on CMD_CHECK to check if the pod interfaces are all configured fine?

@girishmg no, it doesn't. That was the intent of CHECK but it never got implemented that way in crio or containerd. I think this use of CHECK is still useful but it might be time to think about that more broadly (eg, plugin health rather than just container health for example). But for the moment, it doesn't bring any real benefit besides slowing down container creation by hammering OVS.

**Comment by dcbw** [comment]
FWIW, if you want to see if the runtime calls CHECK outside of the ADD, look in the PodSandboxStatus() CRI implementation for each runtime; that's where the container network health would need to be gathered and returned. Both containerd and CRIO pull the network info from their cache, rather than calling CHECK.

**Comment by girishmg** [comment]
@dcbw thanks for the info.

@trozet i am fine with this change.

**Comment by trozet** [comment]
Known flake for multicast, which we know about and waiting on OVN image for upstream:
[Fail] Multicast [It] should be able to send multicast UDP traffic between nodes 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/multicast.go:123

**Pull request merged**
