### PR TITLE
[WIP] Route Pod network traffic to host through tunnel

### PR DESCRIPTION
**Pull request by adrianchiris**
Route Pod network traffic to host through tunnel
    
  Today pod network traffic to k8s workers(host network)
  is sent through GR to be SNATed and then to the underlay.
  on the recieving end, traffic is sent to CT on the
  physical bridge and forwarded to the host
  i.e LOCAL port or host representor port in case of Smart-NICs.
  
  By design, the conntrack state on zone 64000 is never
  established for host destined traffic which may prevent
  offload capable NICs from offloading this type of traffic.
  
  To overcome the issue, we will route host destined traffic
  from OVN to the respective ovn management port.
  doing so, we trade the additional conntrack on zone 64000
  (on both sender and reciever side) and SNAT of GR (on sender side)
  with tunnel encap/decap.
  
  As many NICs are capable of offloading tunnel encap/decap
  operations, it will result in an overall increase in performance
  where supported hardware is present.
  
  This commit modifies the existing policy based routes on
  ovn cluster router and adds a new config knob
  "EnableTunneledHostTraffic" to control the routing of host
  destined traffic from pod network.
  
  When enabled, Policy based routes are addeded to route host destioned
  ip traffic to the respective host through its management port(ovn-k8s-mp0).
  
  When disabled, only pod to node local traffic will be routed through
  the management port as it is today.

**- Special notes for reviewers**
swapping between enable/disable of this feature will swap the 1004 priority policy based routes on ovn_cluster_router.
downgrade may be an issue as previous logic will not try to remove stale policies as `syncPolicyBasedRoutes` used to match on host name + "

**- How to verify it**
Deploy OVN k8s with `--tunneled-host-traffic-enable=true` create pod, run traffic from pod to host network on another worker node, see that traffic goes to that host via ovn-k8s-mp0 port instead of ovs LOCAL port

**- Description for the changelog**
Refer to individual commit messages

### CODE REVIEW

**Comment by adrianchiris** [comment]
cc @trozet @girishmg

**Comment by adrianchiris** [comment]
Note: this will offload on reciever end if:
1. NIC supports internal port offload
2. VF is used as management port.

**Comment by dcbw** [comment]
@mccv1r0 might be interesting to you for your MTU/MSS investigations.

**Comment by dcbw** [comment]
@adrianchiris also, we don't need to SNAT this traffic either right? The reason we currently have to SNAT this pod -> host traffic is to ensure that the destination host sends the reply back over the underlay to the original node since that's the path the source packet took. But if the source packet is coming over the overlay then we can just send it directly back into the overlay without SNAT.

**Comment by adrianchiris** [comment]
> @adrianchiris also, we don't need to SNAT this traffic either right? 

Yes, this PR routes pod to host traffic via mgmt port. so we dont go through GR so no SNAT. traffic (pod to k8s node) in this case is symmetric.

The issue im trying to address is host traffic get sent to ct zone 6400 but never establishes.
I am working on a different PR which addresses this issue in a more general way (and not just for pod to k8s node) by using ct_mark. this is under internal testing.

**Comment by mccv1r0** [comment]
> adds a new config knob "EnableTunneledHostTraffic" to control the routing of host destined traffic from pod network.

IMO we don't need a knob.  This should always be done.

**Comment by adrianchiris** [comment]
> The issue im trying to address is host traffic get sent to ct zone 6400 but never establishes.
I am working on a different PR which addresses this issue in a more general way (and not just for pod to k8s node) by using ct_mark to classify host/ovn traffic on br-ex. this is under internal testing. underlay traffic flows in this case (should) go nicely through GR.

https://github.com/ovn-org/ovn-kubernetes/pull/2330

**Comment by trozet** [comment]
closed in favor of #2330

**Pull request closed without merging**
