### PR TITLE
remove the experimental --ha option from ovn-k8s

### PR DESCRIPTION
**Pull request by girishmg**
--ha provided a way to rebuild OVN DB in the case when the DBs got
corrupted or got lost. However, we now have a way to provide the OVN DB
HA either natively through K8s or outside of k8s. As a result, --ha
option as a OVN DB HA is not that useful. Also, that part of the code
is unmaintained and has not been tested in a while.

Signed-off-by: Girish Moodalbail <gmoodalbail@nvidia.com>

### CODE REVIEW

**Comment by girishmg** [comment]
@shettyg @dcbw PTAL. I have tested it, and it looks good.

**Comment by shettyg** [comment]
There was also code in cluster/node where it would watch namespace and updateIP when master changed. You are not removing it?

**Comment by girishmg** [comment]
@shettyg the commit d65b44226d9c2916935e1eb05a3e658b7c602209 repurposed that code to something else. So, that code is not there anymore.

**Pull request merged**
