### PR TITLE
Retest failed command improvements and /retest-failed action

### PR DESCRIPTION
**Pull request by andreaskaris**
Github just released the rerun failed jobs feature that we have been waiting for:
* https://github.com/actions/runner/issues/432
* https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs

That makes my recent changes with caching seem a bit of overkill.
Roll back those changes and instead introduce a "retest-failed" command.
Keep the master and PR image cache as both are dependencies for the other jobs (so we can save some time and computing).
Also relay error messages to the end user should they occur - for an example of so far missed error messages, see 
https://github.com/ovn-org/ovn-kubernetes/runs/5542811058?check_suite_focus=true
~~~
+ RERUN_URL=https://api.github.com/repos/ovn-org/ovn-kubernetes/actions/runs/1722835047/rerun
+ curl --request POST --url https://api.github.com/repos/ovn-org/ovn-kubernetes/actions/runs/1722835047/rerun --header 'authorization: ***' --header 'content-type: application/json'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
{
  "message": "Unable to retry this workflow run because it was created over a month ago",
  "documentation_url": "https://docs.github.com/rest/reference/actions#re-run-a-workflow"
}
~~~

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by andreaskaris** [comment]
For an example of how this works, see: https://github.com/andreaskaris/ovn-kubernetes/pull/21

**Comment by andreaskaris** [comment]
FYI: I think we'll have to pull this into master, see if it all works as expected, and possibly revert. I tested on my branch and it should be o.k. (see the linked PR above), but obviously I might still have introduced some issue.

**Review by trozet — APPROVED** [review]

**Pull request merged**
