### PR TITLE
Rename Smart-NIC to DPU

### PR DESCRIPTION
**Pull request by adrianchiris**
The correct term for such devices is a
data processing unit (DPU) as the hardware
contains general purpose CPU in addition to
networking hardware and offload engines.

The term Smart-NIC is usually referred to NICs
that have some programmable networking logic that
allows it to offload networking rules such as
Openflow rules or Linux TC rules.

A DPU is a Smart-NIC but a Smart-NIC
is not necessarily a DPU.

An example of such NICs that fall in the category of
Smart-NICs but are not DPU:
- Nvidia Mellanox ConnectX network adapters
- Netronome Agilio network adapters
- Intel FPGA based adapters

Note:
As there are no known deployments in production
of OVN-Kubernetes with DPUs both from upstream and
downstream forks e.g for Nvidia/RedHat products, as
well as official release of OVN-Kubernetes with this
change. This commit (for the sake of code simplicitly)
does not include backward compatibiliy for handling
the modified DPU specific pod annotation and
configuration flags.

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by adrianchiris** [comment]
rebased PR.

No logic change in this PR, just rename so dont think CI failure is related.

@girishmg @trozet could you review?

**Comment by adrianchiris** [comment]
@Billy99  this is now rebased.

/cc @girishmg @dcbw 

The changes propsed here are non-backward compatible as we modify flags names and DPU (formerly SmarNIC) related pod annotations. However to my understanding there are no deployments in production that require to maintain backward compatibility.

**Comment by girishmg** [comment]
@adrianchiris I think it is fine to not keep backward compatibility.

**Comment by adrianchiris** [comment]
since we did not merge yet and as sriovnet v1.0.3 [released](https://github.com/Mellanox/sriovnet/releases/tag/v1.0.3), updated the last commit to point to a release version. no other changes to this PR.

**Comment by adrianchiris** [comment]
@trozet @girishmg can we merge ?

**Comment by adrianchiris** [comment]
last push was a rebase against master. no additional changes

**Pull request merged**
