### PR TITLE
Unskip OVS CPU affinity pinning E2Es for IPv6

### PR DESCRIPTION
**Pull request by kyrtapz**

### CODE REVIEW

**Comment by kyrtapz** [comment]
Success: https://github.com/ovn-org/ovn-kubernetes/actions/runs/9268933936/job/25507460184

**Comment by kyrtapz** [comment]
Success: https://github.com/ovn-org/ovn-kubernetes/actions/runs/9272923895/job/25512960035?pr=4407

**Comment by kyrtapz** [comment]
Success: https://github.com/ovn-org/ovn-kubernetes/actions/runs/9283975962/job/25546518001

**Comment by tssurya** [comment]
unrelated timed out failure: https://github.com/ovn-org/ovn-kubernetes/actions/runs/9286115680/job/25553424551?pr=4407

**Review by tssurya — APPROVED** [review]

**Pull request merged**
