### PR TITLE
Increase the retry timer for CI pod ip discovery in e2e

### PR DESCRIPTION
**Pull request by nerdalert**
- Increased the retries for getPodAddress() due to a an observed
  failure in CI.

Signed-off-by: Brent Salisbury <bsalisbu@redhat.com>

**- What this PR does and why is it needed**

This commit is a result of seeing #1385 fail due to  getPodAddress() timing out before the pod IP is retrieved. It adds an additional 15 seconds for pod IP discovery.

**- How to verify it**

By running CI or kubetest locally

**- Description for the changelog**

 Increased the retries for getPodAddress() due to a an observed failure in CI

### CODE REVIEW

**Comment by dave-tucker** [comment]
@nerdalert gonna need a rebase boss as #1389 got in first

**Comment by nerdalert** [comment]
@dave-tucker @trozet @dcbw Couple of adds, mainly added an `AfterEach()` cleanup for #1389 as its failing CI now by not cleaning up a container name that is trying to get reused in later tests (should pass with this). Also renamed the container to avoid any potential future conflicts. Also small adds of matching Dave's const adds for consistency/readability. Ty!

**Comment by trozet** [comment]
failure has nothing to do with this patch, but looks like we might have a bug in network policy again:

[Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [BeforeEach] should enforce egress policy allowing traffic to a server in a different namespace based on PodSelector and NamespaceSelector

**Pull request merged**
