### PR TITLE
Fixes hybrid overlay from deprecated annotation

### PR DESCRIPTION
**Pull request by trozet**
258c5cd16dfea428a53ac5e313b352899170a55c forgot to update the hybrid overlay case of using the annotation.

### CODE REVIEW

**Comment by trozet** [comment]
testing downstream:  https://github.com/openshift/ovn-kubernetes/pull/2242

**Comment by trozet** [comment]
downstream tests passed @npinaeva @qinqon @maiqueb can one of you please review this as its urgent to fix a regresssion seen in downstream merge?

**Review by maiqueb — APPROVED** [review]
looks good afaict.

**Review by qinqon — APPROVED** [review]
all good here too

**Pull request merged**
