### PR TITLE
Fixing EOF error in e2e-cp script

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
**- What this PR does and why is it needed**

CI is broken because of this error.

/cc @aojea 

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by aojea** [comment]
ups sorry, 
how did it get through then?
/lgtm

**Comment by alexanderConstantinescu** [comment]
> ups sorry,
> how did it get through then?
> /lgtm

:shrug:

**Comment by aojea** [comment]
@alexanderConstantinescu :eyes: 
https://github.com/ovn-org/ovn-kubernetes/commit/4d3b1347141d4e5851d28e36883ba72bedea7fee

:upside_down_face:

**Comment by alexanderConstantinescu** [comment]
> @alexanderConstantinescu 
> [4d3b134](https://github.com/ovn-org/ovn-kubernetes/commit/4d3b1347141d4e5851d28e36883ba72bedea7fee)

:+1: :1st_place_medal:

**Pull request merged**
