### PR TITLE
change egressFirewall to be enabled with a cli flag

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
In the last community meeting it was dicussed to transition egressfirewall to be enabled with a cli flag. this is the PR that does that, and it also removes the code that watches the CRDs because it is no longer required 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
@alexanderConstantinescu PTAL when you get the chance

**Comment by alexanderConstantinescu** [comment]
Literally all egress firewall related tests failed in shared GW mode, could you please have a look at that?

```
Summarizing 6 Failures:

[Fail] e2e egress IP validation [It] Should validate the egress IP functionality against remote hosts with egress firewall applied 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/e2e.go:1051

[Fail] e2e egress IP validation [It] Should validate the egress IP functionality against remote hosts with egress firewall applied 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/e2e.go:1051

[Fail] e2e egress firewall policy validation [It] Should validate the egress firewall policy functionality against remote hosts 
/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/leafnodes/runner.go:113

[Fail] e2e egress firewall policy validation [It] Should validate the egress firewall policy functionality against remote hosts 
/home/runner/go/pkg/mod/github.com/onsi/ginkgo@v1.12.0/internal/leafnodes/runner.go:113

[Fail] e2e egress firewall policy validation [It] Should validate the egress firewall DNS does not deadlock when adding many dnsNames 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/e2e.go:1483

[Fail] e2e egress firewall policy validation [It] Should validate the egress firewall DNS does not deadlock when adding many dnsNames 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/e2e.go:1483

Ran 42 of 54 Specs in 3723.766 seconds
FAIL! -- 39 Passed | 3 Failed | 0 Flaked | 0 Pending | 12 Skipped
--- FAIL: TestE2e (3723.77s)
```

**Pull request merged**
