### PR TITLE
Fixes to linkneigh utility methods

### PR DESCRIPTION
**Pull request by gvbalaji**
Fixes to linkneigh utility methods

 1. Fixed LinkNeighAdd to add the binding instead of setting it.
 2.  Added a helper method for LinkNeighSet

### CODE REVIEW

**Comment by gvbalaji** [comment]
@danwinship I've created this separate PR for changes in linkneigh utility methods.

**Comment by girishmg** [comment]
@danwinship @gvbalaji I do not have the complete context of why this change is being proposed, but NeighSet adds the binding if not present or replaces if the existing binding
```
// NeighSet will add or replace an IP to MAC mapping to the ARP table
// Equivalent to: `ip neigh replace....`
func NeighSet(neigh *Neigh) error {
	return pkgHandle.NeighSet(neigh)
}
```

Not all the callers of LinkNeighAdd() do LinkNeighExists() before calling LinkNeighAdd().
The changes as proposed, will break such call sites. Not sure what is wrong with using NeighSet()?

**Comment by danwinship** [comment]
This started with Bala needing the semantics of `netlink.NeighAdd` rather than `netlink.NeighSet` (specifically, to add a new neighbor without removing the old ones) and so he added a new method and called it `LinkNeighAppend`, and I was like, well this is silly, we should rename `LinkNeighAdd` to `LinkNeighSet` since it calls `netlink.NeighSet`, and then add a new `LinkNeighAdd` that actually calls `netlink.NeighAdd`.

But this wasn't supposed to change the semantics of any existing users; all the existing `LinkNeighAdd` callers need to be fixed to call `LinkNeighSet` now instead.

(And I didn't mean you should file a separate *PR* for it, just that you should split the existing PR into multiple commits. So you can merge this back into that PR if you want, or fix the problem with the existing callers and re-push here.)

**Comment by gvbalaji** [comment]
Thanks @girishmg @danwinship for the comments and discussion.
Like @danwinship said, I  think with this change, API semantics are clear and intuitive.

I found two usages of this.
1. In the localnet code that I am changing where we needed to do an add actually
2. In management-port_linux.go , in the method setupManagementPortIPFamilyConfig. In this method it is already calling LinkNeighExists before calling LinkNeighAdd. As per @danwinship 's advice I had also looked at the commit history and verified which IP command it was calling previously before this new utility method( which was ip neigh add). Hence I did not think that needs to be changed

So summary is I did not think existing calls to this need to be changed.  
Please let me know if you think otherwise.

 @danwinship  at this point I'd prefer to keep this a separate PR  if that is ok with you as we are addressing a specific library call here.

**Comment by danwinship** [comment]
> In the localnet code that I am changing where we needed to do an add actually

OK, so if this is a bugfix for `initLocalnetGateway` can you mention that in the commit message?

> In management-port_linux.go, in the method setupManagementPortIPFamilyConfig. In this method it is already calling LinkNeighExists before calling LinkNeighAdd.

Right, OK, so LinkNeighAdd should work there. Right, @girishmg ?

However, this means no one is using `netlink.NeighSet` anywhere, so there's no reason to add `util.LinkNeighSet`. Right?

**Comment by gvbalaji** [comment]
Thanks @danwinship for the review.
I will update the commit message.

As far as "util.LinkNeighSet" method goes, I was thinking while we are at it we can add this method as it is a common library call ( as against a feature in the domain/business logic). This method can be used to replace a binding without making a call to exists. I am tempted to leave it here as it's a useful library call.  Let me know.

**Comment by danwinship** [comment]
No, please remove it. If someone needs it later, it is easy for them to add it later. Right now it's just bloat.

**Comment by gvbalaji** [comment]
@danwinship I removed the method per your suggestion.

**Comment by girishmg** [comment]
@danwinship thanks for providing the context

@gvbalaji consider this case in the gateway_localnet.go
1. LinkNeighAdd() was called and it permanently added the neighbor entry on the host OS
2. the ovnkube-node daemon restarts for whatever reason
3. We make the LinkNeighAdd() again, and we fail since we are not calling the Exists() method.

That was the reason why NeighSet() was used in LinkNeighAdd(), perhaps the function is incorrectly named.

**Comment by gvbalaji** [comment]
Thanks  @girishmg for the comment. I considered this and here were my thoughts.
In the localnet gateway code it's used as a work around. The code adds the entry and in case of any error they are simply logged and processing is not stopped.  So in the case you mentioned if the entry exists we'll see a log message in the log but processing will continue.

Also in case of dual stack we'll need to add multiple entries. I've a separate PR for dual stack there I can add the call to exists if you want me to.

**Comment by girishmg** [comment]
@gvbalaji 
1. those error messages are harmful and in this case it is a false positive. it will unnecessarily trigger alerts if someone is doing log monitoring on error messages
2. can you please at that call site add LinkNeighExists()? or better yet add back the LinkNeighSet() that you initially had. That way we will have both LinkNeighAdd() and LinkNeighSet(), and we use those two functions in the code

**Comment by girishmg** [comment]
@gvbalaji you can address the Exists thing in your other PR #1326 
@danwinship FYI

/lgtm

**Comment by gvbalaji** [comment]
Thanks @girishmg . I have updated my other PR  #1326 with exists method.

**Pull request merged**
