### PR TITLE
Add endpointSlice informer in master process

### PR DESCRIPTION
**Pull request by zshi-redhat**
Signed-off-by: Zenghui Shi <zshi@redhat.com>

### CODE REVIEW

**Comment by girishmg** [comment]
@zshi-redhat why do we need this? The serviceController already creates the endpointSliceInformer  for its own use. Where do we plan to use this?

**Comment by zshi-redhat** [comment]
> @zshi-redhat why do we need this? The serviceController already creates the endpointSliceInformer for its own use. Where do we plan to use this?

@girishmg I'd like to run ovnkube-master and ovnkube-node in single container/process so that it reduces the overall ovnk resource consumption in a small form factor k8s deployment. But I found this nil pointer reference panic for endpointSlice informer:
```
E0926 11:50:34.415187   50547 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 456 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1add9a0?, 0x2f4d090})
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x7fbda7d8c108?})
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1add9a0, 0x2f4d090})
	/usr/lib/golang/src/runtime/panic.go:838 +0x207
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*WatchFactory).GetEndpointSlices(0xc000211570, {0xc0006f3210, 0xd}, {0xc0006f3200, 0xb})
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/factory/factory.go:695 +0x11f
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*nodePortWatcher).SyncServices(0xc0000e33f0, {0xc0004c0840?, 0x4, 0xc0004c0800?})
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/gateway_shared_intf.go:630 +0x2cc
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*gateway).SyncServices(0xc00035b0e0, {0xc0004c0840, 0x4, 0x4})
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/gateway.go:102 +0xb1
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*WatchFactory).addHandler.func2()
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/factory/factory.go:482 +0x4a
k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0x18, 0xc0003b5000})
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:220 +0x1b
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x209b908?, 0xc000052090?}, 0xc000a3dc78?)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:233 +0x57
k8s.io/apimachinery/pkg/util/wait.poll({0x209b908, 0xc000052090}, 0xb8?, 0xb14a85?, 0x18?)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:580 +0x38
k8s.io/apimachinery/pkg/util/wait.PollImmediateWithContext({0x209b908, 0xc000052090}, 0x0?, 0xc000a3dd08?, 0x40da07?)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:526 +0x4a
k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x1d5bd40?, 0xc000268f30?, 0x77000000000e?)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:512 +0x50
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*WatchFactory).addHandler(0xc000211570, {0x20ac1a0?, 0x1d5bd40}, {0x0, 0x0}, {0x0?, 0x0}, {0x209b588, 0xc00002f698}, 0xc001f90720)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/factory/factory.go:481 +0x3ad
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*WatchFactory).AddServiceHandler(0x1c62680?, {0x209b588?, 0xc00002f698?}, 0xc000228960?)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/factory/factory.go:520 +0x4b
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*gateway).Init(0xc00035b0e0, {0x20aab70, 0xc000211570})
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/gateway.go:145 +0x1ad
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*OvnNode).initGateway.func3()
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/gateway_init.go:349 +0x29
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*startupWaiter).Wait.func1(0xc0002285d0)
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/startup-waiter.go:48 +0xcc
created by github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*startupWaiter).Wait
	/go/src/github.com/openshift/ovn-kubernetes/go-controller/pkg/node/startup-waiter.go:42 +0x57
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x16c1d9f]
```

**Comment by zshi-redhat** [comment]
The `NewMasterWatchFactory` is supposed to initialize factory for master-only or master+node processes according to [comment](https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/factory/factory.go#L116). node process could be [using master's watch factory](https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/cmd/ovnkube/ovnkube.go#L265).

**Comment by ggiguash** [comment]
/retitle USHIFT-438: Add endpointSlice informer in master process

**Review by trozet — APPROVED** [review]

**Review by trozet — APPROVED** [review]

**Pull request merged**
