### PR TITLE
master: remove active/passive HA mode

### PR DESCRIPTION
**Pull request by dcbw**
Leaves leader election for the master processes but removes the logical around updating the DB endpoints on the master side, and watching them on the node side.

### CODE REVIEW

**Comment by girishmg** [comment]
@dcbw you need to remove this as well :)
```
	PodIP              string `gcfg:"pod-ip"`
```

**Comment by girishmg** [comment]
@dcbw you need to remove these as well 

1. config.go`PodIP 
2.  ovnkube-master.yaml.j2`OVNKUBE_POD_IP
3.  util/kube.go`ExtractDbRemotesFromEndpoint and validateOVNConfigEndpoint
4.  util/util_test.go -- "test case ExtractDbRemotesFromEndpoint"
5.  kube/kube.go`UpdateEndpoint
6.  node/node_test.go -- "test validateOVNConfigEndpoint()

**Comment by dcbw** [comment]
@girishmg PTAL thanks. I left the CLI and config file options for PodIP since I think they are still being set by scripting and I don't want to make that fail until people have time to update scripts; we'll remove them soon in a different commit though.

**Pull request merged**
