### PR TITLE
[WIP] DNM dummy commit to test CI stability

### PR DESCRIPTION
**Pull request by trozet**
Dummy PR to check CI stability

### CODE REVIEW

**Comment by trozet** [comment]
@aojea @vpickard @tssurya lets see how our CI is looking

**Comment by aojea** [comment]
green green green green :1st_place_medal: 

aswesome work folks,

**Comment by aojea** [comment]
deadlocked here 

```
STEP: Executing a successful http request from the external internet
[It] should provide Internet connection continuously when master is killed
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/e2e_test.go:276
STEP: Running container which tries to connect to 8.8.8.8 in a loop
```

I have a PR for avoid that deadlock https://github.com/ovn-org/ovn-kubernetes/pull/1561

**Comment by trozet** [comment]
thanks @aojea lets try again... consider this one a success

**Comment by trozet** [comment]
```
2020-08-27T22:30:28.3323639Z [91m[1mSummarizing 9 Failures:[0m
2020-08-27T22:30:28.3324291Z 
2020-08-27T22:30:28.3325724Z [91m[1m[Fail] [0m[90m[sig-network] NetworkPolicy [LinuxOnly] [0m[0mNetworkPolicy between server and client [0m[91m[1m[BeforeEach] should enforce policy based on PodSelector and NamespaceSelector [Feature:NetworkPolicy] [0m
2020-08-27T22:30:28.3327159Z [37m/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1522[0m
2020-08-27T22:30:28.3327778Z 
2020-08-27T22:30:28.3329338Z [91m[1m[Fail] [0m[90m[sig-network] NetworkPolicy [LinuxOnly] [0m[0mNetworkPolicy between server and client [0m[91m[1m[BeforeEach] should enforce policy to allow traffic only from a pod in a different namespace based on PodSelector and NamespaceSelector [Feature:NetworkPolicy] [0m
2020-08-27T22:30:28.3330814Z [37m/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1516[0m
2020-08-27T22:30:28.3334552Z 
2020-08-27T22:30:28.3335581Z [91m[1m[Fail] [0m[90m[sig-network] NetworkPolicy [LinuxOnly] [0m[0mNetworkPolicy between server and client [0m[91m[1m[It] should allow egress access to server in CIDR block [Feature:NetworkPolicy] [0m
2020-08-27T22:30:28.3337746Z [37m/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1522[0m
2020-08-27T22:30:28.3337901Z 
2020-08-27T22:30:28.3338913Z [91m[1m[Fail] [0m[90m[sig-network] NetworkPolicy [LinuxOnly] [0m[0mNetworkPolicy between server and client [0m[91m[1m[BeforeEach] should enforce policy based on NamespaceSelector with MatchExpressions[Feature:NetworkPolicy] [0m
2020-08-27T22:30:28.3340049Z [37m/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:64[0m
2020-08-27T22:30:28.3340409Z 
2020-08-27T22:30:28.3342408Z [91m[1m[Fail] [0m[90m[sig-network] NetworkPolicy [LinuxOnly] [0m[0mNetworkPolicy between server and client [0m[91m[1m[BeforeEach] should enforce policy to allow traffic only from a pod in a different namespace based on PodSelector and NamespaceSelector [Feature:NetworkPolicy] [0m
2020-08-27T22:30:28.3343683Z [37m/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1516[0m
2020-08-27T22:30:28.3343822Z 
2020-08-27T22:30:28.3344651Z [91m[1m[Fail] [0m[90m[sig-network] NetworkPolicy [LinuxOnly] [0m[0mNetworkPolicy between server and client [0m[91m[1m[BeforeEach] should allow egress access to server in CIDR block [Feature:NetworkPolicy] [0m
2020-08-27T22:30:28.3345309Z [37m/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1516[0m
2020-08-27T22:30:28.3345432Z 
2020-08-27T22:30:28.3346311Z [91m[1m[Fail] [0m[90m[sig-network] NetworkPolicy [LinuxOnly] [0m[0mNetworkPolicy between server and client [0m[91m[1m[BeforeEach] should enforce policy based on NamespaceSelector with MatchExpressions[Feature:NetworkPolicy] [0m
2020-08-27T22:30:28.3346968Z [37m/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:64[0m
2020-08-27T22:30:28.3347075Z 
2020-08-27T22:30:28.3347947Z [91m[1m[Fail] [0m[90m[sig-network] NetworkPolicy [LinuxOnly] [0m[0mNetworkPolicy between server and client [0m[91m[1m[BeforeEach] should enforce except clause while egress access to server in CIDR block [Feature:NetworkPolicy] [0m
2020-08-27T22:30:28.3348597Z [37m/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:64[0m
2020-08-27T22:30:28.3348717Z 
2020-08-27T22:30:28.3349741Z [91m[1m[Fail] [0m[90m[sig-network] NetworkPolicy [LinuxOnly] [0m[0mNetworkPolicy between server and client [0m[91m[1m[BeforeEach] should enforce except clause while egress access to server in CIDR block [Feature:NetworkPolicy] [0m
2020-08-27T22:30:28.3350451Z [37m/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1516[0m
```

**Comment by trozet** [comment]
A lot of policy errors:
```
[trozet@trozet pods]$ cat ovn-kubernetes_ovnkube-master-7888658d8-qkn44_d90aad4c-339f-4115-ae69-aff4b9b7fbef/ovnkube-master/0.log | grep E0
2020-08-27T22:08:16.696221029Z stderr F E0827 22:08:16.695213      53 policy.go:478] logical port network-policy-2786_client-a-xrz2h not found in cache
2020-08-27T22:08:50.069675893Z stderr F E0827 22:08:50.068919      53 policy.go:785] no pod IPs found on pod client-a-jcv9n: could not find OVN pod annotation in map[]
2020-08-27T22:08:50.102387681Z stderr F E0827 22:08:50.100274      53 policy.go:785] no pod IPs found on pod client-a-jcv9n: could not find OVN pod annotation in map[]
2020-08-27T22:10:02.910039566Z stderr F E0827 22:10:02.909223      53 policy.go:785] no pod IPs found on pod client-a-ffw66: could not find OVN pod annotation in map[]
2020-08-27T22:10:02.932118135Z stderr F E0827 22:10:02.929004      53 policy.go:785] no pod IPs found on pod client-a-ffw66: could not find OVN pod annotation in map[]
2020-08-27T22:10:13.120485491Z stderr F E0827 22:10:13.120395      53 policy.go:478] logical port network-policy-8910_client-b-57wmf not found in cache
2020-08-27T22:10:54.983268527Z stderr F E0827 22:10:54.983168      53 policy.go:478] logical port network-policy-6244_client-cannot-connect-b4nzz not found in cache
2020-08-27T22:12:30.732089951Z stderr F E0827 22:12:30.732003      53 policy.go:785] no pod IPs found on pod client-b-fhp7l: could not find OVN pod annotation in map[]
2020-08-27T22:12:30.739193355Z stderr F E0827 22:12:30.739123      53 policy.go:785] no pod IPs found on pod client-b-fhp7l: could not find OVN pod annotation in map[]
2020-08-27T22:12:41.929667917Z stderr F E0827 22:12:41.929537      53 policy.go:785] no pod IPs found on pod client-b-kbtt9: could not find OVN pod annotation in map[]
2020-08-27T22:12:41.939327756Z stderr F E0827 22:12:41.937000      53 policy.go:785] no pod IPs found on pod client-b-kbtt9: could not find OVN pod annotation in map[]
2020-08-27T22:12:44.86234916Z stderr F E0827 22:12:44.862286      53 policy.go:785] no pod IPs found on pod client-b-x2t2c: could not find OVN pod annotation in map[]
2020-08-27T22:12:44.888671339Z stderr F E0827 22:12:44.888594      53 policy.go:785] no pod IPs found on pod client-b-x2t2c: could not find OVN pod annotation in map[]
2020-08-27T22:12:46.110875513Z stderr F E0827 22:12:46.110632      53 policy.go:478] logical port network-policy-6065_client-a-wckds not found in cache
2020-08-27T22:12:50.241526273Z stderr F E0827 22:12:50.238940      53 policy.go:785] no pod IPs found on pod client-b-9b4rp: could not find OVN pod annotation in map[]
2020-08-27T22:12:50.291737392Z stderr F E0827 22:12:50.291518      53 policy.go:785] no pod IPs found on pod client-b-9b4rp: could not find OVN pod annotation in map[]
2020-08-27T22:12:50.291776092Z stderr F E0827 22:12:50.291649      53 policy.go:478] logical port network-policy-6065_client-b-9b4rp not found in cache
2020-08-27T22:13:35.213096853Z stderr F E0827 22:13:35.213033      53 policy.go:478] logical port network-policy-6611_client-a-dpsbp not found in cache
2020-08-27T22:14:06.293371012Z stderr F E0827 22:14:06.293304      53 policy.go:785] no pod IPs found on pod client-b-m7grp: could not find OVN pod annotation in map[]
2020-08-27T22:14:06.376174228Z stderr F E0827 22:14:06.376114      53 policy.go:785] no pod IPs found on pod client-b-m7grp: could not find OVN pod annotation in map[]
2020-08-27T22:14:26.645574014Z stderr F E0827 22:14:26.645492      53 policy.go:785] no pod IPs found on pod client-a-f5746: could not find OVN pod annotation in map[]
2020-08-27T22:14:26.705349308Z stderr F E0827 22:14:26.705283      53 policy.go:785] no pod IPs found on pod client-a-f5746: could not find OVN pod annotation in map[]
2020-08-27T22:17:06.659423481Z stderr F E0827 22:17:06.659202      53 policy.go:478] logical port network-policy-7148_pod-a-qmxf5 not found in cache
2020-08-27T22:17:09.195056635Z stderr F E0827 22:17:09.195001      53 policy.go:478] logical port network-policy-2980_client-a-r5q4z not found in cache
2020-08-27T22:17:16.968341588Z stderr F E0827 22:17:16.968234      53 policy.go:785] no pod IPs found on pod pod-b-57vrt: could not find OVN pod annotation in map[]
2020-08-27T22:17:16.978174804Z stderr F E0827 22:17:16.977921      53 policy.go:785] no pod IPs found on pod pod-b-57vrt: could not find OVN pod annotation in map[]
2020-08-27T22:17:57.485866698Z stderr F E0827 22:17:57.485772      53 policy.go:478] logical port network-policy-2980_client-a-xpsk2 not found in cache
```

**Comment by trozet** [comment]
On ovn-worker2 I can see a lot of:
```
I0827 22:18:01.566402    1176 cni.go:157] [network-policy-1432/client-can-connect-80-vcx5t] CNI request &{ADD network-policy-1432 client-can-connect-80-vcx5t a275eeccbb21325d379cf6f7b458ee9719fc6bd73a314928580dffade174d024 /var/run/netns/cni-31694819-b8dd-347c-b284-2d7fba8b9900 eth0 0xc0004d8d00}, result "", err failed to configure pod interface: timed out waiting for pod flows for pod: client-can-connect-80-vcx5t, error: timed out waiting for the condition
```

In fact, every time out on that node is a network policy pod, and there are 0 occurrences of it on ovn-worker.

Now looking at the ovn-controller logs I can see we hit the Null OVSDB write:
2020-08-27T22:17:13.033Z|00366|util|EMER|lib/ovsdb-idl.c:4612: assertion row->new_datum != NULL failed in ovsdb_idl_txn_write__()

@dceara

**Comment by dceara** [comment]
@trozet I assume I can just run the test locally with kind, right? That should help pinpoint the issue in ovn-controller.

**Comment by aojea** [comment]
> @trozet I assume I can just run the test locally with kind, right? That should help pinpoint the issue in ovn-controller.

yes @dceara , ping me directly in slack or irc if you need help with the setup and on how to run the test locally

**Comment by dceara** [comment]
> > @trozet I assume I can just run the test locally with kind, right? That should help pinpoint the issue in ovn-controller.
> 
> yes @dceara , ping me directly in slack or irc if you need help with the setup and on how to run the test locally

Thanks, I managed to replicate the crash locally once. Retrying now with gdb attached to the ovn-controllers, I'll update the [OVN BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1871961) when I know more.

**Pull request closed without merging**
