### PR TITLE
Dont Add NodePort related iptable rules on the DPU 

### PR DESCRIPTION
**Pull request by Pardhakeswar**
Signed-off-by: Pardhakeswar Pacha <ppacha@nvidia.com>

### CODE REVIEW

**Comment by Pardhakeswar** [comment]
@adrianchiris @girishmg @astoycos PTAL

**Comment by girishmg** [comment]
@dcbw I am not sure if this fix is complete yet.

@Pardhakeswar @adrianchiris  we need those IPtable rules on the Smart NIC Host, right?


For example:

If someone is on the Smart NIC Host (with IP NodeIP) and they run `nc -zv NodeIP:NodePort` without IP table rules the packet will not be forwarded.

**Comment by astoycos** [comment]
@girishmg  In smart nic host we make a different watcher exclusively for IPtables (https://github.com/ovn-org/ovn-kubernetes/blob/ae75f9f989526203212c836dfc1b3a40866da57b/go-controller/pkg/node/gateway_init.go#L420) 

and the accompanying watcher functions starting at 

https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/node/gateway_shared_intf.go#L613 


It's a bit confusing since we're overloading functionality.... 

Full mode and SmartNic Mode both use the standard `nodePortWatcher` 

SmartNic Host Mode use the special `nodeportWatcherIptables`

**Pull request merged**
