### PR TITLE
[libovsdb] Run libovsdb modelgen on latest OVN NB schema

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
This commit bumps libovsdb's model to a more recent OVN NB DB schema version which contains elements such as `LogicalRouterPolicy.Nexthops` and such. 

/assign @jcaamano 

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by dave-tucker** [comment]
@jcaamano yes but it's still waiting review https://github.com/ovn-org/libovsdb/pull/204

**Comment by jcaamano** [comment]
I will give it a shot but I guess @amorenoz needs to look at it as well.

/lgtm

**Comment by alexanderConstantinescu** [comment]
External GW e2e tests seem to be one fire:

https://github.com/ovn-org/ovn-kubernetes/pull/2373/checks?check_run_id=3193448320
```


Summarizing 3 Failures:

[Fail] BFD e2e non-vxlan external gateway through a gateway pod Should validate TCP/UDP connectivity to an external gateway's loopback address via a pod with external gateway annotations enabled [It] TCP ipv6 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/external_gateways.go:982

[Fail] BFD e2e multiple external gateway validation Should validate TCP/UDP connectivity to multiple external gateways for a UDP / TCP scenario [It] IPV6 udp 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/external_gateways.go:788

[Fail] BFD e2e multiple external gateway validation Should validate TCP/UDP connectivity to multiple external gateways for a UDP / TCP scenario [It] IPV6 udp 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/external_gateways.go:788
```

https://github.com/ovn-org/ovn-kubernetes/pull/2373/checks?check_run_id=3193448419

```
Summarizing 2 Failures:

[Fail] BFD e2e non-vxlan external gateway through a gateway pod Should validate TCP/UDP connectivity to an external gateway's loopback address via a pod with external gateway annotations enabled [It] UDP ipv6 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/external_gateways.go:572

[Fail] BFD e2e non-vxlan external gateway through a gateway pod Should validate TCP/UDP connectivity to an external gateway's loopback address via a pod with external gateway annotations enabled [It] UDP ipv6 
/home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/external_gateways.go:572
```

**Pull request merged**
