### PR TITLE
vhost-vDPA support

### PR DESCRIPTION
**Pull request by lmilleri**
The current PR introduces support for vhost-vDPA devices.

There are 2 main changes:

1)  DeviceInfo support on ovn-k
See deviceInfo spec at https://github.com/k8snetworkplumbingwg/device-info-spec
This commit is required for introducing vhost-vdpa

2) vhost-vDPA device support

Please make sure to merge this PR first: https://github.com/ovn-org/ovn-kubernetes/pull/3868

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
lgtm

**Review by trozet — APPROVED** [review]

**Comment by SalDaniele** [comment]
Hi @lmilleri, I am running our CI jobs for smartNics and we are seeing sriov pods fail to start up with this change with the following error in oc describe. Any ideas for where we should start to resolve this?

```
  Warning  FailedCreatePodSandBox  10s  kubelet  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_test-sriov-pod_default_12194f6e-96ea-4255-be89-a05c57e7d85b_0(6cd270896bffa12a4a8bd6513072a4bc1aac1684a090603dd77920cc3b01a003): error adding pod default_test-sriov-pod to CNI network "multus-cni-network": plugin type="multus-shim" name="multus-cni-network" failed (add): CmdAdd (shim): CNI request failed with status 400: '&{ContainerID:6cd270896bffa12a4a8bd6513072a4bc1aac1684a090603dd77920cc3b01a003 Netns:/var/run/netns/de460fa1-907f-47b0-becc-82a7176df010 IfName:eth0 Args:IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=test-sriov-pod;K8S_POD_INFRA_CONTAINER_ID=6cd270896bffa12a4a8bd6513072a4bc1aac1684a090603dd77920cc3b01a003;K8S_POD_UID=12194f6e-96ea-4255-be89-a05c57e7d85b Path: StdinData:[123 34 98 105 110 68 105 114 34 58 34 47 118 97 114 47 108 105 98 47 99 110 105 47 98 105 110 34 44 34 99 104 114 111 111 116 68 105 114 34 58 34 47 104 111 115 116 114 111 111 116 34 44 34 99 108 117 115 116 101 114 78 101 116 119 111 114 107 34 58 34 47 104 111 115 116 47 114 117 110 47 109 117 108 116 117 115 47 99 110 105 47 110 101 116 46 100 47 49 48 45 111 118 110 45 107 117 98 101 114 110 101 116 101 115 46 99 111 110 102 34 44 34 99 110 105 67 111 110 102 105 103 68 105 114 34 58 34 47 104 111 115 116 47 101 116 99 47 99 110 105 47 110 101 116 46 100 34 44 34 99 110 105 86 101 114 115 105 111 110
34 58 34 48 46 51 46 49 34 44 34 100 97 101 109 111 110 83 111 99 107 101 116 68 105 114 34 58 34 47 114 117 110 47 109 117 108 116 117 115 47 115 111 99 107 101 116 34 44 34 103 108 111 98 97 108 78 97 109 101 115 112 97 99 101 115 34 58 34 100 101 102 97 117 108 116 44 111 112 101 110 115 104 105 102 116 45 109 117 108 116 117 115 44 111 112 101 110 115 104 105 102 116 45 115 114 105 111 118 45 110 101 116 119 111 114 107 45 111 112 101 114 97 116 111 114 34 44 34 108 111 103 76 101 118 101 108 34 58 34 118 101 114 98 111 115 101 34 44 34 108 111 103 84 111 83 116 100 101 114 114 34 58 116 114 117 101 44 34 109 117 108 116 117 115 65 117 116 111 99 111 110 102 105 103 68 105 114 34 58 34 47 104 111 115 116 47 114 117 110 47
109 117 108 116 117 115 47 99 110 105 47 110 101 116 46 100 34 44 34 109 117 108 116 117 115 67 111 110 102 105 103 70 105 108 101 34 58 34 97 117 116 111 34 44 34 110 97 109 101 34 58 34 109 117 108 116 117 115 45 99 110 105 45 110 101 116 119 111 114 107 34 44 34 110 97 109 101 115 112 97 99 101 73 115 111 108 97 116 105 111 110 34 58 116 114 117 101 44 34 112 101 114 78 111 100 101 67 101 114 116 105 102 105 99 97 116 101 34 58 123 34 98 111 111 116 115 116 114 97 112 75 117 98 101 99 111 110 102 105 103 34 58 34 47 118 97 114 47 108 105 98 47 107 117 98 101 108 101 116 47 107 117 98 101 99 111 110 102 105 103 34 44 34 99 101 114 116 68 105 114 34 58 34 47 101 116 99 47 99 110 105 47 109 117 108 116 117 115 47 99 101 114 116 115 34 44 34 99 101 114 116 68 117 114 97 116 105 111 110 34 58 34 50 52 104 34 44 34 101 110 97 98 108 101 100 34 58 116 114 117 101 125 44 34 115 111 99 107 101 116 68 105 114 34 58 34 47 104 111 115 116 47 114 117 110 47 109 117 108 116 117 115 47 115 111 99 107 101 116 34 44 34 116 121 112 101 34 58 34 109 117 108 116 117 115 45 115 104 105 109 34 125]} ContainerID:"6cd270896bffa12a4a8bd6513072a4bc1aac1684a090603dd77920cc3b01a003" Netns:"/var/run/netns/de460fa1-907f-47b0-becc-82a7176df010" IfName:"eth0" Args:"IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=test-sriov-pod;K8S_POD_INFRA_CONTAINER_ID=6cd270896bffa12a4a8bd6513072a4bc1aac1684a090603dd77920cc3b01a003;K8S_POD_UID=12194f6e-96ea-4255-be89-a05c57e7d85b" Path:"" ERRORED: error configuring pod [default/test-sriov-pod] networking: [default/test-sriov-pod/12194f6e-96ea-4255-be89-a05c57e7d85b:ftnetattach]: error adding container to network "ftnetattach": failed to send CNI request: Post "http://dummy/": EOF

```

```
apiVersion: v1                                                                                                                                                                         
kind: Pod                                                                                                                                                                              
metadata:                                                                                                                                                                              
  name: ft-iperf-server-pod-v4                                                                                                                                                         
  namespace: default                                                                                                                                                                   
  annotations:                                                                                                                                                                         
    v1.multus-cni.io/default-network: default/ftnetattach                                                                                                                              
  labels:                                                                                                                                                                              
    pod-name: ft-iperf-server-pod-v4                                                                                                                                                   
spec:                                                                                                                                                                                  
  containers:
  - name: ft-iperf-server-pod-v4
    image: quay.io/wizhao/ft-base-image:0.8-x86_64
```

**Comment by SalDaniele** [comment]
cc/ @wizhaoredhat

**Comment by lmilleri** [comment]
@SalDaniele @wizhaoredhat Is the ovn-kube log telling anything more? Just a speculation, could it be a json serialization problem when not passing the deviceInfo param in the network attachment definition?
Maybe something like `json:"deviceInfo,omitempty"` is missing at line https://github.com/ovn-org/ovn-kubernetes/blob/9ccf859d9816cc55654dc394d2e82340cd33cfec/go-controller/pkg/cni/types.go#L84?

This is an example of NAD:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-kubernetes-a
  namespace: vdpa
  annotations:
    k8s.v1.cni.cncf.io/resourceName: openshift.io/mlxnics
spec:
  config: |2 
      { "cniVersion": "0.3.1", 
        "name": "l2-network", 
        "type": "ovn-k8s-cni-overlay", 
        "capabilities" : {"CNIDeviceInfoFile": true}, 
        "topology":"localnet", 
        "subnets": "10.100.200.0/24", 
        "vlanID": 33,
        "mtu": 1300, 
        "netAttachDefName": "vdpa/ovn-kubernetes-a", 
        "excludeSubnets": "10.100.200.0/29" 
      }
```

with the additional capability.
I thought that was optional.

I'll be back to work on Thursday and I'll have a look to it first thing.
Thanks

**Comment by jcaamano** [comment]
Consider this change also as a possible reason

https://github.com/ovn-org/ovn-kubernetes/pull/3844

**Comment by lmilleri** [comment]
On a second thought, I'm quite sure the problem is due to a last minute change in the govdpa library.
Basically no error is now returned by the library if no vdpa device is found with the given pci address.  (previously an error was returned)
This PR should fix the problem:
https://github.com/ovn-org/ovn-kubernetes/pull/3987

**Comment by SalDaniele** [comment]
Hi @lmilleri thanks for taking a look, I verified this PR fixes the problem

**Pull request merged**
