### PR TITLE
[Contrib] Add Ubuntu 18.04 support

### PR DESCRIPTION
**Pull request by aserdean**
This PR updates the OVS/OVN versions to 2.10, adds support for Ubuntu 18.04, deprecates support for Ubuntu 14.04.

Unfortunately Ubuntu 18.04 comes with `netplan` builtin. This causes issues when deploying it as a gateway, because the DNS settings are not copied from the physical interface to the OVS bridge. Until support is added, 18.04 minions will be forced with a gateway configuration.

This PR contains the following commits:
-   [ansible] Switch to ovn-org links
-   [contrib] Bump OVS linux version to 2.10
-   [contrib] Add 18.04 to the supported list and deprecate 14.04
-   [contrib] Bump OVS installer to 2.10 on Windows
-   [contrib] Linux add new dependency needed to compile OVS
-   [contrib] Change order when installing debs
-   [contrib] Set init_gateway to false by default on Ubuntu 18.04 nodes

CC: @ionutbalutoiu @alinbalutoiu

### CODE REVIEW

**Comment by dcbw** [comment]
Looks OK to me; @shettyg @girishmg ?

**Comment by shettyg** [comment]
Alin may be expecting the CC'd members in the first message to test it. If not, /lgtm

**Comment by alinbalutoiu** [comment]
Can you make ``init_gateway`` default to false on Ubuntu 18.04? That would be going here: https://github.com/ovn-org/ovn-kubernetes/blob/master/contrib/roles/linux/kubernetes/tasks/prepare_minion.yml#L114-L117
Something like:
```
- block:
  - set_fact:
      init_gateway: true
    when: ansible_distribution_version == '16.04'
  - set_fact:
      init_gateway: false
    when: ansible_distribution_version == '18.04'
  when: init_gateway is not defined

- fail:
    msg: "Gateway not supported yet on Ubuntu 18.04"
  when: init_gateway == true and ansible_distribution_version == '18.04'
```
Which would fail if the user sets intentionally the init_gateway to true for Ubuntu 18.04.

The rest looks good to me, I'll give it a try with Ubuntu 18.04.

**Comment by aserdean** [comment]
> Which would fail if the user sets intentionally the init_gateway to true for Ubuntu 18.04.
> 
> The rest looks good to me, I'll give it a try with Ubuntu 18.04.

Thanks for the suggestion @alinbalutoiu , I folded in the changes. Please let me know if you managed to test it.

**Comment by ionutbalutoiu** [comment]
/LGTM

I just tested these changes on a deployment with:

* K8s master
* K8s slave 1 (Ubuntu 16.04) with gateway enabled
* K8s slave 2 (Ubuntu 18.04) with gateway disabled

Everything worked as expected.

**Pull request merged**
