### PR TITLE
regression: logical_router_port mac address is case sensitive

### PR DESCRIPTION
**Pull request by girishmg**
when we moved all the MAC address from string to net.HardwareAddr it
had a side effect. the String() function of that struct always returns
the MAC address with lower case letters. however, before that move the
MAC addresses were all upper case.

so, when you upgrade a cluster to the latest ovn-k8s code the
ovnkube-master doesn't come up and errors out with the following error

-----8<------
port already exists with mac 0A:58:64:40:8B:09\n", error: OVN command
'/usr/bin/ovn-nbctl lrp-add GR_node1 rtoj-GR_node1 0a:58:64:40:8b:09
100.64.139.9/29'
-----8<------

this commit, for short term, deletes the logical router port and adds
it back so that all the ports going forward will have MAC address that
has lower case letters.

upon upgrading a cluster to this commit ovnkube-master will delete the
the existing port with upper case MAC address and add it back with
lower case MAC address. on subsequent restarts of the ovnkube-master,
the lrp-del followed by lrp-add will be a no-op.

eventually, we can remove this commit.

@ovn-org/ovn-kubernetes-committers

### CODE REVIEW

**Comment by dcbw** [comment]
FWIW I filed https://bugzilla.redhat.com/show_bug.cgi?id=1829059 to fix this in OVN

**Comment by danwinship** [comment]
> eventually, we can remove this commit.

When, exactly? We don't have releases so it's hard to say "we'll keep this for 2 releases"...

> on subsequent restarts of the ovnkube-master, the lrp-del followed by lrp-add will be a no-op.

well, no, it's not a no-op, it temporarily drops all traffic to/from the node, doesn't it?

Can't we just add a hack to uppercasify the MAC in this case? (And then, once we depend on a version of OVN with the case-sensitivity fixed, we can remove that hack.)

**Comment by danwinship** [comment]
> (And then, once we depend on a version of OVN with the case-sensitivity fixed, we can remove that hack.)

ok, fine, so I answered my own question about how long we need to keep either hack :slightly_smiling_face:

**Comment by girishmg** [comment]
> > on subsequent restarts of the ovnkube-master, the lrp-del followed by lrp-add will be a no-op.
> 
> well, no, it's not a no-op, it temporarily drops all traffic to/from the node, doesn't it?

@danwinship It doesn't. I tested it.

On one of the hypervisor node, I did this.
$ ovs-appctl -t ovn-controller vlog/set file:dbg:jsonrpc
$ tail -f /var/log/messages/ovn-controller.log

With the MAC initially being 0A:58:64:40:02:03  I did this

Iteration -1:
$ ovn-nbctl lrp-del rtoj-GR_node1 -- lrp-add GR_node1 rtoj-GR_node1 0a:58:64:40:02:03 100.64.2.3/29

In ovn-controller.log, I saw this

```
2020-04-27T19:05:20.969Z|00183|jsonrpc|DBG|tcp:10.0.2.16:6642: received notification, method="update3", params=[["monid","OVN_Southbound"],"311d9482-b093-44de-8bb7-cca81e884473",{"Port_Binding":{"f80a184f-4c91-41d1-b74c-e8500de03190":{"modify":{"mac":["set",["0A:58:64:40:02:03 100.64.2.3/29","0a:58:64:40:02:03 100.64.2.3/29"]]}}}}]
```

I re-ran `lrp-del followed by lrp-add`

Iteration-2:
$ ovn-nbctl lrp-del rtoj-GR_node1 -- lrp-add GR_node1 rtoj-GR_node1 0a:58:64:40:02:03 100.64.2.3/29

In ovn-controller.log, I didn't see any `update` RPC callback to the local hypervisor as it relates to above change

Iteration-3:
Repeated the lrp-del and lrp-add .. no JSON RPC message in ovn-controller.log

So, this led me to believe that ovn-controller is not going to recompute OpenFlow rules.

Between the iteration-{1,2,3} the br-int's OpenFlow rules corresponding to the MAC address didn't change at all. The `idle_time` on them were still a large number suggesting that it was not recently created.

FWIW, the openflow rules all use lower case MAC address. I didn't see any change to OpenFlow rules when I did the Iteration-1.

**Comment by danwinship** [comment]
ah, right, we encountered something similar before with `ovs-vsctl del-br ... -- add-br ...` not behaving the same as `ovs-vsctl del-br ...; ovs-vsctl add-br ...` (https://github.com/openshift/origin/pull/18634)

**Pull request merged**
