### PR TITLE
check endpoints annotations for idling

### PR DESCRIPTION
**Pull request by aojea**
It turns out that the idling feature annotate the Endpoints of the
Service, and we were looking for the annotations on the Service,
hence we always inserted the reject ACL.

Another important thing to take into consideration is that Kubernetes
is moving to use EndpointSlices instead of Endpoints, in order to make
the transition easier, we just pass the annotations only to the function
that detects if we should install a reject ACL, this way we remove
the dependency on the object type.

Signed-off-by: Antonio Ojea <aojea@redhat.com>

### CODE REVIEW

**Comment by dcbw** [comment]
@aojea code looks good, but the tests fail now:

```

Summarizing 2 Failures:

[Panic!] OVN Namespace Operations on startup [It] reconciles an existing service 
/opt/hostedtoolcache/go/1.15.5/x64/src/runtime/panic.go:212

[Panic!] OVN Namespace Operations on startup [It] reconciles a deleted service 
/opt/hostedtoolcache/go/1.15.5/x64/src/runtime/panic.go:212
```

**Comment by aojea** [comment]
> @aojea code looks good, but the tests fail now:

fixed, I wasn't protecting against nil objects, my fault :(

**Comment by dcbw** [comment]
@aojea can you rebase? Otherwise LGTM

**Comment by aojea** [comment]
/hold
is not clear the path forward for this feature

**Comment by aojea** [comment]
/retest

anyway, if we need to make it work for old versions we have to use Endpoints

**Comment by aojea** [comment]
it seems ovn always used annotations in service, and its own annotations, so I think that this behavior is correct

**Pull request closed without merging**
