### PR TITLE
Manage and update the gateway OpenFlow rules using flow cache

### PR DESCRIPTION
**Pull request by cathy-zhou**
Signed-off-by: Yun Zhou <yunz@nvidia.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by cathy-zhou** [comment]
//retest

**Review by trozet — APPROVED** [review]
sorry for the delay. Awesome work @cathy-zhou  !

**Pull request merged**
