### PR TITLE
Port downstream fedora image changes

### PR DESCRIPTION
**Pull request by pecameron**
Add the iptables-scripts/ ipwrappers to the fedora image.

Signed-off-by: Phil Cameron <pcameron@redhat.com>

### CODE REVIEW

**Comment by pecameron** [comment]
@dcbw @squeed @girishmg @shettyg PTAL

**Comment by squeed** [comment]
This won't work unless you also update the daemonset to mount `/host`.

**Comment by pecameron** [comment]
@squeed Does this not work at all or just reverts to iptables in the image? Will upstream testing on 3.11 work? The actual test on aws uses the yaml from cno.

**Comment by squeed** [comment]
It won't work at all.

This is really an openshift-ism that I don't think *needs* to go upstream. If others want it, that's fine. But it's our own local bubble of weirdness.

**Comment by pecameron** [comment]
Can't work upstream, required downstream. Just closing this PR.

**Pull request closed without merging**
