### PR TITLE
Support for dual stack in addRoutesGatewayIP method for other default gateway

### PR DESCRIPTION
**Pull request by gvbalaji**
Support for dual stack in addRoutesGatewayIP for other default gateway.
Not sure if this is what you expected @dcbw.

Signed-off-by: Balaji Varadaraju <bvaradar@redhat.com>
cc : @dcbw @danwinship

### CODE REVIEW

**Comment by danwinship** [comment]
This isn't quite right; there's only a single `hybridOverlayExternalGW` value, so we can't set up routing correctly in dual-stack clusters. We should probably just fix it so that you're not allowed to set `config.HybridOverlay.Enabled` in dual-stack clusters for now

**Comment by dcbw** [comment]
@danwinship sure, that works for me. But in the non-hybrid case for secondary OVN networks we'd still want dual-stack-capability, and that also uses this function.

**Comment by gvbalaji** [comment]
thanks @danwinship @dcbw . Can you please let me know how does the code changes look for the secondary network dual stack case?

**Comment by dcbw** [comment]
@gvbalaji actually I thought it was fine the way it was :)

**Pull request merged**
