### PR TITLE
test: enable dualstack HA local gateway CI

### PR DESCRIPTION
**Pull request by danwinship**
probably did this wrong, but...

### CODE REVIEW

**Comment by danwinship** [comment]
@aojea 
```
2020-09-22T15:40:19.2412274Z + kind create cluster --name ovn --kubeconfig /home/runner/admin.conf --image kindest/node:v1.19.0 --config=./kind.yaml
2020-09-22T15:40:19.2414355Z ERROR: failed to create cluster: [invalid podSubnet: invalid CIDR address: 10.244.0.0/16,fd00:10:244::/48, invalid serviceSubnet: invalid CIDR address: 10.96.0.0/16,fd00:10:96::/112]
2020-09-22T15:40:19.2416205Z make: *** [install-kind] Error 1
```

**Comment by aojea** [comment]
> @aojea
> 
> ```
> 2020-09-22T15:40:19.2412274Z + kind create cluster --name ovn --kubeconfig /home/runner/admin.conf --image kindest/node:v1.19.0 --config=./kind.yaml
> 2020-09-22T15:40:19.2414355Z ERROR: failed to create cluster: [invalid podSubnet: invalid CIDR address: 10.244.0.0/16,fd00:10:244::/48, invalid serviceSubnet: invalid CIDR address: 10.96.0.0/16,fd00:10:96::/112]
> 2020-09-22T15:40:19.2416205Z make: *** [install-kind] Error 1
> ```

The dual stack jobs need an "special kind" :smile: 
https://github.com/ovn-org/ovn-kubernetes/blob/e37c2d9ec3b85c720dc4cc27054def1f4ab0b2ee/.github/workflows/test_periodic.yml#L185-L187

**Comment by aojea** [comment]
so, it seems the hacky solution untile we support dual stack in kind should we to modify the install kind script to install an additional binary, 

```
sudo curl -Lo /usr/local/bin/kind https://github.com/aojea/kind/releases/download/dualstack/kind
```
and ping the kind.sh script to it if is dual stack

@danwinship I can do it tomorrow my morning if you don't want to spend time on this

**Comment by aojea** [comment]
We should have them running first in the periodic https://github.com/ovn-org/ovn-kubernetes/pull/1702 
they were not passing and timing out, but they were also running with k8s 1.18.

**Comment by aojea** [comment]
superseded by https://github.com/ovn-org/ovn-kubernetes/pull/1742

**Pull request closed without merging**
