### PR TITLE
Add a GitHub Action To Re-Test PR's

### LINKED ISSUE #1216: Create github action trigger to re-run CI on PRs
I've tried:

name: Go
on:
push:
pull_request:
pull_request_review_comment:
types:
- created

And then in under the jobs doing:
verify:
name: Verify
runs-on: ubuntu-latest
if: github.event_name == 'pull_request' || github.event_name == 'push' || github.event.pull_request_review_comment.comment.body == '/retest'

but it doesn't seem to trigger.

### PR DESCRIPTION
**Pull request by dave-tucker**
Fixes #1216 

Before this merges someone with admin on this repo will need to:

1. Create a `ovn-robot` GitHub User and grant them `write` access to this repo.
2. Create a Personal Access Token with `repo` scope and add it as a secret called `REPO_ACCESS_TOKEN` ([docs](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets))

Once it's merged, a comment with `/retest` will attempt to re-run the the CI workflow.
This could fail if, for example, the tests were all green - GH doesn't allow you to re-run in that case.
Or perhaps for other reasons that we'll find out later.

If it was successful, the action will add a :rocket: to the comment.

### CODE REVIEW

**Comment by dave-tucker** [comment]
Example PR against my fork with this enabled: https://github.com/dave-tucker/ovn-kubernetes/pull/1
Only the last 2 comments are really relevant - the rest was just debugging.

**Comment by vjayaramrh** [comment]
@dave-tucker thanks for this PR, if /retest works, it would save everyone a lot of time

**Comment by trozet** [comment]
nice @dave-tucker 
@dcbw I created @ovn-robot can you please invite him with write access? I don't have permission. I guess you will also have to do step 2.

**Comment by dcbw** [comment]
@trozet invited

**Pull request merged**
