### PR TITLE
bump kubernetes version to v1.19.0

### PR DESCRIPTION
**Pull request by aojea**
Kubernetes v1.19.0 was released with lot of fixes and efforts in stabilization of the code.
We should use it in our CI
xref: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md

Signed-off-by: Antonio Ojea <aojea@redhat.com>

### CODE REVIEW

**Comment by aojea** [comment]
@trozet this is the next challenge once we stabilize with 1.18.2

1.19.0 has much more tests, this is failing constantly in 2 different PRs
```
Summarizing 2 Failures:

[Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [It] should ensure an IP overlapping both IPBlock.CIDR and IPBlock.Except is allowed [Feature:NetworkPolicy] 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1821

[Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [It] should ensure an IP overlapping both IPBlock.CIDR and IPBlock.Except is allowed [Feature:NetworkPolicy] 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/network_policy.go:1821
```

@vpickard you are looking at the network policy, can you checkout this PR and start using 1.19 for testing?

**Comment by vpickard** [comment]
@aojea Yes, I will do that and debug the test.

**Comment by danwinship** [comment]
> [Fail] [sig-network] NetworkPolicy [LinuxOnly] NetworkPolicy between server and client [It] should ensure an IP overlapping both IPBlock.CIDR and IPBlock.Except is allowed [Feature:NetworkPolicy]

That test was specifically added to make ovn-kubernetes fail because our implementation of `IPBlock.Except` is incorrect (#845).

**Comment by trozet** [comment]
@aojea can you please skip those tests for now with the github issue referenced and lets see what happens? I also see jobs timing out.

**Comment by aojea** [comment]
heh, our conntrack friend

```
[Fail] [sig-network] Conntrack [It] should be able to preserve UDP traffic when server pod cycles for a NodePort service 
/home/runner/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/conntrack.go:195
```

**Comment by aojea** [comment]
ok, here we go, ipv6 shared ha breaks with the upgrade timing out the job :eye:

**Comment by aojea** [comment]
> ok, here we go, ipv6 shared ha breaks with the upgrade timing out the job

I think that is the same bug we had in kind, that the istio people reported recently, we are going to release a new stable version soon, that seems a good timing :)

**Comment by aojea** [comment]
ok, this is better, we are almost there

**Comment by aojea** [comment]
Yay, all green, let's be sure
/retest

**Comment by aojea** [comment]
2/2 Green

This should be good to go @trozet

**Pull request merged**
