### PR TITLE
Remove stale chassis for hosts that run ovnkube-node on DPU

### PR DESCRIPTION
**Pull request by pliurh**
As the community decided to not add any DB client to the node, this patch uses 'ovn-sbctl' to do the same job.

**- What this PR does and why is it needed**
In the DPU 2-clusters design, a host with DPU will join the cluster
with ovn-controller running in the host first, then it will be moved
to the DPU. Therefore, we will have 2 chassis with the same hostname
in the ovn sbdb.

With this patch, the master will try to remove the stale chassis when
the Chassis ID is inconsistent with the value of  node annotation
'k8s.ovn.org/node-chassis-id'.

This is to fix #3026.

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by trozet — CHANGES_REQUESTED** [review]
we cant use sbctl either, the nodes should have no access to the DBs. Need to find a way to do this from ovnkube-master

**Comment by zshi-redhat** [comment]
> we cant use sbctl either, the nodes should have no access to the DBs. Need to find a way to do this from ovnkube-master

Shall we delete stale chassis in the periodic sync: https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/ovn/master.go#L1158? Not ideal since it is not deleted immediately, but it should fix the issue by accessing DB from master.

**Comment by pliurh** [comment]
> we cant use sbctl either, the nodes should have no access to the DBs. Need to find a way to do this from ovnkube-master

But we use `RunOVNSbctl` elsewhere in the node code, like https://github.com/ovn-org/ovn-kubernetes/blob/eeef0175d948852fd67ff42a1ad6ed2956b92267/go-controller/pkg/node/node.go#L229

As a node with DPU, it can just remove the chassis with the Encap which is using its own IP if it's running in `dpu-host` mode. How can the master decide which chassis shall be removed if chassis_name duplication is detected?

**Comment by zshi-redhat** [comment]
@pliurh  @trozet  May I ask to first revert the previous commit, then work on the final fix in a follow up PR if we cannot have an agreement on the final fix by end of this week? The reason is that it is currently blocking hypershift from testing the latest 4.12 bits.

**Comment by pliurh** [comment]
The previous commit has been reverted by https://github.com/ovn-org/ovn-kubernetes/pull/3103

**Comment by girishmg** [comment]
> But we use `RunOVNSbctl` elsewhere in the node code, like
> 
> https://github.com/ovn-org/ovn-kubernetes/blob/eeef0175d948852fd67ff42a1ad6ed2956b92267/go-controller/pkg/node/node.go#L229
> 
> As a node with DPU, it can just remove the chassis with the Encap which is using its own IP if it's running in `dpu-host` mode. How can the master decide which chassis shall be removed if chassis_name duplication is detected?

Yes, this is unfortunate. However, let's not continue that mistake to other places. Running `ovn-sbctl` in large-scale cluster is expensive and often the command timeouts if the DB is large.

**Comment by girishmg** [comment]
> How can the master decide which chassis shall be removed if chassis_name duplication is detected?

You can use `k8s.ovn.org/node-chassis-id` node annotation

```
k8s.ovn.org/node-chassis-id: 40026017-0c08-4b69-af9e-a927e8e02a34
# ovs-vsctl get open . external_ids:system-id
"40026017-0c08-4b69-af9e-a927e8e02a34"
```

**Comment by pliurh** [comment]
@girishmg Thanks for your clarification. I'll refactor this PR.

**Comment by pliurh** [comment]
@girishmg @trozet PTAL

**Review by trozet — APPROVED** [review]

**Pull request merged**
