### PR TITLE
attempting to reduce cardinality in the interest of memory performance

### PR DESCRIPTION
**Pull request by kedark3**
`resource_update_latency_seconds` metric creates hundreds of time series. We tested this against 120 worker cluster of OpenShift and in the spirit of trying to reduce cardinality as seen in #2279 from @aojea (and after consulting with him), this is a follow up PR along the similar lines.
image

@girishmg @trozet  kindly review if this will be acceptable to change. Thank you.

xref:
https://blog.freshtracks.io/bomb-squad-automatic-detection-and-suppression-of-prometheus-cardinality-explosions-62ca8e02fa32

Signed-off-by: Kedar Vijay Kulkarni <kkulkarni@redhat.com>

### CODE REVIEW

**Comment by dcbw** [comment]
I don't think we want to collapse these all into the same metric; we do want to differentiate between the different handlers since we know that some will be pretty quick and others not.

Instead, should we perhaps break UpdateLatency into AddLatency, UpdateLatency, and DeleteLatency?

**Comment by kedark3** [comment]
@dcbw I was thinking about the collapse too, but wasn't sure do we want to break it down or consolidate. I can update the PR with 3 different metrics in that case.

**Comment by kedark3** [comment]
@dcbw I have updated the PR with what you suggested. Please review if this is what you expect.

**Comment by kedark3** [comment]
Tested this by using the test-image-pr from github actions and deploying it in downstream 4.9 nightly cluster. All pods were stable and Running, and I could see new metrics in the prometheus. 
image
image
image
image

**Comment by kedark3** [comment]
@dcbw my understanding is also not as deep as I'd like it to be. But basically if one unique metric has too many labels it causes query times etc to be high. By splitting it in add/update/delete, my understanding is, we will reduce some strain. But if we reduce it per object type, we can possibly make it even better. I will test the current version of this PR for performance and then if you can provide list of object types we care about, I can create another version where we split metric by just object type( pod, ns, netpol and what others?) and not the operation. And see if it does better.

**Comment by dcbw** [comment]
/lgtm
thanks!

**Comment by kedark3** [comment]
Thanks for merging this Dan. In my testing I noted that it used little over ~2GB of lesser memory than it did before. That's in 50 worker cluster_density.

**Pull request merged**
