### PR TITLE
Avoid calling oc.deleteStaleNodeChassis for every node update event

### PR DESCRIPTION
**Pull request by winsopc**
In large scale zone around 800 nodes,  this check consume more than 60% of the cpu time. we only need check when old and new node object has chassis id annotation change.

#### Which issue(s) this PR fixes

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by winsopc** [comment]
pprof:
image

**Comment by winsopc** [comment]
@cathy-zhou  @trozet PTAL

**Review by girishmg — APPROVED** [review]
you have to move the call to
```
		// delete stale chassis in SBDB if any
		if err := oc.deleteStaleNodeChassis(node); err != nil {
			errs = append(errs, err)
		}
```

under

```
	if nSyncs.syncClusterRouterPort {
```

Can you please fix it?

**Review by girishmg — CHANGES_REQUESTED** [review]
see this: https://github.com/ovn-org/ovn-kubernetes/pull/4439#pullrequestreview-2155632768

**Comment by winsopc** [comment]
> you have to move the call to
> 
> ```
> 		// delete stale chassis in SBDB if any
> 		if err := oc.deleteStaleNodeChassis(node); err != nil {
> 			errs = append(errs, err)
> 		}
> ```
> 
> under
> 
> ```
> 	if nSyncs.syncClusterRouterPort {
> ```
> 
> Can you please fix it?

done. Thanks for catching that.

**Review by girishmg — APPROVED** [review]

**Pull request merged**
