### PR TITLE
fixes some typos in docs/INSTALL.OPENSHIFT.md

### PR DESCRIPTION
**Pull request by haojue**
**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by haojue** [comment]
thank you @jluhrsen, not sure why there is a failing job in CI? CI unstable as this is only a doc change?

**Comment by haojue** [comment]
> thank you @jluhrsen, not sure why there is a failing job in CI? CI unstable as this is only a doc change?

Hi @trozet @dcbw @girishmg @jcaamano , any idea on this? thanks

**Comment by haojue** [comment]
ok, all checks passed now, Hi  @jluhrsen  @trozet @dcbw @girishmg @jcaamano, could you please help merge it? Thanks

**Review by dcbw — APPROVED** [review]

**Pull request merged**
